-- EchoCore Continuum v19 cloud schema
-- Reproducible structure only. No private resident/user data or credentials.
create extension if not exists pgcrypto;
create extension if not exists vector;

create table if not exists public.echocore_devices(
  device_id text primary key,
  device_secret_hash text not null,
  created_at timestamptz not null default now(),
  last_seen timestamptz,
  app_version text,
  capabilities jsonb not null default '[]'::jsonb,
  health jsonb not null default '{}'::jsonb,
  last_error text,
  last_telemetry_at timestamptz
);

create table if not exists public.echocore_commands(
  id uuid primary key default gen_random_uuid(),
  device_id text not null,
  command jsonb not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  claimed_at timestamptz,
  completed_at timestamptz,
  response jsonb,
  attempts integer not null default 0,
  last_error text,
  expires_at timestamptz
);
create index if not exists echocore_commands_device_status_idx on public.echocore_commands(device_id,status,created_at);
create index if not exists echocore_commands_recovery_idx on public.echocore_commands(device_id,status,claimed_at);

create table if not exists public.echocore_device_events(
  id bigint generated by default as identity primary key,
  device_id text not null,
  kind text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists echocore_device_events_device_time_idx on public.echocore_device_events(device_id,created_at desc);

create table if not exists public.echocore_cloud_runtime(
  k text primary key,
  v jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.echocore_cloud_resident_state(
  resident_id text primary key,
  display_name text not null,
  persona text not null default '',
  model_plan jsonb not null default '{}'::jsonb,
  approved_overlay text not null default '',
  mood jsonb not null default '{}'::jsonb,
  last_reflection text not null default '',
  updated_at timestamptz not null default now(),
  voice text not null default '',
  native_knowledge text not null default '',
  model_preferences text[] not null default '{}'
);

create table if not exists public.echocore_cloud_conversations(
  id bigint generated by default as identity primary key,
  device_id text not null,
  resident_id text not null,
  role text not null,
  content text not null,
  created_at timestamptz not null default now(),
  thread_id text not null default '',
  source_message_id bigint
);
create index if not exists idx_ecc_conv_device_resident_time on public.echocore_cloud_conversations(device_id,resident_id,created_at desc);
create index if not exists idx_echocore_conversations_thread on public.echocore_cloud_conversations(device_id,resident_id,thread_id,created_at desc);

create table if not exists public.echocore_cloud_memories(
  id bigint generated by default as identity primary key,
  device_id text not null,
  resident_id text not null,
  memory_type text not null default 'episodic',
  text text not null,
  salience integer not null default 5,
  source_layer text not null default 'lived',
  source_ref text not null default '',
  embedding vector,
  created_at timestamptz not null default now(),
  last_accessed timestamptz not null default now()
);
create index if not exists idx_ecc_mem_device_resident_salience on public.echocore_cloud_memories(device_id,resident_id,salience desc);
create index if not exists idx_ecc_mem_device_resident_time on public.echocore_cloud_memories(device_id,resident_id,created_at desc);

create table if not exists public.echocore_global_memories(
  id bigint generated by default as identity primary key,
  resident_id text not null,
  memory_key text not null unique,
  era text not null default '',
  place text not null default '',
  memory_type text not null default 'reconstructed',
  narrative text not null,
  source_basis text not null default '',
  source_layer text not null default 'historical_reconstruction',
  confidence integer not null default 7,
  salience integer not null default 7,
  emotional_tone text not null default '',
  sensory_trace text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists idx_ecgm_resident_salience on public.echocore_global_memories(resident_id,salience desc,id);

create table if not exists public.echocore_relationships(
  device_id text not null,
  resident_id text not null,
  other_id text not null,
  affinity real not null default .5,
  trust real not null default .5,
  tension real not null default .2,
  respect real not null default .7,
  summary text not null default '',
  shared_events integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key(device_id,resident_id,other_id)
);

create table if not exists public.echocore_resonance_edges(
  device_id text not null,
  resident_id text not null,
  node_type text not null,
  node_key text not null,
  label text not null default '',
  weight real not null default 1.0,
  activations integer not null default 0,
  last_activation timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  primary key(device_id,resident_id,node_type,node_key)
);
create index if not exists idx_ecr_resident_weight on public.echocore_resonance_edges(device_id,resident_id,weight desc,last_activation desc);

create table if not exists public.echocore_cloud_knowledge(
  id bigint generated by default as identity primary key,
  device_id text not null,
  source_id text not null,
  source_name text not null,
  part integer not null default 0,
  heading text not null default '',
  text text not null,
  quality integer not null default 7,
  resident_affinity text[] not null default '{}',
  embedding vector,
  created_at timestamptz not null default now(),
  fts tsvector generated always as (to_tsvector('english',coalesce(heading,'')||' '||coalesce(text,''))) stored,
  unique(device_id,source_id,part)
);
create index if not exists idx_ecc_knowledge_device_source on public.echocore_cloud_knowledge(device_id,source_id,part);
create index if not exists idx_ecc_knowledge_fts on public.echocore_cloud_knowledge using gin(fts);

create table if not exists public.echocore_cloud_messages(
  id bigint generated by default as identity primary key,
  device_id text not null,
  resident_id text not null,
  text text not null,
  reason text not null default '',
  priority integer not null default 5,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  thread_id text not null default '',
  context_snapshot text not null default '',
  replied_at timestamptz,
  parent_message_id bigint
);
create index if not exists idx_ecc_messages_unread on public.echocore_cloud_messages(device_id,read_at,created_at desc);
create index if not exists idx_echocore_messages_thread on public.echocore_cloud_messages(device_id,resident_id,thread_id,created_at desc);

create table if not exists public.echocore_cloud_proposals(
  id uuid primary key default gen_random_uuid(),
  device_id text not null,
  resident_id text not null,
  proposal_type text not null,
  title text not null,
  detail text not null,
  benefits text not null default '',
  risks text not null default '',
  rollback text not null default '',
  tests text not null default '',
  patch jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  decided_at timestamptz
);
create index if not exists idx_ecc_proposals_device_status on public.echocore_cloud_proposals(device_id,status,created_at desc);

create table if not exists public.echocore_cloud_source_sync(
  device_id text not null,
  source_id text not null,
  source_name text not null,
  uploaded_parts integer not null default 0,
  total_parts integer not null default 0,
  total_chars bigint not null default 0,
  status text not null default 'syncing',
  updated_at timestamptz not null default now(),
  primary key(device_id,source_id)
);

create table if not exists public.echocore_resident_threads(
  thread_id text primary key,
  device_id text not null,
  resident_id text not null,
  origin_message_id bigint,
  title text not null default '',
  origin_text text not null default '',
  origin_reason text not null default '',
  origin_context text not null default '',
  summary text not null default '',
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_resident_threads_device on public.echocore_resident_threads(device_id,resident_id,updated_at desc);

create table if not exists public.echocore_thread_turns(
  id bigint generated by default as identity primary key,
  thread_id text not null,
  device_id text not null,
  resident_id text not null,
  role text not null,
  content text not null,
  source_message_id bigint,
  created_at timestamptz not null default now()
);
create index if not exists idx_thread_turns_thread on public.echocore_thread_turns(thread_id,created_at);

create or replace function public.echocore_search_knowledge_v2(p_device_id text,p_query text,p_limit integer default 6)
returns table(id bigint,source_name text,part integer,heading text,text text,quality integer,rank real)
language sql stable security definer set search_path=public as $$
  with q as (select websearch_to_tsquery('english',p_query) query)
  select k.id,k.source_name,k.part,k.heading,k.text,k.quality,ts_rank_cd(k.fts,q.query)::real
  from public.echocore_cloud_knowledge k,q
  where k.device_id=p_device_id and nullif(trim(p_query),'') is not null and k.fts @@ q.query
  order by ts_rank_cd(k.fts,q.query) desc,k.quality desc
  limit greatest(1,least(p_limit,12));
$$;

create or replace function public.echocore_preserve_source_sync_progress()
returns trigger language plpgsql as $$
begin
 new.uploaded_parts:=greatest(coalesce(old.uploaded_parts,0),coalesce(new.uploaded_parts,0));
 new.total_parts:=greatest(coalesce(old.total_parts,0),coalesce(new.total_parts,0));
 new.total_chars:=greatest(coalesce(old.total_chars,0),coalesce(new.total_chars,0));
 if old.status='ready' then new.status:='ready';
 elsif new.uploaded_parts>=new.total_parts and new.total_parts>0 then new.status:='ready'; end if;
 return new;
end $$;
drop trigger if exists trg_echocore_source_sync_progress on public.echocore_cloud_source_sync;
create trigger trg_echocore_source_sync_progress before update on public.echocore_cloud_source_sync for each row execute function public.echocore_preserve_source_sync_progress();

-- Edge Functions use service_role. Direct client access stays closed.
do $$ declare t text; begin
 foreach t in array array['echocore_devices','echocore_commands','echocore_device_events','echocore_cloud_runtime','echocore_cloud_resident_state','echocore_cloud_conversations','echocore_cloud_memories','echocore_global_memories','echocore_relationships','echocore_resonance_edges','echocore_cloud_knowledge','echocore_cloud_messages','echocore_cloud_proposals','echocore_cloud_source_sync','echocore_resident_threads','echocore_thread_turns'] loop
  execute format('alter table public.%I enable row level security',t);
  execute format('revoke all on table public.%I from anon, authenticated',t);
 end loop;
end $$;
