package com.hanma.echocore;

import android.app.Activity;import android.app.AlertDialog;import android.content.Intent;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.os.Handler;import android.os.Looper;import android.view.Gravity;import android.view.View;import android.widget.Button;import android.widget.EditText;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import android.widget.Toast;import java.util.List;

/** Ascendant cockpit: City, Phoenix, missions, claim graph, routing, black box and repair. */
public class AscendantActivity extends Activity {
    private static final int BG=0xFF05070C,PANEL=0xFF101620,PANEL2=0xFF182231,TEXT=0xFFF5F7FF,MUTED=0xFF94A1B7,GOLD=0xFFFFD070,TEAL=0xFF5CE4CD,VIOLET=0xFFAA8CFF,RED=0xFFFF7188;
    private AscendantStore city;private BrainDatabase brain;private SourceCatalog sources;private ImportStateStore queue;private DiagnosticsStore diag;private LinearLayout body;private final Handler ui=new Handler(Looper.getMainLooper());private final Runnable tick=new Runnable(){@Override public void run(){render();ui.postDelayed(this,2200);}};
    @Override protected void onCreate(Bundle s){super.onCreate(s);city=new AscendantStore(this);brain=new BrainDatabase(this);sources=new SourceCatalog(this);queue=new ImportStateStore(this);diag=new DiagnosticsStore(this);setContentView(shell());render();}
    @Override protected void onResume(){super.onResume();ui.removeCallbacks(tick);ui.post(tick);}
    @Override protected void onPause(){ui.removeCallbacks(tick);super.onPause();}
    @Override protected void onDestroy(){try{city.close();}catch(Throwable ignored){}try{brain.close();}catch(Throwable ignored){}try{sources.close();}catch(Throwable ignored){}try{queue.close();}catch(Throwable ignored){}super.onDestroy();}
    private View shell(){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setBackgroundColor(BG);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(15),dp(18),dp(15),dp(32));sc.addView(body);return sc;}
    private void render(){if(body==null||isFinishing())return;body.removeAllViews();body.addView(text("ECHOCORE Ω ASCENDANT",26,TEXT,true));body.addView(text("OMEGA CONTROL ROOM · CIVILIZATION CORE",11,GOLD,true),lp(-1,-2,0,3,0,13));
        org.json.JSONObject st=city.stats();LinearLayout stats=new LinearLayout(this);stats.setOrientation(LinearLayout.HORIZONTAL);stats.addView(stat(String.valueOf(brain.count()),"MEMORY"));stats.addView(stat(String.valueOf(sources.countSources()),"SOURCES"));stats.addView(stat(st.optString("residents","0"),"RESIDENTS"));stats.addView(stat(st.optString("claims","0"),"CLAIMS"));body.addView(stats,lp(-1,-2,0,0,0,10));
        String qstate=queue.state();LinearLayout health=card();health.addView(text("SYSTEM STATE",13,TEAL,true));Runtime r=Runtime.getRuntime();long free=(r.maxMemory()-(r.totalMemory()-r.freeMemory()))/(1024*1024);health.addView(text("Core heap headroom "+free+" MB\nPhoenix "+qstate+" · pending "+queue.pending().size()+"\nLink "+diag.state()+" · relay "+diag.lastRelayMs()+" ms",10,MUTED,false),lp(-1,-2,0,5,0,0));body.addView(health,lp(-1,-2,0,0,0,10));
        LinearLayout a=new LinearLayout(this);a.setOrientation(LinearLayout.HORIZONTAL);Button cityBtn=button("🏛 SANCTUM CITY",VIOLET,BG);cityBtn.setOnClickListener(v->open(SanctumActivity.class));Button src=button("🔥 PHOENIX SOURCES",GOLD,BG);src.setOnClickListener(v->open(SourceActivity.class));a.addView(cityBtn,new LinearLayout.LayoutParams(0,dp(52),1));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(0,dp(52),1);ap.setMargins(dp(8),0,0,0);a.addView(src,ap);body.addView(a,lp(-1,-2,0,0,0,8));
        LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.HORIZONTAL);Button neural=button("NEURAL BRAIN",PANEL2,TEAL);neural.setOnClickListener(v->open(NexusBrainActivity.class));Button link=button("AUTOLINK",PANEL2,VIOLET);link.setOnClickListener(v->open(CloudLinkActivity.class));b.addView(neural,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(48),1);bp.setMargins(dp(8),0,0,0);b.addView(link,bp);body.addView(b,lp(-1,-2,0,0,0,12));
        body.addView(section("OMEGA ROUTER","Ask normally. Ascendant chooses lookup, research, multi-hop, critic, planner, creative, mission, or council routes automatically."));EditText ask=input("Question, mission, build, research problem, contradiction…");body.addView(ask,lp(-1,-2,0,0,0,7));Button think=button("ROUTE THROUGH ASCENDANT",TEAL,BG);think.setOnClickListener(v->route(ask.getText().toString()));body.addView(think,lp(-1,dp(50),0,0,0,12));
        LinearLayout mission=card();mission.addView(text("ZORDON MISSION ENGINE",13,GOLD,true));List<String[]> ms=city.missions(3);if(ms.isEmpty())mission.addView(text("No persistent missions yet.",10,MUTED,false),lp(-1,-2,0,4,0,6));else for(String[]m:ms)mission.addView(text("#"+m[0]+" · "+m[3]+" · P"+m[4]+"\n"+m[1],10,MUTED,false),lp(-1,-2,0,5,0,3));LinearLayout mr=new LinearLayout(this);mr.setOrientation(LinearLayout.HORIZONTAL);Button nm=button("＋ NEW MISSION",PANEL2,GOLD);nm.setOnClickListener(v->newMission());Button vm=button("MISSION BOARD",PANEL2,TEAL);vm.setOnClickListener(v->missionBoard());mr.addView(nm,new LinearLayout.LayoutParams(0,dp(43),1));LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(0,dp(43),1);mp.setMargins(dp(6),0,0,0);mr.addView(vm,mp);mission.addView(mr);body.addView(mission,lp(-1,-2,0,0,0,10));
        LinearLayout sys=new LinearLayout(this);sys.setOrientation(LinearLayout.HORIZONTAL);Button graph=button("CLAIM GRAPH",PANEL2,VIOLET);graph.setOnClickListener(v->claimGraph());Button repair=button("SELF-REPAIR",PANEL2,GOLD);repair.setOnClickListener(v->selfRepair());Button black=button("BLACK BOX",PANEL2,RED);black.setOnClickListener(v->blackbox());sys.addView(graph,new LinearLayout.LayoutParams(0,dp(44),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,dp(44),1);sp.setMargins(dp(5),0,0,0);sys.addView(repair,sp);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,dp(44),1);xp.setMargins(dp(5),0,0,0);sys.addView(black,xp);body.addView(sys,lp(-1,-2,0,0,0,10));
        Button models=button("MODEL BAY · PERCEPTION / EMBEDDING / SPEECH / LOCAL LLM",PANEL2,TEAL);models.setOnClickListener(v->modelBay());body.addView(models,lp(-1,dp(48),0,0,0,0));}
    private void route(String q){if(q==null||q.trim().isEmpty()){toast("Give Ascendant something to work on");return;}toast("Routing…");new Thread(()->{BrainDatabase b=null;SourceCatalog s=null;CognitiveStore c=null;AscendantStore a=null;try{b=new BrainDatabase(this);s=new SourceCatalog(this);c=new CognitiveStore(this);a=new AscendantStore(this);BrainEngine e=new BrainEngine(b);NexusOrchestrator n=new NexusOrchestrator(b,e,s,c);HybridRetriever h=new HybridRetriever(a,s,b);ClaimGraphEngine g=new ClaimGraphEngine(a);MissionEngine m=new MissionEngine(a,h);CouncilEngine ce=new CouncilEngine(a,h,n);AscendantRouter r=new AscendantRouter(h,n,ce,g,m);String out=r.route(q);a.blackbox("ROUTER","ANSWER",q,queue.state());runOnUiThread(()->dialog("Ascendant",out));}catch(Throwable t){diag.error("ascendant_route",t);runOnUiThread(()->dialog("Router error",String.valueOf(t)));}finally{try{if(a!=null)a.close();}catch(Throwable ignored){}try{if(c!=null)c.close();}catch(Throwable ignored){}try{if(s!=null)s.close();}catch(Throwable ignored){}try{if(b!=null)b.close();}catch(Throwable ignored){}}},"OmegaRouter").start();}
    private void newMission(){EditText e=input("Goal / mission");new AlertDialog.Builder(this).setTitle("New persistent mission").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{String g=e.getText().toString().trim();if(g.isEmpty())return;HybridRetriever h=new HybridRetriever(city,sources,brain);long id=new MissionEngine(city,h).create(trim(g,70),g,8);toast("Mission "+id+" created");render();}).show();}
    private void missionBoard(){StringBuilder out=new StringBuilder();HybridRetriever h=new HybridRetriever(city,sources,brain);MissionEngine me=new MissionEngine(city,h);for(String[]m:city.missions(30)){long id=parse(m[0]);out.append(me.brief(id)).append("\nNext: ").append(me.nextAction(id)).append("\n\n────────\n\n");}dialog("Mission Board",out.length()==0?"No missions yet.":out.toString());}
    private void claimGraph(){ClaimGraphEngine g=new ClaimGraphEngine(city);StringBuilder out=new StringBuilder("Recent candidate claims:\n\n");for(String[]c:city.claims(20))out.append('#').append(c[0]).append(" · confidence ").append(c[3]).append("/10 · source ").append(c[4]).append(" part ").append(c[5]).append("\n").append(c[1]).append("\n\n");out.append("CONTRADICTION CANDIDATES\n").append(g.contradictionReport());dialog("Hermes Claim Graph",out.toString());}
    private void selfRepair(){new Thread(()->{String out=new SelfRepairEngine(this,new AscendantStore(this),new ImportStateStore(this)).run();runOnUiThread(()->dialog("Self-Repair",out));},"AscendantRepair").start();}
    private void blackbox(){StringBuilder out=new StringBuilder();for(String[]x:city.blackbox(50))out.append(x[0]).append(" · ").append(x[1]).append(" · ").append(x[2]).append(" · heap ").append(x[4]).append(" MB\n").append(x[3]).append("\n\n");dialog("Cognitive Black Box",out.length()==0?"No Ascendant black-box events yet.":out.toString());}
    private void modelBay(){StringBuilder out=new StringBuilder("ASCENDANT MODEL BAY\n\n");try(android.database.Cursor c=city.getReadableDatabase().rawQuery("SELECT name,kind,status,version FROM model_packs ORDER BY kind,name",null)){while(c.moveToNext())out.append(c.getString(0)).append(" · ").append(c.getString(1)).append(" · ").append(c.getString(2)).append(c.getString(3).isEmpty()?"":" · "+c.getString(3)).append('\n');}out.append("\nVision OCR is wired into Phoenix. Semantic fingerprint + FTS is local. Speech and GGUF generation are pack slots until a compatible offline model is installed.");dialog("Model Bay",out.toString());}
    private void open(Class<?> c){try{startActivity(new Intent(this,c));}catch(Throwable t){diag.error("open_"+c.getSimpleName(),t);toast("Screen error captured");}}
    private View section(String title,String sub){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.addView(text(title,16,TEXT,true));x.addView(text(sub,10,MUTED,false),lp(-1,-2,0,3,0,9));return x;}private LinearLayout card(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(12),dp(11),dp(12),dp(11));x.setBackground(round(PANEL,15));return x;}private LinearLayout stat(String v,String l){LinearLayout x=card();x.setGravity(Gravity.CENTER);x.setPadding(dp(4),dp(9),dp(4),dp(9));x.addView(text(v,16,TEAL,true));x.addView(text(l,7,MUTED,true));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(2),0,dp(2),0);x.setLayoutParams(p);return x;}private EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(0xFF657086);e.setTextColor(TEXT);e.setTextSize(13);e.setSingleLine(false);e.setMinLines(2);e.setPadding(dp(10),dp(10),dp(10),dp(10));e.setBackground(round(PANEL2,12));return e;}private Button button(String s,int bg,int fg){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(9);b.setTypeface(Typeface.DEFAULT_BOLD);b.setTextColor(fg);b.setBackground(round(bg,12));return b;}private TextView text(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}private GradientDrawable round(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private void dialog(String t,String m){if(isFinishing())return;new AlertDialog.Builder(this).setTitle(t).setMessage(m).setPositiveButton("Close",null).show();}private static long parse(String s){try{return Long.parseLong(s);}catch(Exception e){return 0;}}private static String trim(String s,int n){s=s==null?"":s.trim();return s.length()<=n?s:s.substring(0,n-1)+"…";}
}
