package com.hanma.echocore;

import android.app.Notification;import android.app.NotificationChannel;import android.app.NotificationManager;import android.app.PendingIntent;import android.app.Service;import android.content.Context;import android.content.Intent;import android.net.ConnectivityManager;import android.net.Network;import android.net.NetworkCapabilities;import android.os.Build;import android.os.IBinder;import org.json.JSONArray;import org.json.JSONObject;import java.io.BufferedReader;import java.io.InputStream;import java.io.InputStreamReader;import java.io.OutputStream;import java.net.HttpURLConnection;import java.net.URL;import java.nio.charset.StandardCharsets;import java.util.Locale;

/** Ascendant City Gate. Separate controller channel for residents, missions, evidence and Phoenix. */
public class AscendantLinkService extends Service {
    public static final String KEY_ENABLED="ascendant_link_enabled",KEY_ID="ascendant_device_id";private static final String KEY_SECRET="ascendant_device_secret",BASE="https://vdvdijoniwhqorawaufi.supabase.co/functions/v1/echocore-relay",CHANNEL="echocore_ascendant_link",VERSION="11.0.0";private static final int NID=18436;private volatile boolean running;private Thread worker;private SecurePrefs prefs;private DiagnosticsStore diag;
    public static void start(Context c){Intent i=new Intent(c,AscendantLinkService.class);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}
    @Override public void onCreate(){super.onCreate();prefs=new SecurePrefs(this);diag=new DiagnosticsStore(this);createChannel();startForeground(NID,note("Opening City Gate…"));}
    @Override public int onStartCommand(Intent i,int flags,int id){prefs.putBool(KEY_ENABLED,true);if(!running){running=true;worker=new Thread(this::loop,"Ascendant-CityGate");worker.setUncaughtExceptionHandler((t,e)->{diag.processCrash(t.getName(),e);running=false;stopSelf();});worker.start();}return START_STICKY;}
    private void loop(){int failures=0;while(running&&!Thread.currentThread().isInterrupted()&&prefs.getBool(KEY_ENABLED,true)){try{if(!network()){sleep(8000);continue;}ensureRegistered();heartbeat();poll();failures=0;diag.setState("ASCENDANT_LIVE");update("City Gate live");sleep(4200);}catch(InterruptedException e){Thread.currentThread().interrupt();break;}catch(Throwable t){failures++;diag.relayFailure("AscendantLink: "+safe(t),failures);if(t instanceof RelayError&&((RelayError)t).code==401)reset();sleepQuiet(Math.min(60000,3000L*(1L<<Math.min(4,failures))));}}running=false;}
    private void ensureRegistered() throws Exception{String id=prefs.get(KEY_ID,"");String sec=prefs.getSecret(KEY_SECRET);if(!id.isEmpty()&&!sec.isEmpty())return;JSONObject b=new JSONObject().put("app_version",VERSION).put("capabilities",caps());JSONObject r=post("/register",b,false);String ni=r.optString("device_id",""),ns=r.optString("device_secret","");if(ni.isEmpty()||ns.isEmpty())throw new Exception("City Gate registration failed");prefs.put(KEY_ID,ni);prefs.putSecret(KEY_SECRET,ns);diag.event("ASCENDANT_REGISTERED",shortId(ni));}
    private void heartbeat() throws Exception{JSONObject h=new JSONObject();try(BrainDatabase b=new BrainDatabase(this);SourceCatalog s=new SourceCatalog(this);AscendantStore a=new AscendantStore(this);ImportStateStore q=new ImportStateStore(this)){h.put("app_version",VERSION).put("capabilities",caps()).put("health",new JSONObject().put("state","ASCENDANT_LIVE").put("memories",b.count()).put("sources",s.countSources()).put("city",a.stats()).put("phoenix",q.snapshot()).put("reasoner","AscendantRouter"));}post("/heartbeat",h,true);}
    private void poll() throws Exception{JSONObject r=post("/poll",new JSONObject(),true);JSONArray a=r.optJSONArray("commands");if(a==null)return;for(int i=0;i<a.length();i++){JSONObject row=a.optJSONObject(i);if(row==null)continue;String cid=row.optString("id","");JSONObject cmd=row.optJSONObject("command");if(cid.isEmpty()||cmd==null)continue;JSONObject resp=new JSONObject();String action=cmd.optString("action","");try{JSONObject p=cmd.optJSONObject("payload");if(p==null)p=new JSONObject();resp.put("status","ok").put("payload",execute(action,p));}catch(Throwable t){resp.put("status","error").put("payload",new JSONObject().put("type",t.getClass().getSimpleName()).put("message",safe(t)));diag.error("city_gate:"+action,t);}post("/respond",new JSONObject().put("command_id",cid).put("response",resp),true);diag.commandDone("ASC:"+action);}}
    private Object execute(String action,JSONObject p) throws Exception{
        try(BrainDatabase b=new BrainDatabase(this);SourceCatalog s=new SourceCatalog(this);CognitiveStore c=new CognitiveStore(this);AscendantStore a=new AscendantStore(this);ImportStateStore q=new ImportStateStore(this)){
            BrainEngine e=new BrainEngine(b);NexusOrchestrator n=new NexusOrchestrator(b,e,s,c);HybridRetriever h=new HybridRetriever(a,s,b);ClaimGraphEngine g=new ClaimGraphEngine(a);MissionEngine m=new MissionEngine(a,h);CouncilEngine ce=new CouncilEngine(a,h,n);AscendantRouter router=new AscendantRouter(h,n,ce,g,m);
            switch(action){
                case "health":return new JSONObject().put("version",VERSION).put("brain",b.count()).put("sources",s.countSources()).put("city",a.stats()).put("phoenix",q.snapshot()).put("link",diag.snapshotJson());
                case "ascendant_route":return new JSONObject().put("answer",router.route(p.optString("q",p.optString("question",""))));
                case "hybrid_search":return hits(h.search(p.optString("q",""),Math.max(1,Math.min(30,p.optInt("limit",10)))));
                case "council_convene":return new JSONObject().put("transcript",ce.convene(p.optString("topic",p.optString("q","")),Math.max(1,Math.min(20,p.optInt("residents",20)))));
                case "residents_list":return residents(a.residents());
                case "resident_speak":return new JSONObject().put("response",ce.speak(p.optString("resident_id","omega"),p.optString("topic",p.optString("q",""))));
                case "resident_presence":a.setResidentStatus(p.optString("resident_id",""),p.optString("status","HOME"));return new JSONObject().put("ok",true);
                case "resident_add":return new JSONObject().put("resident_row",a.addResident(p.optString("name","New resident"),p.optString("archetype","Specialist"),p.optString("guild","Explorers"),p.optString("lens","Explore the assigned problem carefully.")));
                case "mission_create":{String goal=p.optString("goal","");long id=m.create(p.optString("title",goal),goal,p.optInt("priority",8));return new JSONObject().put("mission_id",id).put("brief",m.brief(id));}
                case "missions_list":return missions(a,m);
                case "mission_brief":{long id=p.optLong("mission_id",0);return new JSONObject().put("brief",m.brief(id)).put("next",m.nextAction(id)).put("evidence",m.evidenceForMission(id));}
                case "mission_step":a.setMissionStep(p.optLong("step_id",0),p.optString("status","DONE"));return new JSONObject().put("ok",true);
                case "claims_list":return claims(a.claims(Math.max(1,Math.min(100,p.optInt("limit",30)))));
                case "contradictions":return new JSONObject().put("report",g.contradictionReport());
                case "phoenix_status":return q.snapshot();
                case "phoenix_start":DocumentImportService.start(this);return new JSONObject().put("ok",true).put("pending",q.pending().size());
                case "phoenix_cancel":DocumentImportService.cancel(this);return new JSONObject().put("ok",true);
                case "blackbox":return blackbox(a.blackbox(Math.max(1,Math.min(100,p.optInt("limit",30)))));
                case "self_repair":return new JSONObject().put("report",new SelfRepairEngine(this,a,q).run());
                case "brain_search":return memories(b.search(p.optString("q",""),Math.max(1,Math.min(50,p.optInt("limit",10)))));
                case "memory_add":{String text=p.optString("text","").trim();if(text.isEmpty())throw new Exception("Missing text");long id=b.addMemoryRich(text,p.optString("type","THOUGHT"),p.optString("tags","ascendant"),p.optInt("importance",6),p.optInt("valence",0),p.optInt("confidence",7),p.optInt("novelty",5),p.optBoolean("active",false));a.evidence(id,"REMOTE",0,0,0,"CITY_GATE",p.optInt("confidence",7));return new JSONObject().put("memory_id",id);}
                case "source_search":{JSONArray x=new JSONArray();for(String[]z:s.searchChunks(p.optString("q",""),Math.max(1,Math.min(50,p.optInt("limit",10)))))x.put(new JSONObject().put("source",z[0]).put("part",z[1]).put("text",z[2]));return x;}
                case "sources_list":{JSONArray x=new JSONArray();for(String[]z:s.recentSources(Math.max(1,Math.min(50,p.optInt("limit",20)))))x.put(new JSONObject().put("id",z[0]).put("name",z[1]).put("mime",z[2]).put("chars",z[5]).put("chunks",z[6]));return x;}
                case "model_packs":{JSONArray x=new JSONArray();try(android.database.Cursor z=a.getReadableDatabase().rawQuery("SELECT id,name,kind,status,version FROM model_packs ORDER BY kind,name",null)){while(z.moveToNext())x.put(new JSONObject().put("id",z.getString(0)).put("name",z.getString(1)).put("kind",z.getString(2)).put("status",z.getString(3)).put("version",z.getString(4)));}return x;}
                case "capabilities":return caps();default:throw new Exception("Unknown Ascendant action: "+action);
            }
        }
    }
    private JSONArray caps(){String[]x={"health","ascendant_route","hybrid_search","council_convene","residents_list","resident_speak","resident_presence","resident_add","mission_create","missions_list","mission_brief","mission_step","claims_list","contradictions","phoenix_status","phoenix_start","phoenix_cancel","blackbox","self_repair","brain_search","memory_add","source_search","sources_list","model_packs","capabilities"};JSONArray a=new JSONArray();for(String s:x)a.put(s);return a;}
    private JSONArray hits(java.util.List<HybridRetriever.Hit> l)throws Exception{JSONArray a=new JSONArray();for(HybridRetriever.Hit h:l)a.put(new JSONObject().put("source_id",h.sourceId).put("part",h.part).put("memory_id",h.memoryId).put("channel",h.channel).put("score",h.score).put("text",h.text));return a;}
    private JSONArray residents(java.util.List<String[]>l)throws Exception{JSONArray a=new JSONArray();for(String[]r:l)a.put(new JSONObject().put("id",r[0]).put("name",r[1]).put("archetype",r[2]).put("room",r[3]).put("guild",r[4]).put("status",r[5]).put("lens",r[6]).put("model_pack",r[7]));return a;}
    private JSONArray missions(AscendantStore a,MissionEngine m)throws Exception{JSONArray x=new JSONArray();for(String[]z:a.missions(50)){long id=Long.parseLong(z[0]);x.put(new JSONObject().put("id",id).put("title",z[1]).put("goal",z[2]).put("status",z[3]).put("priority",z[4]).put("next",m.nextAction(id)));}return x;}
    private JSONArray claims(java.util.List<String[]>l)throws Exception{JSONArray a=new JSONArray();for(String[]r:l)a.put(new JSONObject().put("id",r[0]).put("text",r[1]).put("status",r[2]).put("confidence",r[3]).put("source_id",r[4]).put("part",r[5]));return a;}
    private JSONArray blackbox(java.util.List<String[]>l)throws Exception{JSONArray a=new JSONArray();for(String[]r:l)a.put(new JSONObject().put("ts",r[0]).put("subsystem",r[1]).put("event",r[2]).put("detail",r[3]).put("heap_free_mb",r[4]).put("queue",r[5]));return a;}
    private void postAuth(HttpURLConnection c){c.setRequestProperty("X-Device-Id",prefs.get(KEY_ID,""));c.setRequestProperty("X-Device-Secret",prefs.getSecret(KEY_SECRET));}
    private JSONObject post(String path,JSONObject body,boolean auth)throws Exception{long start=android.os.SystemClock.elapsedRealtime();HttpURLConnection c=(HttpURLConnection)new URL(BASE+path).openConnection();try{c.setRequestMethod("POST");c.setConnectTimeout(12000);c.setReadTimeout(20000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");if(auth)postAuth(c);byte[] data=body.toString().getBytes(StandardCharsets.UTF_8);c.setFixedLengthStreamingMode(data.length);try(OutputStream o=c.getOutputStream()){o.write(data);}int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();String txt=read(in);if(code<200||code>=300)throw new RelayError(code,txt);diag.relaySuccess(android.os.SystemClock.elapsedRealtime()-start);if(txt.trim().isEmpty())return new JSONObject();return new JSONObject(txt);}finally{c.disconnect();}}
    private static String read(InputStream in)throws Exception{if(in==null)return "";StringBuilder b=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String l;while((l=r.readLine())!=null){b.append(l);if(b.length()>2_000_000)throw new Exception("Relay response too large");}}return b.toString();}
    private boolean network(){try{ConnectivityManager cm=(ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE);if(cm==null)return true;Network n=cm.getActiveNetwork();if(n==null)return false;NetworkCapabilities c=cm.getNetworkCapabilities(n);return c!=null&&c.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET);}catch(Throwable t){return true;}}
    private void reset(){prefs.remove(KEY_ID);prefs.remove(KEY_SECRET);}
    private void sleep(long ms)throws InterruptedException{Thread.sleep(ms);}private void sleepQuiet(long ms){try{Thread.sleep(ms);}catch(InterruptedException e){Thread.currentThread().interrupt();}}
    private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationManager n=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(n!=null)n.createNotificationChannel(new NotificationChannel(CHANNEL,"EchoCore Ascendant City Gate",NotificationManager.IMPORTANCE_LOW));}}
    private Notification note(String s){PendingIntent p=PendingIntent.getActivity(this,93,new Intent(this,AscendantActivity.class),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);return b.setSmallIcon(android.R.drawable.stat_notify_sync).setContentTitle("EchoCore Ω Ascendant").setContentText(s).setContentIntent(p).setOnlyAlertOnce(true).setOngoing(true).build();}private void update(String s){NotificationManager n=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(n!=null)n.notify(NID,note(s));}
    @Override public void onDestroy(){running=false;if(worker!=null)worker.interrupt();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}private static String safe(Throwable t){if(t==null)return "unknown";String s=t.getClass().getSimpleName()+": "+(t.getMessage()==null?"":t.getMessage());return s.length()>800?s.substring(0,800):s;}private static String shortId(String s){return s.length()>12?s.substring(0,6)+"…"+s.substring(s.length()-6):s;}private static class RelayError extends Exception{final int code;RelayError(int c,String m){super(m);code=c;}}
}
