package com.hanma.echocore;

import android.app.Activity;import android.app.AlertDialog;import android.content.Intent;import android.graphics.Canvas;import android.graphics.LinearGradient;import android.graphics.Paint;import android.graphics.RadialGradient;import android.graphics.Shader;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.os.Handler;import android.os.Looper;import android.view.Gravity;import android.view.View;import android.widget.Button;import android.widget.EditText;import android.widget.FrameLayout;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import android.widget.Toast;import java.util.List;

/** Immersive Ascendant command deck. Live data updates without rebuilding the screen tree. */
public class AscendantActivity extends Activity {
    private static final int TEXT=0xFFF6F7FF,MUTED=0xFF96A4BB,GOLD=0xFFFFD36F,TEAL=0xFF62E7D1,VIOLET=0xFFAE91FF,RED=0xFFFF7188,PANEL=0xD90C1422,PANEL2=0xDD131E30;
    private AscendantStore city;private BrainDatabase brain;private SourceCatalog sources;private ImportStateStore queue;private DiagnosticsStore diag;private TextView memStat,srcStat,resStat,claimStat,healthText,missionText,gateBadge;private AscendantCityView miniCity;private EditText ask;private final Handler ui=new Handler(Looper.getMainLooper());private final Runnable tick=new Runnable(){public void run(){refreshLive();ui.postDelayed(this,2200);}};
    @Override protected void onCreate(Bundle b){super.onCreate(b);city=new AscendantStore(this);brain=new BrainDatabase(this);sources=new SourceCatalog(this);queue=new ImportStateStore(this);diag=new DiagnosticsStore(this);setContentView(build());try{AscendantLinkService.start(this);}catch(Throwable t){diag.error("start_city_gate",t);}refreshLive();}
    @Override protected void onResume(){super.onResume();ui.removeCallbacks(tick);ui.post(tick);if(miniCity!=null)miniCity.setResidents(city.residents());}
    @Override protected void onPause(){ui.removeCallbacks(tick);super.onPause();}
    @Override protected void onDestroy(){try{city.close();}catch(Throwable ignored){}try{brain.close();}catch(Throwable ignored){}try{sources.close();}catch(Throwable ignored){}try{queue.close();}catch(Throwable ignored){}super.onDestroy();}
    private View build(){FrameLayout root=new FrameLayout(this);root.addView(new CoreField(this),new FrameLayout.LayoutParams(-1,-1));ScrollView sc=new ScrollView(this);sc.setFillViewport(true);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(14),dp(18),dp(14),dp(30));sc.addView(body);root.addView(sc,new FrameLayout.LayoutParams(-1,-1));
        TextView title=text("OMEGA CONTROL DECK",25,TEXT,true);title.setGravity(Gravity.CENTER);body.addView(title);gateBadge=text("CITY GATE · CONNECTING",9,GOLD,true);gateBadge.setGravity(Gravity.CENTER);body.addView(gateBadge,lp(-1,-2,0,3,0,6));
        miniCity=new AscendantCityView(this);miniCity.setResidents(city.residents());miniCity.setListener(new AscendantCityView.Listener(){public void onResidentSelected(String id){Intent i=new Intent(AscendantActivity.this,ResidentRoomActivity.class);i.putExtra("resident_id",id);startActivity(i);}public void onCoreSelected(){open(CouncilChamberActivity.class);}});body.addView(miniCity,new LinearLayout.LayoutParams(-1,dp(275)));
        LinearLayout stats=new LinearLayout(this);memStat=stat(stats,"0","MEMORIES");srcStat=stat(stats,"0","SOURCES");resStat=stat(stats,"0","RESIDENTS");claimStat=stat(stats,"0","CLAIMS");body.addView(stats,lp(-1,-2,0,0,0,10));
        LinearLayout health=glass();health.addView(text("SYSTEM NERVOUS SYSTEM",11,TEAL,true));healthText=text("Reading live state…",10,MUTED,false);health.addView(healthText,lp(-1,-2,0,5,0,0));body.addView(health,lp(-1,-2,0,0,0,10));
        LinearLayout q1=new LinearLayout(this);q1.setOrientation(LinearLayout.HORIZONTAL);addAction(q1,"SANCTUM CITY",VIOLET,()->open(SanctumActivity.class),0);addAction(q1,"COUNCIL",0xFF2D3150,()->open(CouncilChamberActivity.class),1);body.addView(q1,lp(-1,-2,0,0,0,7));LinearLayout q2=new LinearLayout(this);q2.setOrientation(LinearLayout.HORIZONTAL);addAction(q2,"PHOENIX FORGE",GOLD,()->open(SourceActivity.class),0);addAction(q2,"NEURAL BRAIN",0xFF173E43,()->open(NexusBrainActivity.class),1);body.addView(q2,lp(-1,-2,0,0,0,13));
        body.addView(text("OMEGA ROUTER",16,TEXT,true));body.addView(text("One command surface for research, synthesis, critique, planning, multi-hop retrieval, mission work and council routing.",10,MUTED,false),lp(-1,-2,0,3,0,8));ask=new EditText(this);ask.setTextColor(TEXT);ask.setHintTextColor(0xFF69758C);ask.setHint("Ask, build, compare, investigate, plan…");ask.setTextSize(13);ask.setMinLines(3);ask.setMaxLines(8);ask.setPadding(dp(13),dp(11),dp(13),dp(11));ask.setBackground(round(PANEL2,18));body.addView(ask,lp(-1,-2,0,0,0,8));Button route=button("ROUTE THROUGH ASCENDANT",TEAL,0xFF04100E);route.setOnClickListener(v->route());body.addView(route,new LinearLayout.LayoutParams(-1,dp(52)));
        LinearLayout m=glass();LinearLayout mh=new LinearLayout(this);mh.setGravity(Gravity.CENTER_VERTICAL);mh.addView(text("MISSION OBSERVATORY",13,GOLD,true),new LinearLayout.LayoutParams(0,-2,1));Button plus=button("＋",0x221FFFFFF,GOLD);plus.setOnClickListener(v->newMission());mh.addView(plus,new LinearLayout.LayoutParams(dp(46),dp(38)));m.addView(mh);missionText=text("No active missions",10,MUTED,false);m.addView(missionText,lp(-1,-2,0,6,0,8));Button board=button("OPEN MISSION BOARD",0x221FFFFFF,TEAL);board.setOnClickListener(v->missionBoard());m.addView(board,new LinearLayout.LayoutParams(-1,dp(42)));body.addView(m,lp(-1,-2,0,12,0,10));
        LinearLayout sys=new LinearLayout(this);sys.setOrientation(LinearLayout.HORIZONTAL);addSmall(sys,"CLAIM GRAPH",VIOLET,()->claimGraph(),0);addSmall(sys,"SELF-REPAIR",GOLD,()->selfRepair(),1);addSmall(sys,"BLACK BOX",RED,()->blackbox(),1);body.addView(sys,lp(-1,-2,0,0,0,8));Button models=button("MODEL BAY · OCR · RETRIEVAL · SPEECH · LOCAL MODEL",0x221FFFFFF,TEAL);models.setOnClickListener(v->modelBay());body.addView(models,new LinearLayout.LayoutParams(-1,dp(48)));return root;}
    private void refreshLive(){if(isFinishing())return;org.json.JSONObject st=city.stats();memStat.setText(String.valueOf(brain.count()));srcStat.setText(String.valueOf(sources.countSources()));resStat.setText(st.optString("residents","0"));claimStat.setText(st.optString("claims","0"));Runtime r=Runtime.getRuntime();long free=(r.maxMemory()-(r.totalMemory()-r.freeMemory()))/(1024*1024);String q=queue.state();healthText.setText("CORE HEAP  "+free+" MB free\nPHOENIX  "+q+" · "+queue.pending().size()+" queued\nCITY GATE  "+diag.state()+" · "+diag.lastRelayMs()+" ms relay");gateBadge.setText(diag.state().contains("LIVE")?"CITY GATE · LIVE":"CITY GATE · "+diag.state());List<String[]>ms=city.missions(3);StringBuilder x=new StringBuilder();for(String[]z:ms)x.append("#").append(z[0]).append("  P").append(z[4]).append("  ").append(z[3]).append("\n").append(z[1]).append("\n\n");missionText.setText(x.length()==0?"No active missions. Create one and Ascendant will keep its steps and evidence requirements persistent.":x.toString().trim());}
    private void route(){String q=ask.getText().toString().trim();if(q.isEmpty())return;toast("Ascendant routing…");new Thread(()->{BrainDatabase b=null;SourceCatalog s=null;CognitiveStore c=null;AscendantStore a=null;try{b=new BrainDatabase(this);s=new SourceCatalog(this);c=new CognitiveStore(this);a=new AscendantStore(this);BrainEngine e=new BrainEngine(b);NexusOrchestrator n=new NexusOrchestrator(b,e,s,c);HybridRetriever h=new HybridRetriever(a,s,b);ClaimGraphEngine g=new ClaimGraphEngine(a);MissionEngine m=new MissionEngine(a,h);CouncilEngine ce=new CouncilEngine(a,h,n);String out=new AscendantRouter(h,n,ce,g,m).route(q);a.blackbox("ROUTER","ANSWER",q,queue.state());runOnUiThread(()->dialog("Ω Ascendant",out));}catch(Throwable t){diag.error("ascendant_route",t);runOnUiThread(()->dialog("Router error",String.valueOf(t)));}finally{try{if(a!=null)a.close();}catch(Throwable ignored){}try{if(c!=null)c.close();}catch(Throwable ignored){}try{if(s!=null)s.close();}catch(Throwable ignored){}try{if(b!=null)b.close();}catch(Throwable ignored){}}},"OmegaRouter").start();}
    private void newMission(){EditText e=input("Goal / mission");new AlertDialog.Builder(this).setTitle("Create persistent mission").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{String g=e.getText().toString().trim();if(g.isEmpty())return;long id=new MissionEngine(city,new HybridRetriever(city,sources,brain)).create(trim(g,70),g,8);toast("Mission "+id+" created");refreshLive();}).show();}
    private void missionBoard(){StringBuilder out=new StringBuilder();MissionEngine me=new MissionEngine(city,new HybridRetriever(city,sources,brain));for(String[]m:city.missions(30)){long id=parse(m[0]);out.append(me.brief(id)).append("\nNEXT  ").append(me.nextAction(id)).append("\n\n────────\n\n");}dialog("Mission Observatory",out.length()==0?"No missions yet.":out.toString());}
    private void claimGraph(){ClaimGraphEngine g=new ClaimGraphEngine(city);StringBuilder out=new StringBuilder();for(String[]c:city.claims(25))out.append("#").append(c[0]).append(" · C").append(c[3]).append("/10 · S").append(c[4]).append(":").append(c[5]).append("\n").append(c[1]).append("\n\n");out.append("CONTRADICTION CANDIDATES\n").append(g.contradictionReport());dialog("Hermes Evidence Constellation",out.length()==0?"No claims yet.":out.toString());}
    private void selfRepair(){new Thread(()->{AscendantStore a=null;ImportStateStore q=null;try{a=new AscendantStore(this);q=new ImportStateStore(this);String out=new SelfRepairEngine(this,a,q).run();runOnUiThread(()->dialog("Self-Repair",out));}catch(Throwable t){diag.error("self_repair",t);}finally{try{if(a!=null)a.close();}catch(Throwable ignored){}try{if(q!=null)q.close();}catch(Throwable ignored){}}},"AscendantRepair").start();}
    private void blackbox(){StringBuilder out=new StringBuilder();for(String[]x:city.blackbox(60))out.append(x[0]).append(" · ").append(x[1]).append(" / ").append(x[2]).append(" · heap ").append(x[4]).append(" MB\n").append(x[3]).append("\n\n");dialog("Cognitive Black Box",out.length()==0?"No black-box events yet.":out.toString());}
    private void modelBay(){StringBuilder out=new StringBuilder();try(android.database.Cursor c=city.getReadableDatabase().rawQuery("SELECT name,kind,status,version FROM model_packs ORDER BY kind,name",null)){while(c.moveToNext())out.append(c.getString(0)).append(" · ").append(c.getString(1)).append(" · ").append(c.getString(2)).append(c.getString(3).isEmpty()?"":" · "+c.getString(3)).append('\n');}out.append("\nBundled: Vision OCR. Local: semantic fingerprint + FTS. Speech and GGUF generation remain installable pack slots until compatible offline engines are present.");dialog("Model Bay",out.toString());}
    private TextView stat(LinearLayout row,String value,String label){LinearLayout box=glass();box.setGravity(Gravity.CENTER);box.setPadding(dp(3),dp(8),dp(3),dp(8));TextView v=text(value,16,TEAL,true);box.addView(v);box.addView(text(label,7,MUTED,true));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(2),0,dp(2),0);row.addView(box,p);return v;}
    private void addAction(LinearLayout row,String s,int accent,Runnable run,int margin){Button b=button(s,accent,accent==GOLD?0xFF0D0900:0xFF05070D);b.setOnClickListener(v->run.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(54),1);if(margin>0)p.setMargins(dp(7),0,0,0);row.addView(b,p);}private void addSmall(LinearLayout row,String s,int accent,Runnable run,int margin){Button b=button(s,0x331FFFFFF,accent);b.setOnClickListener(v->run.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(44),1);if(margin>0)p.setMargins(dp(5),0,0,0);row.addView(b,p);}private LinearLayout glass(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(12),dp(11),dp(12),dp(11));GradientDrawable g=round(PANEL,17);g.setStroke(dp(1),0x2239C9D3);x.setBackground(g);return x;}private EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(0xFF68748A);e.setTextColor(TEXT);e.setPadding(dp(10),dp(10),dp(10),dp(10));return e;}private Button button(String s,int bg,int fg){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(9);b.setTypeface(Typeface.DEFAULT_BOLD);b.setTextColor(fg);b.setBackground(round(bg,15));return b;}private TextView text(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}private GradientDrawable round(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}private void open(Class<?> c){try{startActivity(new Intent(this,c));}catch(Throwable t){diag.error("open_"+c.getSimpleName(),t);toast("Screen error captured");}}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private void dialog(String t,String m){if(isFinishing())return;new AlertDialog.Builder(this).setTitle(t).setMessage(m).setPositiveButton("Close",null).show();}private static long parse(String s){try{return Long.parseLong(s);}catch(Exception e){return 0;}}private static String trim(String s,int n){s=s==null?"":s.trim();return s.length()<=n?s:s.substring(0,n-1)+"…";}
    private class CoreField extends View{Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);long t0=System.currentTimeMillis();CoreField(android.content.Context c){super(c);}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight(),t=(System.currentTimeMillis()-t0)/1000f;p.setShader(new LinearGradient(0,0,w,h,new int[]{0xFF02050A,0xFF07101C,0xFF120A1D,0xFF02050A},null,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);float pulse=1f+(float)Math.sin(t*.6f)*.06f;p.setShader(new RadialGradient(w*.5f,h*.18f,w*.7f*pulse,new int[]{0x2E5CE7D1,0x227A5CFF,0x00000000},null,Shader.TileMode.CLAMP));c.drawCircle(w*.5f,h*.18f,w*.7f*pulse,p);p.setShader(null);postInvalidateOnAnimation();}}
}
