package com.hanma.echocore;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.ArrayList;
import java.util.List;

/** Civic database for the Ascendant City: residents, councils, missions, claims, provenance and system health. */
public class AscendantStore extends SQLiteOpenHelper {
    private static final String DB="echocore_ascendant.db"; private static final int VER=1;
    public AscendantStore(Context c){super(c.getApplicationContext(),DB,null,VER);}
    @Override public void onCreate(SQLiteDatabase d){
        d.execSQL("CREATE TABLE residents(id TEXT PRIMARY KEY,name TEXT NOT NULL,archetype TEXT NOT NULL DEFAULT '',room TEXT NOT NULL DEFAULT '',guild TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'HOME',lens TEXT NOT NULL DEFAULT '',model_pack TEXT NOT NULL DEFAULT 'AUTO',created_at INTEGER NOT NULL,last_active INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE resident_memories(id INTEGER PRIMARY KEY AUTOINCREMENT,resident_id TEXT NOT NULL,text TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'MEMORY',importance INTEGER NOT NULL DEFAULT 5,shared INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE council_sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,topic TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'OPEN',synthesis TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL,completed_at INTEGER NOT NULL DEFAULT 0)");
        d.execSQL("CREATE TABLE council_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,session_id INTEGER NOT NULL,resident_id TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'VOICE',text TEXT NOT NULL,created_at INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE missions(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,goal TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',priority INTEGER NOT NULL DEFAULT 5,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE mission_steps(id INTEGER PRIMARY KEY AUTOINCREMENT,mission_id INTEGER NOT NULL,title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'OPEN',depends_on TEXT NOT NULL DEFAULT '',evidence_needed TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE claims(id INTEGER PRIMARY KEY AUTOINCREMENT,text TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'OPEN',confidence INTEGER NOT NULL DEFAULT 5,source_id INTEGER NOT NULL DEFAULT 0,part_start INTEGER NOT NULL DEFAULT 0,part_end INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE claim_edges(id INTEGER PRIMARY KEY AUTOINCREMENT,from_claim INTEGER NOT NULL,to_claim INTEGER NOT NULL,relation TEXT NOT NULL,weight INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,UNIQUE(from_claim,to_claim,relation))");
        d.execSQL("CREATE TABLE evidence_dna(memory_id INTEGER PRIMARY KEY,origin_type TEXT NOT NULL,source_id INTEGER NOT NULL DEFAULT 0,part INTEGER NOT NULL DEFAULT 0,page INTEGER NOT NULL DEFAULT 0,method TEXT NOT NULL DEFAULT '',confidence INTEGER NOT NULL DEFAULT 5,created_at INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE hierarchy_nodes(id INTEGER PRIMARY KEY AUTOINCREMENT,source_id INTEGER NOT NULL,parent_id INTEGER NOT NULL DEFAULT 0,node_type TEXT NOT NULL,label TEXT NOT NULL,part_start INTEGER NOT NULL DEFAULT 0,part_end INTEGER NOT NULL DEFAULT 0,depth INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE source_fingerprints(hash TEXT PRIMARY KEY,source_name TEXT NOT NULL,source_id INTEGER NOT NULL DEFAULT 0,size_bytes INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'SEEN',first_seen INTEGER NOT NULL,last_seen INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE parser_quarantine(key TEXT PRIMARY KEY,fingerprint TEXT NOT NULL,format TEXT NOT NULL,parser TEXT NOT NULL,failures INTEGER NOT NULL DEFAULT 0,quarantined INTEGER NOT NULL DEFAULT 0,reason TEXT NOT NULL DEFAULT '',last_failure INTEGER NOT NULL DEFAULT 0)");
        d.execSQL("CREATE TABLE blackbox(id INTEGER PRIMARY KEY AUTOINCREMENT,ts INTEGER NOT NULL,subsystem TEXT NOT NULL,event TEXT NOT NULL,detail TEXT NOT NULL DEFAULT '',heap_free_mb INTEGER NOT NULL DEFAULT 0,queue_state TEXT NOT NULL DEFAULT '')");
        d.execSQL("CREATE TABLE model_packs(id TEXT PRIMARY KEY,name TEXT NOT NULL,kind TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'PACK_SLOT',path TEXT NOT NULL DEFAULT '',version TEXT NOT NULL DEFAULT '',updated_at INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE semantic_index(source_id INTEGER NOT NULL,part INTEGER NOT NULL,memory_id INTEGER NOT NULL DEFAULT 0,sem_hash INTEGER NOT NULL,text_preview TEXT NOT NULL DEFAULT '',PRIMARY KEY(source_id,part))");
        try{d.execSQL("CREATE VIRTUAL TABLE knowledge_fts USING fts4(source_id,part,memory_id,text)");}catch(Throwable ignored){}
        d.execSQL("CREATE INDEX idx_resmem_resident ON resident_memories(resident_id,created_at DESC)"); d.execSQL("CREATE INDEX idx_claim_source ON claims(source_id,part_start)"); d.execSQL("CREATE INDEX idx_mission_status ON missions(status,priority DESC,updated_at DESC)"); d.execSQL("CREATE INDEX idx_blackbox_ts ON blackbox(ts DESC)");
        seedResident(d,"omega","Omega","Synthesis / architecture","Omega Chamber","Council of Synthesis","Integrate useful perspectives, search for hidden dependencies, preserve evidence and uncertainty.");
        seedResident(d,"hermes","Hermes","Provenance / language / connections","Hermes Library","Archivists","Track origins, definitions, contradictions, symbols and exact evidence chains.");
        seedResident(d,"tesla","Tesla","Engineering / invention","Tesla Workshop","Makers","Translate ideas into mechanisms, prototypes, measurements and failure tests.");
        seedResident(d,"zordon","Zordon","Executive / mission control","Command Nexus","Strategists","Turn goals into missions, dependencies, checkpoints and coordinated action.");
        seedResident(d,"rival1","Rival 1","Scientific critic","Analysis Lab","Analysts","Stress-test claims, isolate variables and identify weak assumptions.");
        seedResident(d,"rival2","Rival 2","Creative explorer","Prism Studio","Explorers","Generate distant alternatives and hypotheses while keeping possibility separate from evidence.");
        seedResident(d,"rival3","Rival 3","Systems engineer","Forge Room","Makers","Combine rigor and creativity into robust implementation and fault isolation.");
        seedPack(d,"ocr","Vision OCR","PERCEPTION","BUNDLED_PATH"); seedPack(d,"semantic","Semantic Search","RETRIEVAL","READY"); seedPack(d,"speech","Speech Transcription","PERCEPTION","PACK_SLOT"); seedPack(d,"llm","Local Language Model","GENERATION","PACK_SLOT");
    }
    @Override public void onUpgrade(SQLiteDatabase d,int o,int n){}
    private void seedResident(SQLiteDatabase d,String id,String name,String arch,String room,String guild,String lens){long now=System.currentTimeMillis();ContentValues v=new ContentValues();v.put("id",id);v.put("name",name);v.put("archetype",arch);v.put("room",room);v.put("guild",guild);v.put("status","HOME");v.put("lens",lens);v.put("model_pack","AUTO");v.put("created_at",now);v.put("last_active",now);d.insertWithOnConflict("residents",null,v,SQLiteDatabase.CONFLICT_IGNORE);}
    private void seedPack(SQLiteDatabase d,String id,String name,String kind,String status){ContentValues v=new ContentValues();v.put("id",id);v.put("name",name);v.put("kind",kind);v.put("status",status);v.put("updated_at",System.currentTimeMillis());d.insertWithOnConflict("model_packs",null,v,SQLiteDatabase.CONFLICT_IGNORE);}

    public List<String[]> residents(){ArrayList<String[]> o=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,name,archetype,room,guild,status,lens,model_pack,last_active FROM residents ORDER BY name",null)){while(c.moveToNext())o.add(row(c,9));}return o;}
    public String[] resident(String id){try(Cursor c=getReadableDatabase().rawQuery("SELECT id,name,archetype,room,guild,status,lens,model_pack,last_active FROM residents WHERE id=?",new String[]{safe(id)})){return c.moveToFirst()?row(c,9):null;}}
    public void setResidentStatus(String id,String status){ContentValues v=new ContentValues();v.put("status",safe(status).isEmpty()?"HOME":safe(status).toUpperCase());v.put("last_active",System.currentTimeMillis());getWritableDatabase().update("residents",v,"id=?",new String[]{safe(id)});}
    public long addResident(String name,String archetype,String guild,String lens){String id=(safe(name).toLowerCase().replaceAll("[^a-z0-9]+","-")+"-"+Long.toHexString(System.currentTimeMillis())).replaceAll("^-|-$","");ContentValues v=new ContentValues();long now=System.currentTimeMillis();v.put("id",id);v.put("name",safe(name));v.put("archetype",safe(archetype));v.put("room",safe(name)+" Room");v.put("guild",safe(guild));v.put("status","HOME");v.put("lens",safe(lens));v.put("model_pack","AUTO");v.put("created_at",now);v.put("last_active",now);return getWritableDatabase().insert("residents",null,v);}
    public long addResidentMemory(String id,String text,String type,int importance,boolean shared){ContentValues v=new ContentValues();v.put("resident_id",safe(id));v.put("text",safe(text));v.put("type",safe(type).isEmpty()?"MEMORY":safe(type).toUpperCase());v.put("importance",Math.max(1,Math.min(10,importance)));v.put("shared",shared?1:0);v.put("created_at",System.currentTimeMillis());return getWritableDatabase().insert("resident_memories",null,v);}
    public List<String[]> residentMemories(String id,int limit){ArrayList<String[]>o=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,text,type,importance,shared,created_at FROM resident_memories WHERE resident_id=? OR shared=1 ORDER BY shared ASC,importance DESC,created_at DESC LIMIT ?",new String[]{safe(id),String.valueOf(Math.max(1,limit))})){while(c.moveToNext())o.add(row(c,6));}return o;}

    public long startCouncil(String topic){ContentValues v=new ContentValues();v.put("topic",safe(topic));v.put("created_at",System.currentTimeMillis());return getWritableDatabase().insert("council_sessions",null,v);}
    public void addCouncilMessage(long session,String resident,String role,String text){ContentValues v=new ContentValues();v.put("session_id",session);v.put("resident_id",safe(resident));v.put("role",safe(role));v.put("text",safe(text));v.put("created_at",System.currentTimeMillis());getWritableDatabase().insert("council_messages",null,v);}
    public void finishCouncil(long session,String synthesis){ContentValues v=new ContentValues();v.put("status","DONE");v.put("synthesis",safe(synthesis));v.put("completed_at",System.currentTimeMillis());getWritableDatabase().update("council_sessions",v,"id=?",new String[]{String.valueOf(session)});}

    public long addMission(String title,String goal,int priority){ContentValues v=new ContentValues();long now=System.currentTimeMillis();v.put("title",safe(title));v.put("goal",safe(goal));v.put("priority",Math.max(1,Math.min(10,priority)));v.put("created_at",now);v.put("updated_at",now);return getWritableDatabase().insert("missions",null,v);}
    public long addMissionStep(long mission,String title,String depends,String evidence){ContentValues v=new ContentValues();long now=System.currentTimeMillis();v.put("mission_id",mission);v.put("title",safe(title));v.put("depends_on",safe(depends));v.put("evidence_needed",safe(evidence));v.put("created_at",now);v.put("updated_at",now);return getWritableDatabase().insert("mission_steps",null,v);}
    public List<String[]> missions(int limit){ArrayList<String[]>o=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,title,goal,status,priority,updated_at FROM missions ORDER BY CASE status WHEN 'ACTIVE' THEN 0 ELSE 1 END,priority DESC,updated_at DESC LIMIT ?",new String[]{String.valueOf(Math.max(1,limit))})){while(c.moveToNext())o.add(row(c,6));}return o;}
    public List<String[]> missionSteps(long id){ArrayList<String[]>o=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,title,status,depends_on,evidence_needed,updated_at FROM mission_steps WHERE mission_id=? ORDER BY id",new String[]{String.valueOf(id)})){while(c.moveToNext())o.add(row(c,6));}return o;}
    public void setMissionStep(long step,String status){ContentValues v=new ContentValues();v.put("status",safe(status).toUpperCase());v.put("updated_at",System.currentTimeMillis());getWritableDatabase().update("mission_steps",v,"id=?",new String[]{String.valueOf(step)});}

    public long addClaim(String text,int confidence,long sourceId,int part){ContentValues v=new ContentValues();v.put("text",safe(text));v.put("confidence",Math.max(1,Math.min(10,confidence)));v.put("source_id",sourceId);v.put("part_start",part);v.put("part_end",part);v.put("created_at",System.currentTimeMillis());return getWritableDatabase().insert("claims",null,v);}
    public void linkClaims(long a,long b,String relation,int weight){if(a<=0||b<=0||a==b)return;ContentValues v=new ContentValues();v.put("from_claim",a);v.put("to_claim",b);v.put("relation",safe(relation).toUpperCase());v.put("weight",Math.max(1,weight));v.put("created_at",System.currentTimeMillis());getWritableDatabase().insertWithOnConflict("claim_edges",null,v,SQLiteDatabase.CONFLICT_IGNORE);}
    public List<String[]> claims(int limit){ArrayList<String[]>o=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,text,status,confidence,source_id,part_start,created_at FROM claims ORDER BY confidence DESC,created_at DESC LIMIT ?",new String[]{String.valueOf(Math.max(1,limit))})){while(c.moveToNext())o.add(row(c,7));}return o;}
    public void evidence(long memoryId,String origin,long sourceId,int part,int page,String method,int confidence){ContentValues v=new ContentValues();v.put("memory_id",memoryId);v.put("origin_type",safe(origin));v.put("source_id",sourceId);v.put("part",part);v.put("page",page);v.put("method",safe(method));v.put("confidence",Math.max(1,Math.min(10,confidence)));v.put("created_at",System.currentTimeMillis());getWritableDatabase().insertWithOnConflict("evidence_dna",null,v,SQLiteDatabase.CONFLICT_REPLACE);}

    public void indexText(long sourceId,int part,long memoryId,String text){if(text==null||text.trim().isEmpty())return;long h=SemanticHasher.simhash(text);SQLiteDatabase d=getWritableDatabase();ContentValues s=new ContentValues();s.put("source_id",sourceId);s.put("part",part);s.put("memory_id",memoryId);s.put("sem_hash",h);s.put("text_preview",trim(text,500));d.insertWithOnConflict("semantic_index",null,s,SQLiteDatabase.CONFLICT_REPLACE);try{d.delete("knowledge_fts","source_id=? AND part=?",new String[]{String.valueOf(sourceId),String.valueOf(part)});ContentValues f=new ContentValues();f.put("source_id",sourceId);f.put("part",part);f.put("memory_id",memoryId);f.put("text",text);d.insert("knowledge_fts",null,f);}catch(Throwable ignored){}}
    public List<String[]> semanticCandidates(int limit){ArrayList<String[]>o=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT source_id,part,memory_id,sem_hash,text_preview FROM semantic_index ORDER BY source_id DESC,part ASC LIMIT ?",new String[]{String.valueOf(Math.max(1,limit))})){while(c.moveToNext())o.add(row(c,5));}return o;}
    public List<String[]> fts(String query,int limit){ArrayList<String[]>o=new ArrayList<>();String q=SemanticHasher.ftsQuery(query);if(q.isEmpty())return o;try(Cursor c=getReadableDatabase().rawQuery("SELECT source_id,part,memory_id,text FROM knowledge_fts WHERE knowledge_fts MATCH ? LIMIT ?",new String[]{q,String.valueOf(Math.max(1,limit))})){while(c.moveToNext())o.add(row(c,4));}catch(Throwable ignored){}return o;}

    public void blackbox(String subsystem,String event,String detail,String queue){Runtime r=Runtime.getRuntime();long free=(r.maxMemory()-(r.totalMemory()-r.freeMemory()))/(1024*1024);ContentValues v=new ContentValues();v.put("ts",System.currentTimeMillis());v.put("subsystem",safe(subsystem));v.put("event",safe(event));v.put("detail",trim(detail,1800));v.put("heap_free_mb",free);v.put("queue_state",safe(queue));SQLiteDatabase d=getWritableDatabase();d.insert("blackbox",null,v);try{d.execSQL("DELETE FROM blackbox WHERE id NOT IN (SELECT id FROM blackbox ORDER BY ts DESC LIMIT 300)");}catch(Throwable ignored){}}
    public List<String[]> blackbox(int limit){ArrayList<String[]>o=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT ts,subsystem,event,detail,heap_free_mb,queue_state FROM blackbox ORDER BY ts DESC LIMIT ?",new String[]{String.valueOf(Math.max(1,limit))})){while(c.moveToNext())o.add(row(c,6));}return o;}
    public JSONObject stats(){JSONObject o=new JSONObject();try{o.put("residents",count("residents")).put("missions",count("missions")).put("claims",count("claims")).put("evidence_dna",count("evidence_dna")).put("semantic_parts",count("semantic_index"));}catch(Exception ignored){}return o;}
    private int count(String table){try(Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM "+table,null)){return c.moveToFirst()?c.getInt(0):0;}}
    private static String[] row(Cursor c,int n){String[] r=new String[n];for(int i=0;i<n;i++)r[i]=c.isNull(i)?"":c.getString(i);return r;}
    private static String safe(String s){return s==null?"":s.trim();} private static String trim(String s,int n){s=safe(s);return s.length()<=n?s:s.substring(0,n-1)+"…";}
}
