package com.hanma.echocore;

import java.util.ArrayList;import java.util.LinkedHashMap;import java.util.List;import java.util.Locale;import java.util.Map;

/** Routes work through the resident whose inherited cognition and preloaded corpus best match the task. */
public class AscendantRouter {
    private final HybridRetriever retriever;private final NexusOrchestrator nexus;private final CouncilEngine council;private final ClaimGraphEngine claims;private final MissionEngine missions;
    public AscendantRouter(HybridRetriever r,NexusOrchestrator n,CouncilEngine c,ClaimGraphEngine g,MissionEngine m){retriever=r;nexus=n;council=c;claims=g;missions=m;}
    public String route(String q){String s=q==null?"":q.trim();if(s.isEmpty())return "Give Ascendant a question, mission, decision, or idea.";String l=s.toLowerCase(Locale.US);
        if(l.startsWith("council ")||l.contains("ask the council")||l.contains("all of you"))return council.convene(s.replaceFirst("(?i)^council\\s+",""),30);
        if(l.startsWith("mission ")){String goal=s.substring(8).trim();long id=missions.create(trim(goal,64),goal,8);return "ZORDON · MISSION "+id+" CREATED\n\n"+missions.brief(id)+"\n\n"+council.speak("zordon",goal);}
        if(l.contains("who are you")||l.contains("your backstory")||l.contains("your origin")||l.contains("remember who")||l.contains("akashic")||l.contains("civilization"))return council.speak("omega",s);
        if(l.contains("lain")||l.contains("wired")||l.contains("network identity")||l.contains("distributed identity")||l.contains("digital self")||l.contains("cyber identity")||l.contains("replicated state"))return council.speak("lain",s)+"\n\nOMEGA CROSS-LINK\n"+trim(council.speak("omega",s),2200);
        if(l.contains("leary")||l.contains("eight circuit")||l.contains("8 circuit")||l.contains("metaprogram")||l.contains("cyberculture")||l.contains("consciousness model")||l.contains("set and setting"))return council.speak("leary",s)+"\n\nOMEGA CROSS-LINK\n"+trim(council.speak("omega",s),2200);
        if(l.contains("contradiction")||l.contains("conflict between"))return council.speak("rival1",s)+"\n\nCLAIM GRAPH\n"+claims.contradictionReport();
        if(l.startsWith("find ")||l.startsWith("search ")||l.startsWith("exact "))return lookup(s);
        if(l.contains("hermes")||l.contains("hermetic")||l.contains("alchemy")||l.contains("kybalion")||l.contains("kabbalah")||l.contains("egypt")||l.contains("ancient text")||l.contains("research")||l.contains("evidence")||l.contains("source")||l.contains("compare")||l.contains("history")||l.contains("symbol"))return council.speak("hermes",s)+"\n\n"+multiHop(s);
        if(l.contains("plan")||l.contains("mission")||l.contains("goal")||l.contains("roadmap"))return council.speak("zordon",s);
        if(l.contains("apk")||l.contains("android")||l.contains("code")||l.contains("software")||l.contains("build")||l.contains("create")||l.contains("prototype")||l.contains("engineer"))return council.speak("rival3",s)+"\n\nOMEGA CROSS-CHECK\n"+trim(council.speak("omega",s),2200);
        if(l.contains("tesla")||l.contains("coil")||l.contains("circuit")||l.contains("voltage")||l.contains("resonance")||l.contains("field")||l.contains("frequency")||l.contains("energy")||l.contains("electrical")||l.contains("wireless power"))return council.speak("tesla",s);
        if(l.contains("critic")||l.contains("wrong")||l.contains("weakness")||l.contains("fals")||l.contains("artifact")||l.contains("confound"))return council.speak("rival1",s)+"\n\nCLAIM GRAPH\n"+claims.contradictionReport();
        if(l.contains("idea")||l.contains("creative")||l.contains("alternate")||l.contains("unconventional")||l.contains("fiction")||l.contains("myth")||l.contains("strange"))return council.speak("rival2",s);
        if(l.contains("alien")||l.contains("ufo")||l.contains("uap")||l.contains("contact")||l.contains("unknown signal")||l.contains("xeno")||l.contains("extraterrestrial"))return council.speak("star-council",s)+"\n\nOMEGA CROSS-CHECK\n"+trim(council.speak("omega",s),2200);
        return council.speak("omega",s);
    }
    private String lookup(String q){List<HybridRetriever.Hit> hits=retriever.search(q,12);if(hits.isEmpty())return council.speak("hermes",q)+"\n\nLOCAL USER LOOKUP\nNo matching user-imported source or ordinary memory was found. The preloaded Civilization Vault was still searched by Hermes above.";StringBuilder b=new StringBuilder("HERMES USER-SOURCE LOOKUP\n\n");int i=1;for(HybridRetriever.Hit h:hits)b.append('[').append(i++).append("] ").append(h.label()).append("\n").append(trim(h.text,700)).append("\n\n");return council.speak("hermes",q)+"\n\n"+b.toString().trim();}
    private String multiHop(String q){LinkedHashMap<String,HybridRetriever.Hit> all=new LinkedHashMap<>();List<HybridRetriever.Hit> first=retriever.search(q,12);add(all,first);ArrayList<String> seeds=new ArrayList<>();for(HybridRetriever.Hit h:first){for(String t:SemanticHasher.tokens(h.text)){if(t.length()>=5&&!q.toLowerCase(Locale.US).contains(t)&&!seeds.contains(t))seeds.add(t);if(seeds.size()>=4)break;}if(seeds.size()>=4)break;}for(String seed:seeds)add(all,retriever.search(q+" "+seed,6));StringBuilder b=new StringBuilder("ASCENDANT LIVE-SOURCE MULTI-HOP\nQuestion: ").append(q).append("\nPasses: initial");for(String x:seeds)b.append(" → ").append(x);b.append("\n\n");int i=1;for(HybridRetriever.Hit h:all.values()){b.append('[').append(i++).append("] ").append(h.label()).append("\n").append(trim(h.text,650)).append("\n\n");if(i>14)break;}if(all.isEmpty())b.append("No user-imported evidence hit this query. Hermes still has the bundled Civilization Vault and root archive above.\n");return b.toString();}
    private static void add(Map<String,HybridRetriever.Hit> map,List<HybridRetriever.Hit> list){for(HybridRetriever.Hit h:list){String k=h.sourceId+":"+h.part+":"+h.memoryId;if(!map.containsKey(k))map.put(k,h);}}
    private static String trim(String s,int n){s=s==null?"":s.trim();return s.length()<=n?s:s.substring(0,n-1)+"…";}
}
