package com.hanma.echocore;

import android.app.NotificationChannel;import android.app.NotificationManager;import android.app.Service;import android.content.Context;import android.content.Intent;import android.os.Build;import android.os.IBinder;
import org.json.JSONArray;import org.json.JSONObject;
import java.io.BufferedReader;import java.io.InputStream;import java.io.InputStreamReader;import java.io.OutputStream;import java.net.HttpURLConnection;import java.net.URL;import java.nio.charset.StandardCharsets;import java.util.Locale;import java.util.UUID;

public class CloudLinkService extends Service {
 public static final String KEY_ENABLED="autolink_enabled",KEY_REGISTERED="autolink_registered",KEY_DEVICE_ID="autolink_device_id",KEY_FORCE_REGISTER="autolink_force_register";private static final String BASE="https://vdvdijoniwhqorawaufi.supabase.co/functions/v1/echocore-relay";private volatile boolean running;private Thread worker;private BrainDatabase brain;private BrainEngine engine;private SourceCatalog sources;private CognitiveStore store;private CognitiveOrchestrator omega;private SecurePrefs prefs;
 @Override public void onCreate(){super.onCreate();brain=new BrainDatabase(this);engine=new BrainEngine(brain);sources=new SourceCatalog(this);store=new CognitiveStore(this);omega=new CognitiveOrchestrator(brain,engine,sources,store);prefs=new SecurePrefs(this);channel();}
 @Override public int onStartCommand(Intent i,int f,int id){startForeground(18434,new android.app.Notification.Builder(this,Build.VERSION.SDK_INT>=26?"echocore_autolink":null).setContentTitle("EchoCore AutoLink").setContentText("Secure brain relay active").setSmallIcon(android.R.drawable.stat_notify_sync).setOngoing(true).build());if(!running){running=true;worker=new Thread(this::loop,"EchoCoreAutoLink");worker.start();}return START_STICKY;}
 @Override public void onDestroy(){running=false;if(worker!=null)worker.interrupt();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}private void channel(){if(Build.VERSION.SDK_INT>=26)((NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE)).createNotificationChannel(new NotificationChannel("echocore_autolink","EchoCore AutoLink",NotificationManager.IMPORTANCE_LOW));}
 private void loop(){while(running){try{if(prefs.getBool(KEY_ENABLED,true)){ensureRegistered();heartbeat();poll();}Thread.sleep(3500);}catch(InterruptedException e){break;}catch(Exception e){prefs.putBool(KEY_REGISTERED,false);try{Thread.sleep(7000);}catch(Exception x){break;}}}}
 private void ensureRegistered()throws Exception{String id=prefs.get(KEY_DEVICE_ID,"");String secret=prefs.getSecret("autolink_device_secret");boolean force=prefs.getBool(KEY_FORCE_REGISTER,false);if(!id.isEmpty()&&!secret.isEmpty()&&!force){prefs.putBool(KEY_REGISTERED,true);return;}JSONObject r=post("/register",new JSONObject().put("app_version","7.0.0").put("capabilities",caps()),false);if(!r.optBoolean("ok"))throw new Exception(r.optString("error","register failed"));prefs.put(KEY_DEVICE_ID,r.getString("device_id"));prefs.putSecret("autolink_device_secret",r.getString("device_secret"));prefs.putBool(KEY_FORCE_REGISTER,false);prefs.putBool(KEY_REGISTERED,true);}
 private void heartbeat()throws Exception{post("/heartbeat",new JSONObject().put("app_version","7.0.0").put("capabilities",caps()),true);}
 private void poll()throws Exception{JSONObject r=post("/poll",new JSONObject(),true);JSONArray a=r.optJSONArray("commands");if(a==null)return;for(int i=0;i<a.length();i++){JSONObject c=a.optJSONObject(i);if(c==null)continue;String cid=c.optString("id","");JSONObject cmd=c.optJSONObject("command");JSONObject resp=new JSONObject();try{String action=cmd==null?"":cmd.optString("action","");JSONObject payload=cmd==null?new JSONObject():cmd.optJSONObject("payload");if(payload==null)payload=new JSONObject();resp.put("status","ok").put("payload",execute(action,payload));}catch(Exception e){resp.put("status","error").put("payload",new JSONObject().put("message",safe(e)));}post("/respond",new JSONObject().put("command_id",cid).put("response",resp),true);}}
 private Object execute(String action,JSONObject p)throws Exception{switch(action){case"brain_answer":{String q=p.optString("question",p.optString("q","")),m=p.optString("mode","DEEP").toUpperCase(Locale.US),a=omega.localAnswer(q,m);store.addTurn("REMOTE",q,m);store.addTurn("OMEGA",a,m);return new JSONObject().put("answer",a).put("mode",m);}case"brain_search":{JSONArray a=new JSONArray();for(MemoryNode x:brain.search(p.optString("q",""),Math.max(1,Math.min(50,p.optInt("limit",8)))))a.put(new JSONObject().put("id",x.id).put("text",x.text).put("type",x.type).put("tags",x.tags).put("importance",x.importance));return a;}case"memory_add":{String t=p.optString("text","").trim();if(t.isEmpty())throw new Exception("Missing text");long id=brain.addMemoryRich(t,p.optString("type","THOUGHT"),p.optString("tags",engine.autoTags(t)),p.optInt("importance",engine.inferImportance(t)),p.optInt("valence",engine.inferValence(t)),p.optInt("confidence",7),p.optInt("novelty",engine.inferNovelty(t)),p.optBoolean("active",false));return new JSONObject().put("memory_id",id);}case"source_import_text":return importText(p.optString("name","Remote source"),p.optString("text",""));case"source_search":{JSONArray a=new JSONArray();for(String[] r:sources.searchChunks(p.optString("q",""),Math.max(1,Math.min(50,p.optInt("limit",8)))))a.put(new JSONObject().put("source",r[0]).put("part",r[1]).put("text",r[2]));return a;}case"projects_list":{JSONArray a=new JSONArray();for(String[] pr:store.projects()){long id=Long.parseLong(pr[0]);JSONObject o=new JSONObject().put("id",id).put("title",pr[1]).put("goal",pr[2]).put("status",pr[3]);JSONArray ts=new JSONArray();for(String[] t:store.tasks(id))ts.put(new JSONObject().put("id",t[0]).put("text",t[1]).put("status",t[2]).put("priority",t[3]));o.put("tasks",ts);a.put(o);}return a;}case"project_add":{String title=p.optString("title","").trim();if(title.isEmpty())throw new Exception("Missing title");String goal=p.optString("goal","");long id=store.addProject(title,goal);int pr=8;for(String s:omega.planSteps(goal.isEmpty()?title:goal))store.addTask(id,s,pr--);return new JSONObject().put("project_id",id);}case"task_add":return new JSONObject().put("task_id",store.addTask(p.optLong("project_id",0),p.optString("text",""),p.optInt("priority",5)));case"consolidate":return new JSONObject().put("result",p.optBoolean("full_autopilot",false)?omega.autopilotCycle():engine.consolidate());case"capabilities":return caps();default:throw new Exception("Unknown action: "+action);}}
 private JSONObject post(String path,JSONObject body,boolean auth)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(BASE+path).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(15000);c.setReadTimeout(25000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");if(auth){c.setRequestProperty("X-Device-Id",prefs.get(KEY_DEVICE_ID,""));c.setRequestProperty("X-Device-Secret",prefs.getSecret("autolink_device_secret"));}try(OutputStream o=c.getOutputStream()){o.write(body.toString().getBytes(StandardCharsets.UTF_8));}InputStream in=c.getResponseCode()<400?c.getInputStream():c.getErrorStream();BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String line;while((line=r.readLine())!=null)b.append(line);return new JSONObject(b.toString());}
 private JSONObject importText(String name,String text)throws Exception{if(text==null||text.trim().isEmpty())throw new Exception("Missing source text");long sid=sources.startSource(name,"text/plain","autolink://"+UUID.randomUUID(),text.length());long parent=brain.addMemoryRich("SOURCE: "+name+"\nORIGIN: AutoLink","SOURCE","source, autolink, "+engine.autoTags(name),8,0,8,5,false);int part=1,chars=0;for(String piece:chunk(text,1200)){sources.addChunk(sid,part,piece);brain.addMemoryRich("SOURCE "+name+" · part "+part+"\n"+piece,"REFERENCE","document, autolink, part:"+part,7,0,8,4,false);chars+=piece.length();part++;}sources.finishSource(sid,chars,part-1,parent);return new JSONObject().put("source_id",sid).put("chunks",part-1).put("chars",chars);}
 private static java.util.List<String> chunk(String text,int target){java.util.ArrayList<String> o=new java.util.ArrayList<>();String s=text.replace("\r\n","\n").trim();int i=0;while(i<s.length()){int e=Math.min(s.length(),i+target);if(e<s.length()){int x=s.lastIndexOf(' ',e);if(x>i+target/2)e=x;}String q=s.substring(i,e).trim();if(!q.isEmpty())o.add(q);i=Math.max(e,i+1);}return o;}private JSONArray caps(){return new JSONArray(new String[]{"brain_answer","brain_search","memory_add","source_import_text","source_search","projects_list","project_add","task_add","consolidate","capabilities"});}private static String safe(Exception e){return e.getMessage()==null?e.toString():e.getMessage();}
}
