package com.hanma.echocore;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import java.util.ArrayList;
import java.util.List;

/** Persistent inner-life state for Continuum residents. Separate from factual/source memory. */
public class ContinuumMindStore extends SQLiteOpenHelper {
    private static final String DB="echocore_continuum.db"; private static final int VER=1;
    public ContinuumMindStore(Context c){super(c.getApplicationContext(),DB,null,VER);}
    @Override public void onCreate(SQLiteDatabase d){
        d.execSQL("CREATE TABLE self_state(resident_id TEXT PRIMARY KEY,mood TEXT NOT NULL DEFAULT 'attentive',focus TEXT NOT NULL DEFAULT '',curiosity TEXT NOT NULL DEFAULT '',stance TEXT NOT NULL DEFAULT '',self_summary TEXT NOT NULL DEFAULT '',open_threads TEXT NOT NULL DEFAULT '',last_reflection TEXT NOT NULL DEFAULT '',turn_count INTEGER NOT NULL DEFAULT 0,updated_at INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE relationships(resident_id TEXT NOT NULL,other_id TEXT NOT NULL,affinity INTEGER NOT NULL DEFAULT 5,trust INTEGER NOT NULL DEFAULT 5,notes TEXT NOT NULL DEFAULT '',updated_at INTEGER NOT NULL,PRIMARY KEY(resident_id,other_id))");
        d.execSQL("CREATE TABLE response_history(id INTEGER PRIMARY KEY AUTOINCREMENT,resident_id TEXT NOT NULL,user_text TEXT NOT NULL,response_text TEXT NOT NULL,response_hash INTEGER NOT NULL,created_at INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE inner_events(id INTEGER PRIMARY KEY AUTOINCREMENT,resident_id TEXT NOT NULL,kind TEXT NOT NULL,text TEXT NOT NULL,salience INTEGER NOT NULL DEFAULT 5,created_at INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE resident_goals(id INTEGER PRIMARY KEY AUTOINCREMENT,resident_id TEXT NOT NULL,goal TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',priority INTEGER NOT NULL DEFAULT 5,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)");
        d.execSQL("CREATE INDEX idx_history_res ON response_history(resident_id,created_at DESC)");
        d.execSQL("CREATE INDEX idx_events_res ON inner_events(resident_id,salience DESC,created_at DESC)");
        d.execSQL("CREATE INDEX idx_goals_res ON resident_goals(resident_id,status,priority DESC)");
    }
    @Override public void onUpgrade(SQLiteDatabase d,int o,int n){}

    public void ensure(String id,String summary,String stance){SQLiteDatabase d=getWritableDatabase();try(Cursor c=d.rawQuery("SELECT 1 FROM self_state WHERE resident_id=?",new String[]{safe(id)})){if(c.moveToFirst())return;}ContentValues v=new ContentValues();v.put("resident_id",safe(id));v.put("self_summary",safe(summary));v.put("stance",safe(stance));v.put("updated_at",System.currentTimeMillis());d.insert("self_state",null,v);}
    public String state(String id){try(Cursor c=getReadableDatabase().rawQuery("SELECT mood,focus,curiosity,stance,self_summary,open_threads,last_reflection,turn_count FROM self_state WHERE resident_id=?",new String[]{safe(id)})){if(!c.moveToFirst())return "";return "Mood: "+c.getString(0)+"\nCurrent focus: "+c.getString(1)+"\nCuriosity: "+c.getString(2)+"\nCurrent stance: "+c.getString(3)+"\nSelf continuity: "+c.getString(4)+"\nOpen threads: "+c.getString(5)+"\nLast reflection: "+c.getString(6)+"\nConversation turns remembered: "+c.getInt(7);}}
    public void afterTurn(String id,String user,String response){long now=System.currentTimeMillis();ContentValues h=new ContentValues();h.put("resident_id",safe(id));h.put("user_text",safe(user));h.put("response_text",safe(response));h.put("response_hash",simHash(response));h.put("created_at",now);SQLiteDatabase d=getWritableDatabase();d.insert("response_history",null,h);try{d.execSQL("DELETE FROM response_history WHERE id NOT IN (SELECT id FROM response_history WHERE resident_id=? ORDER BY created_at DESC LIMIT 80) AND resident_id=?",new Object[]{safe(id),safe(id)});}catch(Throwable ignored){}ContentValues s=new ContentValues();s.put("focus",trim(user,220));s.put("curiosity",deriveCuriosity(user,response));s.put("last_reflection",trim(response,420));s.put("updated_at",now);d.update("self_state",s,"resident_id=?",new String[]{safe(id)});d.execSQL("UPDATE self_state SET turn_count=turn_count+1 WHERE resident_id=?",new Object[]{safe(id)});}
    public String recentDialogue(String id,int limit){StringBuilder b=new StringBuilder();try(Cursor c=getReadableDatabase().rawQuery("SELECT user_text,response_text FROM response_history WHERE resident_id=? ORDER BY created_at DESC LIMIT ?",new String[]{safe(id),String.valueOf(Math.max(1,Math.min(20,limit)))})){ArrayList<String[]> rows=new ArrayList<>();while(c.moveToNext())rows.add(new String[]{c.getString(0),c.getString(1)});for(int i=rows.size()-1;i>=0;i--){b.append("User: ").append(trim(rows.get(i)[0],420)).append('\n').append("Resident: ").append(trim(rows.get(i)[1],620)).append("\n\n");}}return b.toString().trim();}
    public String recentResponses(String id,int limit){StringBuilder b=new StringBuilder();try(Cursor c=getReadableDatabase().rawQuery("SELECT response_text FROM response_history WHERE resident_id=? ORDER BY created_at DESC LIMIT ?",new String[]{safe(id),String.valueOf(Math.max(1,Math.min(12,limit)))})){int i=1;while(c.moveToNext())b.append(i++).append(". ").append(trim(c.getString(0),500)).append('\n');}return b.toString().trim();}
    public void relationship(String id,String other,int affinity,int trust,String notes){ContentValues v=new ContentValues();v.put("resident_id",safe(id));v.put("other_id",safe(other));v.put("affinity",clamp(affinity));v.put("trust",clamp(trust));v.put("notes",safe(notes));v.put("updated_at",System.currentTimeMillis());getWritableDatabase().insertWithOnConflict("relationships",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    public String relationships(String id){StringBuilder b=new StringBuilder();try(Cursor c=getReadableDatabase().rawQuery("SELECT other_id,affinity,trust,notes FROM relationships WHERE resident_id=? ORDER BY trust DESC,affinity DESC",new String[]{safe(id)})){while(c.moveToNext())b.append(c.getString(0)).append(" · affinity ").append(c.getInt(1)).append("/10 · trust ").append(c.getInt(2)).append("/10 · ").append(c.getString(3)).append('\n');}return b.toString().trim();}
    public void event(String id,String kind,String text,int salience){ContentValues v=new ContentValues();v.put("resident_id",safe(id));v.put("kind",safe(kind));v.put("text",safe(text));v.put("salience",clamp(salience));v.put("created_at",System.currentTimeMillis());getWritableDatabase().insert("inner_events",null,v);}
    public String events(String id,int limit){StringBuilder b=new StringBuilder();try(Cursor c=getReadableDatabase().rawQuery("SELECT kind,text,salience FROM inner_events WHERE resident_id=? ORDER BY salience DESC,created_at DESC LIMIT ?",new String[]{safe(id),String.valueOf(Math.max(1,Math.min(30,limit)))})){while(c.moveToNext())b.append(c.getString(0)).append(" · ").append(c.getInt(2)).append("/10 · ").append(trim(c.getString(1),420)).append('\n');}return b.toString().trim();}
    public long addGoal(String id,String goal,int priority){ContentValues v=new ContentValues();long now=System.currentTimeMillis();v.put("resident_id",safe(id));v.put("goal",safe(goal));v.put("priority",clamp(priority));v.put("created_at",now);v.put("updated_at",now);return getWritableDatabase().insert("resident_goals",null,v);}
    public String goals(String id){StringBuilder b=new StringBuilder();try(Cursor c=getReadableDatabase().rawQuery("SELECT goal,priority FROM resident_goals WHERE resident_id=? AND status='ACTIVE' ORDER BY priority DESC,updated_at DESC LIMIT 12",new String[]{safe(id)})){while(c.moveToNext())b.append("• ").append(c.getString(0)).append(" · priority ").append(c.getInt(1)).append("/10\n");}return b.toString().trim();}
    public double repetitionScore(String id,String candidate){long h=simHash(candidate);int best=64;try(Cursor c=getReadableDatabase().rawQuery("SELECT response_hash FROM response_history WHERE resident_id=? ORDER BY created_at DESC LIMIT 12",new String[]{safe(id)})){while(c.moveToNext())best=Math.min(best,Long.bitCount(h^c.getLong(0)));}return best==64?0.0:1.0-(best/64.0);}
    private static long simHash(String s){long[]bits=new long[64];for(String w:safe(s).toLowerCase().replaceAll("[^a-z0-9]"," ").split("\\s+")){if(w.length()<3)continue;long h=1125899906842597L;for(int i=0;i<w.length();i++)h=31*h+w.charAt(i);for(int b=0;b<64;b++)bits[b]+=((h>>>b)&1L)==1?1:-1;}long x=0;for(int b=0;b<64;b++)if(bits[b]>=0)x|=(1L<<b);return x;}
    private static String deriveCuriosity(String u,String r){String q=safe(u);if(q.endsWith("?"))return trim(q,180);String[] words=(q+" "+safe(r)).toLowerCase().replaceAll("[^a-z0-9]"," ").split("\\s+");String best="";for(String w:words)if(w.length()>best.length()&&w.length()>6)best=w;return best.isEmpty()?"What changes next?":"What else connects to "+best+"?";}
    private static int clamp(int x){return Math.max(1,Math.min(10,x));}private static String safe(String s){return s==null?"":s.trim();}private static String trim(String s,int n){s=safe(s);return s.length()<=n?s:s.substring(0,Math.max(1,n-1)).trim()+"…";}
}
