package com.hanma.echocore;

import android.app.Activity;import android.graphics.Canvas;import android.graphics.LinearGradient;import android.graphics.Paint;import android.graphics.RadialGradient;import android.graphics.Shader;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.Gravity;import android.view.View;import android.widget.Button;import android.widget.EditText;import android.widget.FrameLayout;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;

/** Immersive council chamber for multi-resident synthesis over the Living Archive. */
public class CouncilChamberActivity extends Activity {
    private static final int TEXT=0xFFF6F7FF,MUTED=0xFF96A2B8,GOLD=0xFFFFD477,TEAL=0xFF64E7D4,VIOLET=0xFFAA8FFF,PANEL=0xD9101725;
    private AscendantStore city;private LinearLayout output;private EditText prompt;private Button convene;private ScrollView scroll;
    @Override protected void onCreate(Bundle b){super.onCreate(b);city=new AscendantStore(this);FoundationalArchive.install(city);setContentView(build());}
    @Override protected void onDestroy(){try{city.close();}catch(Throwable ignored){}super.onDestroy();}
    private View build(){FrameLayout root=new FrameLayout(this);root.addView(new ChamberField(this),new FrameLayout.LayoutParams(-1,-1));LinearLayout all=new LinearLayout(this);all.setOrientation(LinearLayout.VERTICAL);all.setPadding(dp(14),dp(14),dp(14),dp(12));root.addView(all,new FrameLayout.LayoutParams(-1,-1));
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);Button back=button("‹",0x22FFFFFF,TEXT,24);back.setOnClickListener(v->finish());top.addView(back,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);titles.addView(text("COUNCIL CHAMBER",21,TEXT,true));titles.addView(text(city.residents().size()+" RESIDENT MINDS · "+FoundationalArchive.count(city)+" ROOT RECORDS",9,GOLD,true));top.addView(titles,new LinearLayout.LayoutParams(0,-2,1));all.addView(top);
        AscendantCityView orbit=new AscendantCityView(this);orbit.setInteractive(false);orbit.setResidents(city.residents());all.addView(orbit,new LinearLayout.LayoutParams(-1,dp(250)));
        scroll=new ScrollView(this);output=new LinearLayout(this);output.setOrientation(LinearLayout.VERTICAL);output.setPadding(0,dp(6),0,dp(10));scroll.addView(output);TextView intro=text("The Council wakes with its identity and civilization archive already loaded. Current sources and observations are layered on top, not used as a replacement for who each resident is.",11,MUTED,false);intro.setGravity(Gravity.CENTER);output.addView(intro,lp(-1,-2,dp(18),4,dp(18),12));all.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        prompt=new EditText(this);prompt.setTextColor(TEXT);prompt.setHintTextColor(0xFF657189);prompt.setHint("Place a problem before the full archive…");prompt.setTextSize(13);prompt.setMinLines(2);prompt.setMaxLines(5);prompt.setPadding(dp(13),dp(10),dp(13),dp(10));prompt.setBackground(round(PANEL,18));all.addView(prompt,lp(-1,-2,0,0,0,8));convene=button("CONVENE THE CITY",VIOLET,0xFF05070C,11);convene.setOnClickListener(v->runCouncil());all.addView(convene,new LinearLayout.LayoutParams(-1,dp(50)));return root;}
    private void runCouncil(){String q=prompt.getText().toString().trim();if(q.isEmpty())return;prompt.setText("");convene.setEnabled(false);addCard("YOU",q,TEAL);addCard("COUNCIL","Root memories online. Retrieving inherited archive + current evidence…",GOLD);new Thread(()->{BrainDatabase b=null;SourceCatalog s=null;CognitiveStore c=null;AscendantStore a=null;try{b=new BrainDatabase(this);s=new SourceCatalog(this);c=new CognitiveStore(this);a=new AscendantStore(this);FoundationalArchive.install(a);BrainEngine e=new BrainEngine(b);NexusOrchestrator n=new NexusOrchestrator(b,e,s,c);HybridRetriever h=new HybridRetriever(a,s,b);CouncilEngine ce=new CouncilEngine(a,h,n);String out=ce.convene(q,Math.max(8,a.residents().size()));runOnUiThread(()->{addCard("Ω SYNTHESIS",out,VIOLET);convene.setEnabled(true);scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));});}catch(Throwable t){runOnUiThread(()->{addCard("CHAMBER ERROR",t.getClass().getSimpleName()+" · "+String.valueOf(t.getMessage()),0xFFFF7C91);convene.setEnabled(true);});}finally{try{if(a!=null)a.close();}catch(Throwable ignored){}try{if(c!=null)c.close();}catch(Throwable ignored){}try{if(s!=null)s.close();}catch(Throwable ignored){}try{if(b!=null)b.close();}catch(Throwable ignored){}}},"AscendantCouncilChamber").start();}
    private void addCard(String who,String body,int accent){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(10),dp(12),dp(11));GradientDrawable bg=round(PANEL,18);bg.setStroke(dp(1),(accent&0x00FFFFFF)|0x44000000);card.setBackground(bg);card.addView(text(who,9,accent,true));card.addView(text(body,12,TEXT,false),lp(-1,-2,0,5,0,0));output.addView(card,lp(-1,-2,0,4,0,5));}
    private Button button(String s,int bg,int fg,float z){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(fg);b.setTextSize(z);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(round(bg,14));return b;}private TextView text(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}private GradientDrawable round(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
    private class ChamberField extends View{Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);long t0=System.currentTimeMillis();ChamberField(android.content.Context c){super(c);}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight(),t=(System.currentTimeMillis()-t0)/1000f;p.setShader(new LinearGradient(0,0,w,h,new int[]{0xFF02040A,0xFF090D1B,0xFF160B20,0xFF02050A},null,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);float pulse=1f+(float)Math.sin(t*.65f)*.07f;p.setShader(new RadialGradient(w*.5f,h*.28f,w*.58f*pulse,new int[]{0x337B5CFF,0x223BDAC2,0x00000000},null,Shader.TileMode.CLAMP));c.drawCircle(w*.5f,h*.28f,w*.58f*pulse,p);p.setShader(null);postInvalidateDelayed(33);}}
}
