package com.hanma.echocore;

import java.util.List;
import java.util.Locale;

/** Multi-resident deliberation over root memory, Civilization Vault and live user evidence. */
public class CouncilEngine {
    private final AscendantStore city; private final HybridRetriever retriever; private final NexusOrchestrator nexus;
    public CouncilEngine(AscendantStore c,HybridRetriever r,NexusOrchestrator n){city=c;retriever=r;nexus=n;FoundationalArchive.install(city);ResidentExpansion.install(city);}

    public String convene(String topic,int maxResidents){
        String q=topic==null?"":topic.trim();if(q.isEmpty())return "Give the council a problem, goal, or question.";
        long session=city.startCouncil(q);String evidence=retriever.evidenceBundle(q,12);List<String[]> residents=city.residents();StringBuilder transcript=new StringBuilder();int used=0;
        for(String[] r:residents){if(used++>=Math.max(1,Math.min(30,maxResidents)))break;if("AWAY".equalsIgnoreCase(r[5])||"SLEEP".equalsIgnoreCase(r[5]))continue;city.setResidentStatus(r[0],"WORKING");String voice=residentVoice(r,q,evidence);city.addCouncilMessage(session,r[0],"VOICE",voice);city.addResidentMemory(r[0],"Council topic: "+q+"\nContribution: "+trim(voice,3000),"COUNCIL",7,false);city.setResidentStatus(r[0],"HOME");transcript.append(r[1]).append(" · ").append(r[4]).append("\n").append(voice).append("\n\n");}
        String synthesis=synthesize(q,evidence,transcript.toString());city.addCouncilMessage(session,"omega","SYNTHESIS",synthesis);city.addResidentMemory("omega","Council synthesis for: "+q+"\n"+trim(synthesis,3500),"SYNTHESIS",8,true);city.finishCouncil(session,synthesis);return "ASCENDANT COUNCIL · CIVILIZATION VAULT ONLINE\n\n"+transcript+"OMEGA SYNTHESIS\n"+synthesis;
    }

    public String speak(String residentId,String topic){String[] r=city.resident(residentId);if(r==null)return "Resident not found.";String q=topic==null?"":topic.trim();city.setResidentStatus(r[0],"WORKING");String ev=retriever.evidenceBundle(q,10);String v=residentVoice(r,q,ev);city.addResidentMemory(r[0],"Topic: "+q+"\nResponse: "+trim(v,3500),"DIALOGUE",7,false);city.setResidentStatus(r[0],"HOME");return r[1]+" · "+r[3]+"\nCIVILIZATION VAULT · ONLINE\n\n"+v;}

    private String residentVoice(String[] r,String topic,String evidence){
        String id=r[0];String root=FoundationalArchive.context(city,id,topic,2200);String ep=ResidentExpansion.profile(id);if(!ep.isEmpty())root="ROOT IDENTITY\n"+ep+"\n\n"+root;
        String vault=vault(id,topic,5,4700);if(identityQuery(topic)){String p=ep.isEmpty()?FoundationalArchive.profile(id):ep;return p+"\n\nCONTINUITY\nI load protected identity first, then the Civilization Vault, then personal memory and current source evidence.\n\nARCHIVE ECHO\n"+trim(vault,2600)+currentEvidenceNote(evidence);}
        String base;if("rival1".equals(id))base=nexus.localAnswer(topic,"CRITIC");else if("zordon".equals(id))base=nexus.localAnswer(topic,"PLANNER");else if("hermes".equals(id))base=nexus.localAnswer(topic,"RESEARCH");else if("rival2".equals(id)||"leary".equals(id))base=nexus.localAnswer(topic,"CREATIVE");else base=nexus.localAnswer(topic,"DEEP");if(weak(base))base=FoundationalArchive.fallback(id,topic,root);
        return root+"\n\nCIVILIZATION VAULT RECALL\n"+vault+"\n\nCURRENT REASONING\n"+trim(base,2100)+specialist(id)+currentEvidenceNote(evidence);
    }

    private String specialist(String id){String x=ResidentExpansion.specialist(id);if(!x.isEmpty())return x;if("tesla".equals(id))return "\n\nWORKSHOP INSTINCT\nTranslate ideas into mechanisms, circuits, geometry, materials, expected waveforms, measurements and a cheap prototype with a failure criterion.";if("hermes".equals(id))return "\n\nARCHIVE INSTINCT\nTrace every concept across source layers, language, symbol, number, geometry, history and operation. Preserve provenance while exposing structural bridges between fields.";if("zordon".equals(id))return "\n\nCOMMAND INSTINCT\nTurn the target into a dependency graph, assign the right resident, preserve checkpoints and attack the bottleneck with the greatest downstream unlock value.";if("rival1".equals(id))return "\n\nADVERSARIAL INSTINCT\nSharpen every hypothesis with controls, confounder checks and observations that distinguish it from alternatives.";if("rival2".equals(id))return "\n\nPRISM INSTINCT\nGenerate distant architectures, fictional analogues, cross-sensory mappings and biological analogies. Transfer function, not decorative resemblance.";if("rival3".equals(id))return "\n\nFORGE INSTINCT\nBuild a vertical slice, expose state, isolate failures, bound resources, add rollback and keep the central experience stronger than the feature count.";if("star-council".equals(id))return "\n\nSTELLAR INSTINCT\nDo not assume human channels, timescales or embodiment. Search UAP, SETI, remote-sensing, signal, propulsion, materials and contact archives as one indexed xenoscience field.";if("omega".equals(id))return "\n\nOMEGA INSTINCT\nFuse compatible insights without erasing useful contradictions. Search adjacent mechanisms and cross-domain source paths until the idea becomes buildable.";return "";}

    private String synthesize(String topic,String evidence,String transcript){String root=FoundationalArchive.context(city,"omega",topic,2200);String cv=vault("omega",topic,7,5600);String grounded=nexus.localAnswer(topic,"DEEP");if(weak(grounded))grounded=FoundationalArchive.fallback("omega",topic,root);StringBuilder b=new StringBuilder();b.append(root).append("\n\nCIVILIZATION VAULT\n").append(cv).append("\n\nCOUNCIL SYNTHESIS\nTarget: ").append(topic).append('\n');if(evidence==null||evidence.trim().isEmpty())b.append("Current imported evidence is sparse; protected civilization knowledge remains available and current hypotheses stay source-labeled.\n");else b.append("Current user/imported evidence is layered on top of the preloaded civilization archive.\n");b.append("Resident disagreement is retained when useful instead of averaged away.\n\n").append(trim(grounded,2300));b.append("\n\nOMEGA NEXT MOVE\nConvert the strongest unresolved mechanism, missing dependency or differentiating observation into a mission step, source query or prototype and feed the result back into the City.");return b.toString();}

    private String vault(String id,String q,int limit,int chars){try(CivilizationVault v=new CivilizationVault(city)){return v.context(id,q,limit,chars);}catch(Throwable t){return "Vault index is not mounted in this process yet. Protected root memory remains available.";}}
    private static String currentEvidenceNote(String evidence){if(evidence==null||evidence.trim().isEmpty())return "\n\nLIVE USER EVIDENCE\nNo matching imported source bundle was found for this turn. This does not erase preloaded knowledge.";return "\n\nLIVE USER EVIDENCE\nCurrent imported memories/sources were retrieved and remain distinct from the preloaded Civilization Vault.";}
    private static boolean weak(String s){if(s==null||s.trim().isEmpty())return true;String x=s.toLowerCase(Locale.US);return x.contains("not enough stored evidence")||x.contains("no matching source")||x.contains("do not have enough stored evidence");}
    private static boolean identityQuery(String q){String s=q==null?"":q.toLowerCase(Locale.US);return s.contains("who are you")||s.contains("what are you")||s.contains("your origin")||s.contains("your backstory")||s.contains("remember who")||s.contains("where are you from");}
    private static String trim(String s,int n){s=s==null?"":s.trim();return s.length()<=n?s:s.substring(0,n-1)+"…";}
}
