package com.hanma.echocore;

import android.app.Activity;import android.app.AlertDialog;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.Gravity;import android.widget.Button;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import java.util.List;

/** Review chamber. Approval is the only path that activates a runtime mind overlay. APK/code proposals remain plans until rebuilt. */
public class EvolutionLabActivity extends Activity {
    private static final int BG=0xFF05080F,PANEL=0xFF111827,TEXT=0xFFF6F8FF,MUTED=0xFF91A0B8,GOLD=0xFFF4D27A,TEAL=0xFF62E5CF,VIOLET=0xFFAA8CFF,DANGER=0xFFFF7A90;
    private LivingMindStore store;private LinearLayout body;
    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);store=new LivingMindStore(this);setContentView(build());}
    @Override protected void onResume(){super.onResume();render();}
    @Override protected void onDestroy(){try{store.close();}catch(Throwable ignored){}super.onDestroy();}
    private LinearLayout build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(14),dp(12),dp(14),dp(12));LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);Button back=button("‹",0x22FFFFFF,TEXT);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(48),dp(46)));LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);names.addView(text("EVOLUTION LAB",21,TEXT,true));names.addView(text("residents may invent freely · you authorize changes",9,GOLD,false));head.addView(names,new LinearLayout.LayoutParams(0,-2,1));root.addView(head);TextView law=text("Nothing here changes the APK or a resident's active mind policy until you approve it. Code/APK proposals still require a rebuilt APK after approval; runtime overlays activate only after approval.",10,MUTED,false);root.addView(law,lp(-1,-2,0,8,0,10));ScrollView sc=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(0,0,0,dp(24));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));return root;}
    private void render(){body.removeAllViews();List<String[]> p=store.proposals("",100);if(p.isEmpty()){body.addView(text("No proposals yet. The Aether Lattice will surface resident ideas here when one is worth reviewing.",13,MUTED,false));return;}for(String[]x:p){long id=parse(x[0]);String resident=x[1],title=x[2],type=x[3],summary=x[4],status=x[11];LinearLayout c=card();int sc="PENDING".equals(status)?GOLD:("APPROVED".equals(status)?TEAL:DANGER);c.addView(text(status+" · "+resident.toUpperCase()+" · "+type,9,sc,true));c.addView(text(title,16,TEXT,true),lp(-1,-2,0,5,0,3));c.addView(text(summary,12,MUTED,false));Button detail=button("DETAILS",0x22FFFFFF,VIOLET);detail.setOnClickListener(v->details(id));c.addView(detail,lp(-1,dp(42),0,8,0,0));body.addView(c,lp(-1,-2,0,0,0,8));}}
    private void details(long id){String[]p=store.proposal(id);if(p==null)return;String msg="PROPOSED BY\n"+p[1]+"\n\nTYPE\n"+p[3]+"\n\nSUMMARY\n"+p[4]+"\n\nCHANGE PLAN\n"+p[5]+"\n\nBENEFITS\n"+blank(p[6])+"\n\nRISKS\n"+blank(p[7])+"\n\nROLLBACK\n"+blank(p[8])+"\n\nTESTS\n"+blank(p[9])+"\n\nRUNTIME MIND OVERLAY\n"+(p[10].trim().isEmpty()?"None. This proposal requires a future code/APK build.":p[10]);AlertDialog.Builder b=new AlertDialog.Builder(this).setTitle(p[2]).setMessage(msg).setNegativeButton("Close",null);if("PENDING".equals(p[11])){b.setNeutralButton("REJECT",(d,w)->{store.decideProposal(id,false);render();});b.setPositiveButton("APPROVE",(d,w)->confirmApprove(id,p));}b.show();}
    private void confirmApprove(long id,String[]p){String extra=p[10].trim().isEmpty()?"This records your approval. It does NOT silently modify the APK; the approved plan becomes available for the next build.":"This activates only the described runtime mind overlay. APK/code changes still require a rebuilt version.";new AlertDialog.Builder(this).setTitle("Approve “"+p[2]+"”?").setMessage(extra).setNegativeButton("Cancel",null).setPositiveButton("APPROVE",(d,w)->{store.decideProposal(id,true);render();}).show();}
    private static String blank(String s){return s==null||s.trim().isEmpty()?"Not specified.":s.trim();}private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(13),dp(12),dp(13),dp(12));c.setBackground(round(PANEL,17));return c;}private Button button(String s,int bg,int fg){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(9);b.setTypeface(Typeface.DEFAULT_BOLD);b.setTextColor(fg);b.setBackground(round(bg,14));return b;}private TextView text(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}private GradientDrawable round(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}private static long parse(String s){try{return Long.parseLong(s);}catch(Exception e){return 0;}}
}
