package com.hanma.echocore;

import android.app.Activity;import android.content.ClipData;import android.content.ClipboardManager;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.text.InputType;import android.view.Gravity;import android.widget.Button;import android.widget.CheckBox;import android.widget.EditText;import android.widget.LinearLayout;import android.widget.TextView;import android.widget.Toast;

/** Secure doorway for the GPT-5.6 Sol resident cognition layer. */
public class FrontierMindActivity extends Activity {
    private static final int BG=0xFF05080F,TEXT=0xFFF6F8FF,MUTED=0xFF93A1B8,TEAL=0xFF63E8D1,GOLD=0xFFF4D27A,VIOLET=0xFFAA8CFF;
    private SecurePrefs prefs;private EditText key;private TextView status;private CheckBox web;
    @Override protected void onCreate(Bundle b){super.onCreate(b);prefs=new SecurePrefs(this);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);setContentView(build());refresh();}
    private LinearLayout build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(18),dp(22),dp(18),dp(22));TextView title=text("FRONTIER MIND",26,TEXT,true);title.setGravity(Gravity.CENTER);root.addView(title);TextView sub=text("GPT-5.6 Sol · high reasoning · cloud continuity",10,TEAL,true);sub.setGravity(Gravity.CENTER);root.addView(sub,lp(-1,-2,0,3,0,18));status=text("CHECKING…",12,GOLD,true);status.setGravity(Gravity.CENTER);status.setBackground(round(0xFF101827,18));status.setPadding(dp(12),dp(12),dp(12),dp(12));root.addView(status,lp(-1,-2,0,0,0,18));TextView explain=text("Frontier is the primary reasoning brain for every resident. Their own identity, memories, relationships, Resonance state and relevant knowledge are assembled in the cloud, then GPT-5.6 Sol reasons over them. Your API key remains encrypted with Android Keystore and is sent only over HTTPS for the live inference request. If Frontier is unavailable, residents automatically fall back to their specialist cloud models.",12,MUTED,false);root.addView(explain,lp(-1,-2,0,0,0,18));key=new EditText(this);key.setHint("OpenAI API key");key.setHintTextColor(0xFF69758A);key.setTextColor(TEXT);key.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);key.setPadding(dp(13),dp(12),dp(13),dp(12));key.setBackground(round(0xFF101827,16));if(valid(prefs.getSecret("api_key")))key.setHint("Key secured · paste only to replace");root.addView(key,new LinearLayout.LayoutParams(-1,dp(54)));LinearLayout row=new LinearLayout(this);Button paste=button("PASTE",0x22FFFFFF,TEAL);paste.setOnClickListener(v->paste());Button save=button("SECURE + TEST",VIOLET,0xFF05070C);save.setOnClickListener(v->save());row.addView(paste,new LinearLayout.LayoutParams(0,dp(50),.38f));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,dp(50),.62f);sp.setMargins(dp(8),0,0,0);row.addView(save,sp);root.addView(row,lp(-1,-2,0,10,0,6));web=new CheckBox(this);web.setText("Let Frontier search the live web when the question needs current information");web.setTextColor(TEXT);web.setChecked(prefs.getBool("web_search",true));root.addView(web);TextView fixed=text("Primary  GPT-5.6 Sol\nReasoning  high\nPersistent memory  Supabase civilization cloud\nKnowledge  silent retrieval\nFallback  resident-specific 24B–128B cloud models\nKey storage  Android Keystore only",11,MUTED,false);fixed.setBackground(round(0xAA0E1522,16));fixed.setPadding(dp(12),dp(12),dp(12),dp(12));root.addView(fixed,lp(-1,-2,0,12,0,8));Button backup=button("SPECIALIST CLOUD ONLY",0x22FFFFFF,GOLD);backup.setOnClickListener(v->{prefs.remove("api_key");prefs.putBool("model_enabled",false);refresh();});root.addView(backup,new LinearLayout.LayoutParams(-1,dp(48)));return root;}
    private void paste(){try{ClipboardManager cm=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(cm!=null&&cm.hasPrimaryClip()){ClipData c=cm.getPrimaryClip();if(c!=null&&c.getItemCount()>0){CharSequence x=c.getItemAt(0).coerceToText(this);if(x!=null)key.setText(x.toString().trim());}}}catch(Throwable t){toast("Clipboard unavailable");}}
    private void save(){String k=key.getText().toString().trim();if(!k.isEmpty()){if(!valid(k)){toast("That doesn't look like an OpenAI API key");return;}prefs.putSecret("api_key",k);}if(!valid(prefs.getSecret("api_key"))){toast("Paste the key first");return;}prefs.put("endpoint","https://api.openai.com/v1/responses");prefs.put("model","gpt-5.6-sol");prefs.put("reasoning_effort","high");prefs.putBool("web_search",web.isChecked());prefs.putBool("model_enabled",true);key.setText("");status.setText("TESTING FRONTIER…");status.setTextColor(GOLD);refresh();}
    private void refresh(){if(status==null)return;new Thread(()->{try{CloudMindClient c=new CloudMindClient(this);org.json.JSONObject s=c.status();boolean frontier=s.optBoolean("frontier",false)||"OpenAI Responses".equalsIgnoreCase(s.optString("provider",""));int backups=s.optInt("available_models",0);runOnUiThread(()->{status.setText(frontier?"FRONTIER ONLINE · GPT-5.6 SOL · "+backups+" BACKUPS":"SPECIALIST CLOUD ONLINE · FRONTIER KEY NOT ACTIVE");status.setTextColor(frontier?VIOLET:TEAL);});}catch(Throwable t){runOnUiThread(()->{boolean has=valid(prefs.getSecret("api_key"));status.setText(has?"KEY SECURED · CLOUD TEST WAITING":"FRONTIER KEY NEEDED");status.setTextColor(GOLD);});}},"FrontierStatus").start();}
    private static boolean valid(String k){return k!=null&&k.startsWith("sk-")&&k.length()>24;}
    private TextView text(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}private Button button(String s,int bg,int fg){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(fg);b.setTextSize(10);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(round(bg,15));return b;}private GradientDrawable round(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
