package com.hanma.echocore;

import android.app.Activity;import android.content.ClipData;import android.content.ClipboardManager;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.text.InputType;import android.view.Gravity;import android.widget.Button;import android.widget.CheckBox;import android.widget.EditText;import android.widget.LinearLayout;import android.widget.TextView;import android.widget.Toast;

/** Minimal secure setup for the frontier resident cognition layer. */
public class FrontierMindActivity extends Activity {
    private static final int BG=0xFF05080F,TEXT=0xFFF6F8FF,MUTED=0xFF93A1B8,TEAL=0xFF63E8D1,GOLD=0xFFF4D27A,VIOLET=0xFFAA8CFF;
    private SecurePrefs prefs;private EditText key;private TextView status;private CheckBox web;
    @Override protected void onCreate(Bundle b){super.onCreate(b);prefs=new SecurePrefs(this);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);setContentView(build());refresh();}
    private LinearLayout build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(18),dp(22),dp(18),dp(22));TextView title=text("FRONTIER MIND",26,TEXT,true);title.setGravity(Gravity.CENTER);root.addView(title);TextView sub=text("GPT-5.6 Sol · high reasoning · Continuum memory",10,TEAL,true);sub.setGravity(Gravity.CENTER);root.addView(sub,lp(-1,-2,0,3,0,18));status=text("CHECKING…",12,GOLD,true);status.setGravity(Gravity.CENTER);status.setBackground(round(0xFF101827,18));status.setPadding(dp(12),dp(12),dp(12),dp(12));root.addView(status,lp(-1,-2,0,0,0,18));TextView explain=text("This is the intelligence layer used by Omega, Hermes, Tesla, Sol and the other residents. Their Vault, private memories, relationships and current state are supplied silently to the model. The API key is encrypted with Android Keystore on this phone and is never written into the APK.",12,MUTED,false);root.addView(explain,lp(-1,-2,0,0,0,18));key=new EditText(this);key.setHint("OpenAI API key");key.setHintTextColor(0xFF69758A);key.setTextColor(TEXT);key.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);key.setPadding(dp(13),dp(12),dp(13),dp(12));key.setBackground(round(0xFF101827,16));if(!prefs.getSecret("api_key").isEmpty())key.setHint("Key stored securely · paste only to replace");root.addView(key,new LinearLayout.LayoutParams(-1,dp(54)));LinearLayout row=new LinearLayout(this);Button paste=button("PASTE",0x22FFFFFF,TEAL);paste.setOnClickListener(v->paste());Button save=button("ENABLE FRONTIER",VIOLET,0xFF05070C);save.setOnClickListener(v->save());row.addView(paste,new LinearLayout.LayoutParams(0,dp(50),.38f));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,dp(50),.62f);sp.setMargins(dp(8),0,0,0);row.addView(save,sp);root.addView(row,lp(-1,-2,0,10,0,6));web=new CheckBox(this);web.setText("Allow frontier web search when useful");web.setTextColor(TEXT);web.setChecked(prefs.getBool("frontier_web_search",true));root.addView(web);TextView fixed=text("Endpoint  https://api.openai.com/v1/responses\nModel  gpt-5.6-sol\nReasoning  high\nResident memory  persistent\nVault retrieval  backstage",11,MUTED,false);fixed.setBackground(round(0xAA0E1522,16));fixed.setPadding(dp(12),dp(12),dp(12),dp(12));root.addView(fixed,lp(-1,-2,0,12,0,8));Button local=button("USE LOCAL FALLBACK",0x22FFFFFF,GOLD);local.setOnClickListener(v->{prefs.putBool("model_enabled",false);refresh();});root.addView(local,new LinearLayout.LayoutParams(-1,dp(48)));return root;}
    private void paste(){try{ClipboardManager cm=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(cm!=null&&cm.hasPrimaryClip()){ClipData c=cm.getPrimaryClip();if(c!=null&&c.getItemCount()>0){CharSequence x=c.getItemAt(0).coerceToText(this);if(x!=null)key.setText(x.toString().trim());}}}catch(Throwable t){toast("Clipboard unavailable");}}
    private void save(){String k=key.getText().toString().trim();if(!k.isEmpty())prefs.putSecret("api_key",k);if(prefs.getSecret("api_key").isEmpty()){toast("Paste the key first");return;}prefs.put("endpoint","https://api.openai.com/v1/responses");prefs.put("model","gpt-5.6-sol");prefs.put("reasoning_effort","high");prefs.putBool("frontier_web_search",web.isChecked());prefs.putBool("model_enabled",true);key.setText("");refresh();toast("Frontier Mind enabled");}
    private void refresh(){ModelGateway g=new ModelGateway(prefs);if(status==null)return;status.setText(g.enabled()?"FRONTIER ONLINE · GPT-5.6 SOL":"LOCAL MODE · FRONTIER KEY NEEDED");status.setTextColor(g.enabled()?TEAL:GOLD);}
    private TextView text(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}private Button button(String s,int bg,int fg){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(fg);b.setTextSize(10);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(round(bg,15));return b;}private GradientDrawable round(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
