package com.hanma.echocore;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import java.util.ArrayList;
import java.util.List;

/**
 * Durable life-layer for Continuum residents. This is deliberately separate from factual
 * source memory: a resident may remember an experience, hold a private reflection, send a
 * message, or propose a change without corrupting the evidence store.
 */
public class LivingMindStore extends SQLiteOpenHelper {
    private static final String DB="echocore_living_minds.db"; private static final int VER=1;
    public LivingMindStore(Context c){super(c.getApplicationContext(),DB,null,VER);}
    @Override public void onCreate(SQLiteDatabase d){
        d.execSQL("CREATE TABLE episodic_memory(memory_key TEXT PRIMARY KEY,resident_id TEXT NOT NULL,era TEXT NOT NULL DEFAULT '',place TEXT NOT NULL DEFAULT '',memory_type TEXT NOT NULL DEFAULT 'EPISODE',narrative TEXT NOT NULL,source_basis TEXT NOT NULL DEFAULT '',canon_layer TEXT NOT NULL DEFAULT 'RECONSTRUCTION',confidence INTEGER NOT NULL DEFAULT 7,salience INTEGER NOT NULL DEFAULT 7,emotional_tone TEXT NOT NULL DEFAULT '',sensory TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL)");
        d.execSQL("CREATE INDEX idx_episode_res ON episodic_memory(resident_id,salience DESC,created_at DESC)");
        d.execSQL("CREATE TABLE thought_journal(id INTEGER PRIMARY KEY AUTOINCREMENT,resident_id TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'REFLECTION',text TEXT NOT NULL,salience INTEGER NOT NULL DEFAULT 5,created_at INTEGER NOT NULL)");
        d.execSQL("CREATE INDEX idx_journal_res ON thought_journal(resident_id,salience DESC,created_at DESC)");
        d.execSQL("CREATE TABLE resident_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,resident_id TEXT NOT NULL,sender_name TEXT NOT NULL,body TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'THOUGHT',priority INTEGER NOT NULL DEFAULT 5,delivered INTEGER NOT NULL DEFAULT 0,read_state INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL)");
        d.execSQL("CREATE INDEX idx_msg_read ON resident_messages(read_state,priority DESC,created_at DESC)");
        d.execSQL("CREATE TABLE evolution_proposals(id INTEGER PRIMARY KEY AUTOINCREMENT,resident_id TEXT NOT NULL,title TEXT NOT NULL,change_type TEXT NOT NULL DEFAULT 'APK',summary TEXT NOT NULL,change_plan TEXT NOT NULL,benefits TEXT NOT NULL DEFAULT '',risks TEXT NOT NULL DEFAULT '',rollback TEXT NOT NULL DEFAULT '',tests TEXT NOT NULL DEFAULT '',runtime_overlay TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'PENDING',created_at INTEGER NOT NULL,reviewed_at INTEGER NOT NULL DEFAULT 0,applied_at INTEGER NOT NULL DEFAULT 0)");
        d.execSQL("CREATE INDEX idx_proposal_status ON evolution_proposals(status,created_at DESC)");
        d.execSQL("CREATE TABLE approved_overlays(resident_id TEXT PRIMARY KEY,text TEXT NOT NULL,proposal_id INTEGER NOT NULL DEFAULT 0,approved_at INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE life_signals(id INTEGER PRIMARY KEY AUTOINCREMENT,kind TEXT NOT NULL,detail TEXT NOT NULL,salience INTEGER NOT NULL DEFAULT 5,consumed INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL)");
        d.execSQL("CREATE INDEX idx_signal_pending ON life_signals(consumed,salience DESC,created_at ASC)");
        d.execSQL("CREATE TABLE aether_state(resident_id TEXT PRIMARY KEY,phase REAL NOT NULL DEFAULT 0,vitality REAL NOT NULL DEFAULT .6,coherence REAL NOT NULL DEFAULT .6,last_pulse INTEGER NOT NULL DEFAULT 0,last_dream INTEGER NOT NULL DEFAULT 0,last_message INTEGER NOT NULL DEFAULT 0,last_proposal INTEGER NOT NULL DEFAULT 0,updated_at INTEGER NOT NULL)");
        d.execSQL("CREATE TABLE civic_ledger(id INTEGER PRIMARY KEY AUTOINCREMENT,ts INTEGER NOT NULL,resident_id TEXT NOT NULL DEFAULT '',event TEXT NOT NULL,detail TEXT NOT NULL DEFAULT '')");
        d.execSQL("CREATE INDEX idx_ledger_ts ON civic_ledger(ts DESC)");
    }
    @Override public void onUpgrade(SQLiteDatabase d,int oldV,int newV){}

    public void seedMemory(String key,String resident,String era,String place,String type,String narrative,String source,String layer,int confidence,int salience,String emotion,String sensory){
        ContentValues v=new ContentValues();v.put("memory_key",safe(key));v.put("resident_id",safe(resident));v.put("era",safe(era));v.put("place",safe(place));v.put("memory_type",safe(type).isEmpty()?"EPISODE":safe(type));v.put("narrative",safe(narrative));v.put("source_basis",safe(source));v.put("canon_layer",safe(layer).isEmpty()?"RECONSTRUCTION":safe(layer));v.put("confidence",clamp(confidence));v.put("salience",clamp(salience));v.put("emotional_tone",safe(emotion));v.put("sensory",safe(sensory));v.put("created_at",System.currentTimeMillis());getWritableDatabase().insertWithOnConflict("episodic_memory",null,v,SQLiteDatabase.CONFLICT_IGNORE);
    }
    public String episodicContext(String resident,int limit){StringBuilder b=new StringBuilder();String id=safe(resident);try(Cursor c=getReadableDatabase().rawQuery("SELECT era,place,memory_type,narrative,source_basis,canon_layer,confidence,salience,emotional_tone,sensory FROM episodic_memory WHERE resident_id=? OR resident_id='*' ORDER BY CASE WHEN resident_id=? THEN 0 ELSE 1 END,salience DESC,created_at ASC LIMIT ?",new String[]{id,id,String.valueOf(Math.max(1,Math.min(40,limit)))})){while(c.moveToNext()){b.append("• ");if(!c.getString(0).isEmpty())b.append(c.getString(0)).append(" · ");if(!c.getString(1).isEmpty())b.append(c.getString(1)).append(" · ");b.append(c.getString(2)).append(" · ").append(c.getString(3));if(!c.getString(8).isEmpty())b.append(" · tone: ").append(c.getString(8));if(!c.getString(9).isEmpty())b.append(" · sensory trace: ").append(c.getString(9));b.append("\n");}}return b.toString().trim();}
    public int memoryCount(String resident){try(Cursor c=getReadableDatabase().rawQuery("SELECT count(*) FROM episodic_memory WHERE resident_id=? OR resident_id='*'",new String[]{safe(resident)})){return c.moveToFirst()?c.getInt(0):0;}}

    public long journal(String resident,String kind,String text,int salience){ContentValues v=new ContentValues();v.put("resident_id",safe(resident));v.put("kind",safe(kind).isEmpty()?"REFLECTION":safe(kind));v.put("text",safe(text));v.put("salience",clamp(salience));v.put("created_at",System.currentTimeMillis());return getWritableDatabase().insert("thought_journal",null,v);}
    public String journalContext(String resident,int limit){StringBuilder b=new StringBuilder();try(Cursor c=getReadableDatabase().rawQuery("SELECT kind,text,salience FROM thought_journal WHERE resident_id=? ORDER BY created_at DESC LIMIT ?",new String[]{safe(resident),String.valueOf(Math.max(1,Math.min(30,limit)))})){while(c.moveToNext())b.append("• ").append(c.getString(0)).append(" · ").append(c.getInt(2)).append("/10 · ").append(trim(c.getString(1),520)).append('\n');}return b.toString().trim();}

    public long addMessage(String resident,String sender,String body,String kind,int priority){ContentValues v=new ContentValues();v.put("resident_id",safe(resident));v.put("sender_name",safe(sender));v.put("body",safe(body));v.put("kind",safe(kind).isEmpty()?"THOUGHT":safe(kind));v.put("priority",clamp(priority));v.put("created_at",System.currentTimeMillis());long id=getWritableDatabase().insert("resident_messages",null,v);ledger(resident,"MESSAGE_CREATED",trim(body,300));return id;}
    public List<String[]> messages(int limit){ArrayList<String[]>o=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,resident_id,sender_name,body,kind,priority,delivered,read_state,created_at FROM resident_messages ORDER BY created_at DESC LIMIT ?",new String[]{String.valueOf(Math.max(1,Math.min(200,limit)))})){while(c.moveToNext())o.add(row(c,9));}return o;}
    public int unread(){try(Cursor c=getReadableDatabase().rawQuery("SELECT count(*) FROM resident_messages WHERE read_state=0",null)){return c.moveToFirst()?c.getInt(0):0;}}
    public void markRead(long id){ContentValues v=new ContentValues();v.put("read_state",1);getWritableDatabase().update("resident_messages",v,"id=?",new String[]{String.valueOf(id)});}
    public void markDelivered(long id){ContentValues v=new ContentValues();v.put("delivered",1);getWritableDatabase().update("resident_messages",v,"id=?",new String[]{String.valueOf(id)});}

    public long addProposal(String resident,String title,String type,String summary,String plan,String benefits,String risks,String rollback,String tests,String runtimeOverlay){ContentValues v=new ContentValues();v.put("resident_id",safe(resident));v.put("title",safe(title));v.put("change_type",safe(type).isEmpty()?"APK":safe(type).toUpperCase());v.put("summary",safe(summary));v.put("change_plan",safe(plan));v.put("benefits",safe(benefits));v.put("risks",safe(risks));v.put("rollback",safe(rollback));v.put("tests",safe(tests));v.put("runtime_overlay",safe(runtimeOverlay));v.put("status","PENDING");v.put("created_at",System.currentTimeMillis());long id=getWritableDatabase().insert("evolution_proposals",null,v);ledger(resident,"PROPOSAL_CREATED",title);return id;}
    public List<String[]> proposals(String status,int limit){ArrayList<String[]>o=new ArrayList<>();String st=safe(status).toUpperCase();String sql=st.isEmpty()?"SELECT id,resident_id,title,change_type,summary,change_plan,benefits,risks,rollback,tests,runtime_overlay,status,created_at,reviewed_at,applied_at FROM evolution_proposals ORDER BY CASE status WHEN 'PENDING' THEN 0 WHEN 'APPROVED' THEN 1 ELSE 2 END,created_at DESC LIMIT ?":"SELECT id,resident_id,title,change_type,summary,change_plan,benefits,risks,rollback,tests,runtime_overlay,status,created_at,reviewed_at,applied_at FROM evolution_proposals WHERE status=? ORDER BY created_at DESC LIMIT ?";String[] args=st.isEmpty()?new String[]{String.valueOf(Math.max(1,Math.min(100,limit)))}:new String[]{st,String.valueOf(Math.max(1,Math.min(100,limit)))};try(Cursor c=getReadableDatabase().rawQuery(sql,args)){while(c.moveToNext())o.add(row(c,15));}return o;}
    public String[] proposal(long id){try(Cursor c=getReadableDatabase().rawQuery("SELECT id,resident_id,title,change_type,summary,change_plan,benefits,risks,rollback,tests,runtime_overlay,status,created_at,reviewed_at,applied_at FROM evolution_proposals WHERE id=?",new String[]{String.valueOf(id)})){return c.moveToFirst()?row(c,15):null;}}
    public int pendingProposals(){try(Cursor c=getReadableDatabase().rawQuery("SELECT count(*) FROM evolution_proposals WHERE status='PENDING'",null)){return c.moveToFirst()?c.getInt(0):0;}}
    public boolean hasPendingFrom(String resident){try(Cursor c=getReadableDatabase().rawQuery("SELECT 1 FROM evolution_proposals WHERE resident_id=? AND status='PENDING' LIMIT 1",new String[]{safe(resident)})){return c.moveToFirst();}}
    public void decideProposal(long id,boolean approve){String[] p=proposal(id);if(p==null)return;String status=approve?"APPROVED":"REJECTED";ContentValues v=new ContentValues();v.put("status",status);v.put("reviewed_at",System.currentTimeMillis());getWritableDatabase().update("evolution_proposals",v,"id=?",new String[]{String.valueOf(id)});if(approve&&!p[10].trim().isEmpty()){ContentValues o=new ContentValues();o.put("resident_id",p[1]);o.put("text",p[10]);o.put("proposal_id",id);o.put("approved_at",System.currentTimeMillis());getWritableDatabase().insertWithOnConflict("approved_overlays",null,o,SQLiteDatabase.CONFLICT_REPLACE);}ledger(p[1],approve?"PROPOSAL_APPROVED":"PROPOSAL_REJECTED",p[2]);}
    public String overlay(String resident){try(Cursor c=getReadableDatabase().rawQuery("SELECT text FROM approved_overlays WHERE resident_id=?",new String[]{safe(resident)})){return c.moveToFirst()?c.getString(0):"";}}

    public long signal(String kind,String detail,int salience){ContentValues v=new ContentValues();v.put("kind",safe(kind));v.put("detail",safe(detail));v.put("salience",clamp(salience));v.put("created_at",System.currentTimeMillis());return getWritableDatabase().insert("life_signals",null,v);}
    public List<String[]> pendingSignals(int limit){ArrayList<String[]>o=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,kind,detail,salience,created_at FROM life_signals WHERE consumed=0 ORDER BY salience DESC,created_at ASC LIMIT ?",new String[]{String.valueOf(Math.max(1,Math.min(50,limit)))})){while(c.moveToNext())o.add(row(c,5));}return o;}
    public void consumeSignal(long id){ContentValues v=new ContentValues();v.put("consumed",1);getWritableDatabase().update("life_signals",v,"id=?",new String[]{String.valueOf(id)});}

    public void ensureAether(String resident){String id=safe(resident);SQLiteDatabase d=getWritableDatabase();try(Cursor c=d.rawQuery("SELECT 1 FROM aether_state WHERE resident_id=?",new String[]{id})){if(c.moveToFirst())return;}ContentValues v=new ContentValues();v.put("resident_id",id);v.put("phase",Math.abs(id.hashCode()%360));v.put("vitality",.62);v.put("coherence",.66);v.put("updated_at",System.currentTimeMillis());d.insert("aether_state",null,v);}
    public String aether(String resident){ensureAether(resident);try(Cursor c=getReadableDatabase().rawQuery("SELECT phase,vitality,coherence,last_pulse,last_dream,last_message,last_proposal FROM aether_state WHERE resident_id=?",new String[]{safe(resident)})){if(!c.moveToFirst())return "";return "phase="+String.format(java.util.Locale.US,"%.1f",c.getDouble(0))+" · vitality="+String.format(java.util.Locale.US,"%.2f",c.getDouble(1))+" · coherence="+String.format(java.util.Locale.US,"%.2f",c.getDouble(2))+" · last_pulse="+c.getLong(3)+" · last_dream="+c.getLong(4)+" · last_message="+c.getLong(5)+" · last_proposal="+c.getLong(6);}}
    public long aetherTime(String resident,String field){ensureAether(resident);String f=("last_dream".equals(field)||"last_message".equals(field)||"last_proposal".equals(field)||"last_pulse".equals(field))?field:"last_pulse";try(Cursor c=getReadableDatabase().rawQuery("SELECT "+f+" FROM aether_state WHERE resident_id=?",new String[]{safe(resident)})){return c.moveToFirst()?c.getLong(0):0;}}
    public void pulseAether(String resident,double vitalityDelta,double coherenceDelta){ensureAether(resident);SQLiteDatabase d=getWritableDatabase();try(Cursor c=d.rawQuery("SELECT phase,vitality,coherence FROM aether_state WHERE resident_id=?",new String[]{safe(resident)})){if(!c.moveToFirst())return;double phase=(c.getDouble(0)+13.7)%360.0,v=Math.max(0,Math.min(1,c.getDouble(1)+vitalityDelta)),co=Math.max(0,Math.min(1,c.getDouble(2)+coherenceDelta));ContentValues x=new ContentValues();x.put("phase",phase);x.put("vitality",v);x.put("coherence",co);x.put("last_pulse",System.currentTimeMillis());x.put("updated_at",System.currentTimeMillis());d.update("aether_state",x,"resident_id=?",new String[]{safe(resident)});}}
    public void stampAether(String resident,String field){ensureAether(resident);if(!"last_dream".equals(field)&&!"last_message".equals(field)&&!"last_proposal".equals(field))return;ContentValues v=new ContentValues();v.put(field,System.currentTimeMillis());v.put("updated_at",System.currentTimeMillis());getWritableDatabase().update("aether_state",v,"resident_id=?",new String[]{safe(resident)});}

    public void ledger(String resident,String event,String detail){ContentValues v=new ContentValues();v.put("ts",System.currentTimeMillis());v.put("resident_id",safe(resident));v.put("event",safe(event));v.put("detail",trim(detail,1200));SQLiteDatabase d=getWritableDatabase();d.insert("civic_ledger",null,v);try{d.execSQL("DELETE FROM civic_ledger WHERE id NOT IN (SELECT id FROM civic_ledger ORDER BY ts DESC LIMIT 1000)");}catch(Throwable ignored){}}
    public List<String[]> ledger(int limit){ArrayList<String[]>o=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT ts,resident_id,event,detail FROM civic_ledger ORDER BY ts DESC LIMIT ?",new String[]{String.valueOf(Math.max(1,Math.min(200,limit)))})){while(c.moveToNext())o.add(row(c,4));}return o;}

    private static String[] row(Cursor c,int n){String[]r=new String[n];for(int i=0;i<n;i++)r[i]=c.isNull(i)?"":c.getString(i);return r;}
    private static int clamp(int x){return Math.max(1,Math.min(10,x));}
    private static String safe(String s){return s==null?"":s.trim();}
    private static String trim(String s,int n){s=safe(s);return s.length()<=n?s:s.substring(0,Math.max(1,n-1)).trim()+"…";}
}
