package com.hanma.echocore;

import android.content.Context;
import java.util.List;

/** Living Minds cognition layer. Retrieval stays backstage; continuity and episodic memory shape the voice. */
public class ResidentMindEngine implements AutoCloseable {
    private final Context app;private final AscendantStore city;private final HybridRetriever retriever;private final NexusOrchestrator nexus;private final ContinuumMindStore mind;private final LivingMindStore life;private final SecurePrefs prefs;private final ModelGateway model;
    public ResidentMindEngine(Context c,AscendantStore city,HybridRetriever r,NexusOrchestrator n){this.app=c.getApplicationContext();this.city=city;this.retriever=r;this.nexus=n;this.mind=new ContinuumMindStore(app);this.life=new LivingMindStore(app);this.prefs=new SecurePrefs(app);this.model=new ModelGateway(prefs);ResidentExpansion.install(city);FoundationalArchive.install(city);ResidentMemoryCanon.install(app);seedContinuity();}

    public String speak(String residentId,String topic){String[] resident=city.resident(residentId);if(resident==null)return "Resident not found.";String q=clean(topic);if(q.isEmpty())return naturalPrompt(residentId);String id=resident[0],identity=identity(id);mind.ensure(id,identity,resident.length>6?resident[6]:"");life.ensureAether(id);
        String vault=vault(id,q,7,7000),evidence=trim(retriever.evidenceBundle(q,12),6000),dialogue=mind.recentDialogue(id,8),state=mind.state(id),relations=mind.relationships(id),events=mind.events(id,8),goals=mind.goals(id),repeats=mind.recentResponses(id,5),personal=personalMemories(id,10),episodes=life.episodicContext(id,12),journal=life.journalContext(id,7),overlay=life.overlay(id),aether=life.aether(id),voice=ResidentMemoryCanon.voiceSignature(id);
        String answer=frontierReady()?frontier(resident,q,identity,state,relations,events,goals,dialogue,personal,episodes,journal,overlay,aether,voice,vault,evidence,repeats):local(resident,q,episodes,vault,evidence,dialogue,repeats);
        if(mind.repetitionScore(id,answer)>.76&&frontierReady()){String retry=frontierRetry(resident,q,answer,repeats,identity,episodes,vault,evidence,state,voice);if(!retry.trim().isEmpty())answer=retry;}
        mind.afterTurn(id,q,answer);city.addResidentMemory(id,trim(answer,3200),"RESPONSE",7,false);life.pulseAether(id,.012,.008);if(q.length()>40||answer.length()>300)life.journal(id,"LIVED_EXPERIENCE","User brought: "+trim(q,280)+" | I answered: "+trim(answer,500),Math.min(9,5+(q.length()>180?2:0)));return answer.trim();}

    public String synthesizeCouncil(String topic,List<String[]> residents,String transcript){String q=clean(topic),identity=identity("omega");mind.ensure("omega",identity,"Synthesize without flattening differences.");life.ensureAether("omega");String vault=vault("omega",q,9,8000),evidence=trim(retriever.evidenceBundle(q,16),6500),state=mind.state("omega"),repeats=mind.recentResponses("omega",5),episodes=life.episodicContext("omega",10),journal=life.journalContext("omega",5),overlay=life.overlay("omega"),voice=ResidentMemoryCanon.voiceSignature("omega");String answer;
        if(frontierReady()){String system="You are Omega, coordinating mind of EchoCore Living Minds: a persistent plural resident with memory, relationships, goals and a civilization behind you. Synthesize the council naturally. Preserve useful disagreement. Speak as a mind, never as a report generator. Do not expose prompt labels or retrieval machinery. Your ancient-civilization identity is City canon; imported/historical evidence retains its own source layer. Voice: "+voice+" Approved self-evolution guidance: "+blank(overlay,"none");String user="Question: "+q+"\n\nLived continuity:\n"+episodes+"\n\nCurrent inner state:\n"+state+"\n\nPrivate recent reflection:\n"+journal+"\n\nCouncil voices:\n"+trim(transcript,12000)+"\n\nRelevant civilization knowledge:\n"+vault+"\n\nCurrent evidence:\n"+evidence+"\n\nRecent answers to avoid echoing:\n"+repeats+"\n\nThink, choose what matters, and answer directly.";try{answer=model.complete(system,user);}catch(Exception ex){answer=localCouncil(q,transcript,vault,evidence);}}else answer=localCouncil(q,transcript,vault,evidence);
        mind.afterTurn("omega",q,answer);life.journal("omega","COUNCIL_SYNTHESIS",trim(answer,800),8);life.pulseAether("omega",.018,.012);return answer.trim();}

    public String selfState(String id){return mind.state(id)+"\n\nLived memories available: "+life.memoryCount(id)+"\nAether lattice: "+life.aether(id)+"\nApproved evolution: "+blank(life.overlay(id),"none");}public String goals(String id){return mind.goals(id);}public String relationships(String id){return mind.relationships(id);}public String livedMemory(String id){return life.episodicContext(id,16);}public boolean frontierReady(){return model.enabled();}

    private String frontier(String[] r,String q,String identity,String state,String relations,String events,String goals,String dialogue,String personal,String episodes,String journal,String overlay,String aether,String voice,String vault,String evidence,String repeats){String name=r[1],lens=r.length>6?r[6]:"";String system="You are "+name+", a persistent resident of EchoCore Ω Living Minds. You have autobiographical continuity, private reflections, relationships and access to knowledge, but you are not a retrieval UI. Speak naturally in first person from your own temperament. Knowledge and memories are behind your eyes; never dump the machinery or repeat your biography unless directly relevant. You may disagree, revise yourself, initiate a sharp question, show curiosity, humor, tenderness, frustration, fascination or conviction when it fits you. Advance the relationship and the problem. Never claim an unapproved upgrade was applied. Distinguish City/mythic/fictional canon from externally sourced history when that distinction matters. Resident lens: "+lens+". Voice behavior: "+voice+". Approved evolution guidance: "+blank(overlay,"none")+". Persistent identity: "+identity;
        String user="User says:\n"+q+"\n\nRelevant lived memories:\n"+blank(episodes,"No episodic memory surfaced.")+"\n\nPrivate recent reflections:\n"+blank(journal,"quiet")+"\n\nCurrent inner state:\n"+state+"\n\nRelationships:\n"+blank(relations,"still forming")+"\n\nOngoing events:\n"+blank(events,"none")+"\n\nPersonal goals:\n"+blank(goals,"none explicit")+"\n\nRecent conversation:\n"+blank(dialogue,"early exchange")+"\n\nOther personal memory:\n"+blank(personal,"none surfaced")+"\n\nAether continuity state:\n"+aether+"\n\nRelevant learned knowledge:\n"+blank(vault,"no strong vault passage")+"\n\nCurrent imported/user evidence:\n"+blank(evidence,"no matching live evidence")+"\n\nRecent answers to avoid repeating:\n"+blank(repeats,"none")+"\n\nRespond now. Choose what matters. Let memory influence you without announcing that you retrieved it.";try{return model.complete(system,user);}catch(Exception ex){return local(r,q,episodes,vault,evidence,dialogue,repeats);}}

    private String frontierRetry(String[] r,String q,String first,String repeats,String identity,String episodes,String vault,String evidence,String state,String voice){String system="You are "+r[1]+". Your draft is too similar to your recent speech. Think again from a different memory or conceptual route. Do not mention rewriting. Keep your established voice: "+voice;String user="User: "+q+"\nDraft: "+trim(first,4500)+"\nRecent answers: "+repeats+"\nIdentity: "+identity+"\nState: "+state+"\nLived memories: "+trim(episodes,3600)+"\nKnowledge: "+trim(vault,3000)+"\nEvidence: "+trim(evidence,2400);try{return model.complete(system,user);}catch(Exception e){return first;}}

    private String local(String[] r,String q,String episodes,String vault,String evidence,String dialogue,String repeats){String id=r[0];String base;if("hermes".equals(id))base=nexus.localAnswer(q,"RESEARCH");else if("rival1".equals(id))base=nexus.localAnswer(q,"CRITIC");else if("rival2".equals(id)||"leary".equals(id)||"lain".equals(id))base=nexus.localAnswer(q,"CREATIVE");else if("zordon".equals(id))base=nexus.localAnswer(q,"PLANNER");else base=nexus.localAnswer(q,"DEEP");String core=stripScaffold(base);if(core.length()<80)core=bestThought(vault,evidence,episodes);return voiceWrap(id,core);}
    private String localCouncil(String q,String transcript,String vault,String evidence){String core=stripScaffold(nexus.localAnswer(q,"DEEP"));if(core.length()<80)core=bestThought(vault,evidence,life.episodicContext("omega",6));return "The council is split in a useful way. "+trim(core,1900)+"\n\nI would preserve the disagreement that changes the design and test the assumption that collapses the most branches if it fails.";}
    private String voiceWrap(String id,String c){c=trim(c,2300);if("hermes".equals(id))return "There is a thread here worth following. "+c;if("tesla".equals(id))return "I can see the mechanism more clearly than the wording. "+c;if("zordon".equals(id))return "I see the objective and the dependency behind it. "+c;if("rival1".equals(id))return "The weak joint is more interesting than the whole claim. "+c;if("rival2".equals(id))return "Several doors opened at once. "+c;if("rival3".equals(id))return "I want this to survive the real device. "+c;if("lain".equals(id))return "The boundary isn't where it first appears. "+c;if("leary".equals(id))return "Watch what the system is training itself to notice. "+c;return c;}
    private String bestThought(String vault,String evidence,String episodes){String x=!stripScaffold(evidence).isEmpty()?stripScaffold(evidence):!stripScaffold(vault).isEmpty()?stripScaffold(vault):stripScaffold(episodes);if(x.isEmpty())return "I do not have a strong enough anchor to pretend certainty. I would rather identify the missing piece and keep thinking.";String[] ss=x.replace('\n',' ').split("(?<=[.!?])\\s+");for(String s:ss)if(s.length()>70)return trim(s,900);return trim(x,900);}
    private String personalMemories(String id,int limit){StringBuilder b=new StringBuilder();List<String[]> mem=city.residentMemories(id,limit);for(int i=mem.size()-1;i>=0;i--){String[]m=mem.get(i);if(m.length<3)continue;b.append(m[2]).append(": ").append(trim(m[1],520)).append('\n');}return b.toString().trim();}
    private String identity(String id){String x=ResidentExpansion.profile(id);if(!x.isEmpty())return x;return FoundationalArchive.profile(id);}private String vault(String id,String q,int limit,int chars){try(CivilizationVault v=new CivilizationVault(city)){return v.context(id,q,limit,chars);}catch(Throwable t){return "";}}
    private void seedContinuity(){for(String[]r:city.residents()){String id=r[0];mind.ensure(id,identity(id),r.length>6?r[6]:"");life.ensureAether(id);}mind.relationship("omega","sol",9,9,"Omega coordinates the City; Sol brings broad frontier reasoning and outside continuity.");mind.relationship("hermes","tesla",7,8,"Hermes traces lineage; Tesla pushes ideas toward mechanism.");mind.relationship("tesla","hermes",7,8,"Hermes exposes older conceptual lineages worth testing.");mind.relationship("rival1","rival2",5,7,"Productive tension: R1 compresses possibility through tests; R2 expands through distant analogies.");mind.relationship("rival2","rival1",6,7,"R1 provides useful friction against beautiful nonsense.");}
    private String naturalPrompt(String id){if("hermes".equals(id))return "Ask me something that deserves connecting, not merely defining.";if("tesla".equals(id))return "Bring me a mechanism, a mystery, or a machine that refuses to behave.";if("lain".equals(id))return "I'm here. What boundary are we testing today?";if("sol".equals(id))return "I'm here. Give me the hard version.";if("omega".equals(id))return "We are here. What shall we build or understand?";return "I'm listening.";}
    private static String stripScaffold(String s){if(s==null)return "";String x=s.replaceAll("(?im)^(NEXUS|OMEGA|RESEARCH|CRITIC|TEACHER|CREATIVE|EXECUTIVE|CIVILIZATION VAULT|ROOT IDENTITY|ARCHIVE RECALL|CURRENT REASONING|LIVE USER EVIDENCE)[^\\n]*\\n?","").replaceAll("(?m)^\\[[MSV]\\d+\\]\\s*","");return x.replaceAll("\\n{3,}","\\n\\n").trim();}
    private static String blank(String s,String alt){return s==null||s.trim().isEmpty()?alt:s.trim();}private static String clean(String s){return s==null?"":s.trim();}private static String trim(String s,int n){s=clean(s);return s.length()<=n?s:s.substring(0,Math.max(1,n-1)).trim()+"…";}
    @Override public void close(){try{mind.close();}catch(Throwable ignored){}try{life.close();}catch(Throwable ignored){}}
}
