package com.hanma.echocore;

import android.app.Activity;import android.graphics.Canvas;import android.graphics.LinearGradient;import android.graphics.Paint;import android.graphics.RadialGradient;import android.graphics.Shader;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.Gravity;import android.view.View;import android.view.Window;import android.widget.Button;import android.widget.EditText;import android.widget.FrameLayout;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import android.widget.Toast;import java.util.List;

/** Persistent conversational room for one Ascendant resident. */
public class ResidentRoomActivity extends Activity {
    private static final int TEXT=0xFFF5F7FF,MUTED=0xFF9AA9C0,TEAL=0xFF67E8D1,GOLD=0xFFF4D27A,VIOLET=0xFFAF91FF,PANEL=0xD9141B2A;
    private AscendantStore city;private String id;private String[] resident;private LinearLayout transcript;private ScrollView scroll;private EditText input;private Button send;
    @Override protected void onCreate(Bundle b){super.onCreate(b);requestWindowFeature(Window.FEATURE_NO_TITLE);id=getIntent().getStringExtra("resident_id");city=new AscendantStore(this);resident=city.resident(id);if(resident==null){finish();return;}setContentView(build());renderHistory();}
    @Override protected void onDestroy(){try{city.close();}catch(Throwable ignored){}super.onDestroy();}
    private View build(){FrameLayout root=new FrameLayout(this);root.addView(new Aura(this),new FrameLayout.LayoutParams(-1,-1));LinearLayout all=new LinearLayout(this);all.setOrientation(LinearLayout.VERTICAL);all.setPadding(dp(14),dp(14),dp(14),dp(12));FrameLayout.LayoutParams fp=new FrameLayout.LayoutParams(-1,-1);root.addView(all,fp);
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);Button back=button("‹",0x221FFFFFF, TEXT,24);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);TextView title=text(resident[1],22,TEXT,true);names.addView(title);names.addView(text(resident[2]+" · "+resident[4],10,MUTED,false));head.addView(names,new LinearLayout.LayoutParams(0,-2,1));TextView state=text(resident[5],9,"WORKING".equals(resident[5])?GOLD:TEAL,true);state.setGravity(Gravity.CENTER);state.setBackground(round(0x221FFFFFF,30));state.setPadding(dp(10),dp(6),dp(10),dp(6));head.addView(state);all.addView(head,new LinearLayout.LayoutParams(-1,-2));
        TextView room=text(resident[3],10,GOLD,true);room.setGravity(Gravity.CENTER);all.addView(room,lp(-1,-2,0,8,0,8));TextView lens=text(resident[6],10,0xCCB9C5D9,false);lens.setGravity(Gravity.CENTER);all.addView(lens,lp(-1,-2,dp(10),0,dp(10),10));
        scroll=new ScrollView(this);transcript=new LinearLayout(this);transcript.setOrientation(LinearLayout.VERTICAL);transcript.setPadding(0,dp(8),0,dp(12));scroll.addView(transcript);all.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout composer=new LinearLayout(this);composer.setGravity(Gravity.BOTTOM|Gravity.CENTER_VERTICAL);input=new EditText(this);input.setTextColor(TEXT);input.setHintTextColor(0xFF647087);input.setHint("Speak into the room…");input.setTextSize(13);input.setMinLines(1);input.setMaxLines(5);input.setPadding(dp(13),dp(9),dp(13),dp(9));input.setBackground(round(PANEL,18));composer.addView(input,new LinearLayout.LayoutParams(0,-2,1));send=button("SEND",VIOLET,0xFF05070D,10);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(dp(74),dp(48));sp.setMargins(dp(8),0,0,0);composer.addView(send,sp);send.setOnClickListener(v->send());all.addView(composer);return root;}
    private void renderHistory(){transcript.removeAllViews();List<String[]> mem=city.residentMemories(id,60);if(mem.isEmpty())addSystem("This room is quiet. Start a conversation and its local history will remain here.");else for(int i=mem.size()-1;i>=0;i--){String[]m=mem.get(i);String type=m[2];boolean shared="1".equals(m[4]);addBubble(m[1],"USER".equals(type),shared?"SHARED MEMORY":type);}scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));}
    private void send(){String q=input.getText().toString().trim();if(q.isEmpty())return;input.setText("");city.addResidentMemory(id,q,"USER",7,false);addBubble(q,true,"YOU");send.setEnabled(false);city.setResidentStatus(id,"WORKING");new Thread(()->{BrainDatabase b=null;SourceCatalog s=null;CognitiveStore c=null;AscendantStore a=null;try{b=new BrainDatabase(this);s=new SourceCatalog(this);c=new CognitiveStore(this);a=new AscendantStore(this);BrainEngine e=new BrainEngine(b);NexusOrchestrator n=new NexusOrchestrator(b,e,s,c);HybridRetriever h=new HybridRetriever(a,s,b);CouncilEngine ce=new CouncilEngine(a,h,n);String out=ce.speak(id,q);a.addResidentMemory(id,out,"RESPONSE",8,false);a.setResidentStatus(id,"HOME");runOnUiThread(()->{addBubble(out,false,resident[1].toUpperCase());send.setEnabled(true);scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));});}catch(Throwable t){city.setResidentStatus(id,"HOME");runOnUiThread(()->{addSystem("Room engine error: "+t.getClass().getSimpleName()+" · "+String.valueOf(t.getMessage()));send.setEnabled(true);});}finally{try{if(a!=null)a.close();}catch(Throwable ignored){}try{if(c!=null)c.close();}catch(Throwable ignored){}try{if(s!=null)s.close();}catch(Throwable ignored){}try{if(b!=null)b.close();}catch(Throwable ignored){}}},"ResidentRoom-"+id).start();}
    private void addBubble(String body,boolean mine,String label){LinearLayout wrap=new LinearLayout(this);wrap.setGravity(mine?Gravity.RIGHT:Gravity.LEFT);LinearLayout bubble=new LinearLayout(this);bubble.setOrientation(LinearLayout.VERTICAL);bubble.setPadding(dp(12),dp(9),dp(12),dp(10));bubble.setBackground(round(mine?0xDD25314A:0xDD111827,17));TextView lab=text(label,8,mine?TEAL:GOLD,true);bubble.addView(lab);bubble.addView(text(body,13,TEXT,false),lp(-1,-2,0,4,0,0));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams((int)(getResources().getDisplayMetrics().widthPixels*.82f),-2);wrap.addView(bubble,bp);transcript.addView(wrap,lp(-1,-2,0,4,0,5));}
    private void addSystem(String s){TextView t=text(s,10,MUTED,false);t.setGravity(Gravity.CENTER);transcript.addView(t,lp(-1,-2,dp(24),8,dp(24),8));}
    private Button button(String s,int bg,int fg,float z){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(fg);b.setTextSize(z);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(round(bg,14));return b;}private TextView text(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}private GradientDrawable round(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
    private class Aura extends View{private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);long t0=System.currentTimeMillis();Aura(android.content.Context c){super(c);}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight(),t=(System.currentTimeMillis()-t0)/1000f;p.setShader(new LinearGradient(0,0,w,h,new int[]{0xFF03060C,0xFF0A1020,0xFF100919},null,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);float pulse=1f+(float)Math.sin(t*.8f)*.08f;p.setShader(new RadialGradient(w*.5f,h*.23f,w*.65f*pulse,new int[]{0x337B5CFF,0x2217BFA5,0x00000000},null,Shader.TileMode.CLAMP));c.drawCircle(w*.5f,h*.23f,w*.65f*pulse,p);p.setShader(null);for(int i=0;i<18;i++){float y=(i+1)*h/20f;int a=10+(i%4)*4;p.setColor((a<<24)|0x0072D9FF);c.drawLine(0,y,w,y,p);}postInvalidateOnAnimation();}}
}
