package com.hanma.echocore;

import android.app.Activity;import android.content.Intent;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.Gravity;import android.widget.Button;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import java.text.DateFormat;import java.util.Date;import java.util.List;

/** Inbox for resident-initiated thoughts, discoveries and proposal notices. */
public class ResidentInboxActivity extends Activity {
    private static final int BG=0xFF05080F,PANEL=0xFF111827,TEXT=0xFFF6F8FF,MUTED=0xFF91A0B8,GOLD=0xFFF4D27A,TEAL=0xFF62E5CF,VIOLET=0xFFAA8CFF;
    private LivingMindStore store;private LinearLayout body;
    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);store=new LivingMindStore(this);setContentView(build());}
    @Override protected void onResume(){super.onResume();render();}
    @Override protected void onDestroy(){try{store.close();}catch(Throwable ignored){}super.onDestroy();}
    private LinearLayout build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(14),dp(12),dp(14),dp(12));LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);Button back=button("‹",0x22FFFFFF,TEXT);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(48),dp(46)));LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);titles.addView(text("RESIDENT INBOX",21,TEXT,true));titles.addView(text("messages they chose to initiate",9,TEAL,false));head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));root.addView(head);ScrollView sc=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(0,dp(8),0,dp(24));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));return root;}
    private void render(){body.removeAllViews();List<String[]> rows=store.messages(120);if(rows.isEmpty()){body.addView(text("The City is quiet. When a resident decides something is worth bringing to you, it will appear here.",13,MUTED,false));return;}for(String[]m:rows){long id=parse(m[0]);String resident=m[1],sender=m[2],msg=m[3],kind=m[4];int priority=parseInt(m[5],5),read=parseInt(m[7],0);LinearLayout c=card();c.addView(text((read==0?"● ":"")+sender+"  ·  "+kind,11,read==0?GOLD:MUTED,true));c.addView(text(msg,14,TEXT,false),lp(-1,-2,0,6,0,5));c.addView(text("priority "+priority+"/10 · "+when(m[8]),8,MUTED,false));LinearLayout row=new LinearLayout(this);Button room=button("OPEN ROOM",0x22FFFFFF,TEAL);room.setOnClickListener(v->{store.markRead(id);Intent i=new Intent(this,ContinuumRoomActivity.class);i.putExtra("resident_id",resident);startActivity(i);});row.addView(room,new LinearLayout.LayoutParams(0,dp(42),1));Button readBtn=button(read==0?"MARK READ":"READ",0x22FFFFFF,read==0?VIOLET:MUTED);readBtn.setEnabled(read==0);readBtn.setOnClickListener(v->{store.markRead(id);render();});LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,dp(42),1);rp.setMargins(dp(6),0,0,0);row.addView(readBtn,rp);c.addView(row,lp(-1,-2,0,8,0,0));body.addView(c,lp(-1,-2,0,0,0,8));}}
    private String when(String ts){try{return DateFormat.getDateTimeInstance(DateFormat.SHORT,DateFormat.SHORT).format(new Date(Long.parseLong(ts)));}catch(Exception e){return "";}}
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(13),dp(12),dp(13),dp(12));c.setBackground(round(PANEL,17));return c;}private Button button(String s,int bg,int fg){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(9);b.setTypeface(Typeface.DEFAULT_BOLD);b.setTextColor(fg);b.setBackground(round(bg,14));return b;}private TextView text(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}private GradientDrawable round(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}private static long parse(String s){try{return Long.parseLong(s);}catch(Exception e){return 0;}}private static int parseInt(String s,int d){try{return Integer.parseInt(s);}catch(Exception e){return d;}}
}
