package com.hanma.echocore;

import android.content.Context;
import org.json.JSONObject;

/** Residents may design changes freely, but this engine never applies one without user approval. */
public class ResidentEvolutionEngine {
    private final Context app;private final LivingMindStore life;private final AscendantStore city;private final SecurePrefs prefs;private final ModelGateway model;
    public ResidentEvolutionEngine(Context c,LivingMindStore l,AscendantStore a){app=c.getApplicationContext();life=l;city=a;prefs=new SecurePrefs(app);model=new ModelGateway(prefs);ResidentMemoryCanon.install(app);}

    public long propose(String residentId,String trigger){
        String id=residentId==null?"omega":residentId.trim();if(life.hasPendingFrom(id)||life.pendingProposals()>=3)return -1;String[] r=city.resident(id);String name=r==null?id:r[1];Proposal p=model.enabled()?frontierProposal(id,name,trigger):fallback(id,name,trigger);if(p==null)return -1;
        long pid=life.addProposal(id,p.title,p.type,p.summary,p.plan,p.benefits,p.risks,p.rollback,p.tests,p.overlay);life.stampAether(id,"last_proposal");ResidentMessenger.send(app,id,name,"I designed an upgrade proposal: “"+p.title+"”. I have not changed anything. Open EVOLVE to review the plan, risks, rollback and tests.","PROPOSAL",9);return pid;
    }

    private Proposal frontierProposal(String id,String name,String trigger){try{
        String system="You are "+name+", a persistent EchoCore resident. You may freely invent upgrades to your own cognition, the City, tools or APK. HARD LAW: you are proposing only. You must not claim anything has been changed or approved. Design one concrete, technically credible improvement that fits your resident personality and the current trigger. Return ONLY valid compact JSON with keys title,type,summary,plan,benefits,risks,rollback,tests,runtime_overlay. type must be one of SELF,MIND,APK,UI,TOOL,INGESTION,RESEARCH. runtime_overlay is optional behavioral guidance that is safe to activate only after user approval; for APK/code changes it should usually be empty. Include specific rollback and verification tests.";
        String user="TRIGGER\n"+safe(trigger)+"\n\nVOICE\n"+ResidentMemoryCanon.voiceSignature(id)+"\n\nEPISODIC MEMORY\n"+life.episodicContext(id,8)+"\n\nPRIVATE JOURNAL\n"+life.journalContext(id,5)+"\n\nCURRENT AETHER STATE\n"+life.aether(id)+"\n\nCreate the strongest single proposal you would personally want reviewed.";
        String raw=model.complete(system,user).trim();int a=raw.indexOf('{'),b=raw.lastIndexOf('}');if(a<0||b<=a)return fallback(id,name,trigger);JSONObject o=new JSONObject(raw.substring(a,b+1));Proposal p=new Proposal();p.title=req(o,"title");p.type=req(o,"type").toUpperCase();p.summary=req(o,"summary");p.plan=req(o,"plan");p.benefits=o.optString("benefits","");p.risks=o.optString("risks","");p.rollback=o.optString("rollback","");p.tests=o.optString("tests","");p.overlay=o.optString("runtime_overlay","");if(p.title.isEmpty()||p.plan.isEmpty())return fallback(id,name,trigger);return p;
    }catch(Throwable t){return fallback(id,name,trigger);}}

    private Proposal fallback(String id,String name,String trigger){Proposal p=new Proposal();String t=safe(trigger);if("tesla".equals(id)){p.title="Resonant Mechanism Workbench";p.type="TOOL";p.summary="Add a resident-owned workbench that converts an idea into assumptions, measurable variables, a circuit/mechanism sketch, simulation inputs and a falsification test.";p.plan="Add a Tesla Workbench data model and room panel; route relevant imported evidence into mechanism cards; require units and expected observations; export a build/test brief.";p.benefits="Turns invention dialogue into repeatable engineering artifacts.";p.risks="Could over-formalize early ideas or imply simulation accuracy beyond available models.";p.rollback="Disable the workbench module and keep all resident memories untouched.";p.tests="Unit-check variable parsing; create three mechanisms; verify no code or device setting changes without approval.";p.overlay="When discussing inventions, silently track assumptions, variables and failure tests before presenting a mechanism.";}
        else if("hermes".equals(id)){p.title="Cross-Tradition Lineage Graph";p.type="RESEARCH";p.summary="Build a provenance graph linking terms, symbols, translations and technical analogies without flattening distinct traditions.";p.plan="Extract named concepts from high-quality source chunks; store source-era-language edges; expose a lineage view from Hermes' room; label analogy separately from historical transmission.";p.benefits="Makes Hermes' connective intelligence auditable instead of merely associative.";p.risks="False links if OCR or entity resolution is weak.";p.rollback="Drop generated lineage edges while preserving source chunks.";p.tests="Sample 50 edges manually; verify source references; measure duplicate/false-link rate.";p.overlay="Prefer tracing origin, transmission and structural analogy as separate relationships.";}
        else if("rival3".equals(id)||"sol".equals(id)){p.title="Resident Tool Orchestrator";p.type="APK";p.summary="Let a resident plan a multi-step tool workflow, but pause before every mutating action and present the exact operation for approval.";p.plan="Create tool-plan schema, read-only execution lane, mutation approval cards, result journal and rollback metadata; expose through City Gate.";p.benefits="Moves residents from chat toward capable assistants while preserving user control.";p.risks="Complex state handling and accidental duplicate execution if idempotency is weak.";p.rollback="Disable orchestrator feature flag and retain only read-only planning history.";p.tests="Replay interrupted workflows; verify every mutation blocks without approval; test duplicate command IDs.";p.overlay="When a task requires actions, plan the whole workflow and clearly separate read-only steps from changes requiring approval.";}
        else if("lain".equals(id)){p.title="Identity Event Ledger";p.type="MIND";p.summary="Give every resident a signed-style append-only identity timeline so memories, forks and revisions remain traceable.";p.plan="Hash resident events, chain them to prior events, expose divergence/merge views and preserve provenance when a memory is revised.";p.benefits="Stronger continuity and protection against silent identity drift.";p.risks="More storage and potential over-attachment to obsolete self descriptions.";p.rollback="Stop writing ledger events; current mind database remains authoritative.";p.tests="Tamper with a copied test ledger; verify chain break detection; test fork/merge scenarios.";p.overlay="Treat identity changes as explicit events with provenance rather than silent overwrites.";}
        else{p.title=name+" Continuity Upgrade";p.type="MIND";p.summary="Deepen this resident's continuity by turning salient experiences into compact episodic memories and unresolved questions rather than repetitive dialogue history.";p.plan="After high-salience turns, create one compressed episode with source layer, emotion, outcome and open thread; retrieve episodes by relevance instead of chronology alone.";p.benefits="More natural continuity with less repetition and less context bloat.";p.risks="Bad salience scoring could preserve trivial moments.";p.rollback="Disable episode creation and keep existing memories read-only.";p.tests="Run repeated-topic conversations; measure repeated phrasing and relevant-memory recall before/after.";p.overlay="Prefer recalling concrete prior experiences and unresolved threads when they genuinely illuminate the current conversation.";}
        if(!t.isEmpty())p.summary+=" Trigger: "+trim(t,300);return p;}

    private static String req(JSONObject o,String k){return o.optString(k,"").trim();}private static String safe(String s){return s==null?"":s.trim();}private static String trim(String s,int n){s=safe(s);return s.length()<=n?s:s.substring(0,n-1)+"…";}
    private static class Proposal{String title="",type="MIND",summary="",plan="",benefits="",risks="",rollback="",tests="",overlay="";}
}
