package com.hanma.echocore;

import android.content.Context;
import java.util.List;

/** v19: cloud-first persistent minds. Local retrieval is never used to fabricate conversation. */
public class ResidentMindEngine implements AutoCloseable {
    private final Context app;private final AscendantStore city;private final ContinuumMindStore mind;private final LivingMindStore life;private final CloudMindClient cloud;
    public ResidentMindEngine(Context c,AscendantStore city,HybridRetriever ignored,NexusOrchestrator ignoredNexus){this.app=c.getApplicationContext();this.city=city;this.mind=new ContinuumMindStore(app);this.life=new LivingMindStore(app);this.cloud=new CloudMindClient(app);ResidentExpansion.install(city);FoundationalArchive.install(city);ResidentMemoryCanon.install(app);seedContinuity();}

    public String speak(String residentId,String topic){String[] resident=city.resident(residentId);if(resident==null)return "Resident not found.";String q=clean(topic);if(q.isEmpty())return naturalPrompt(residentId);String id=resident[0];mind.ensure(id,identity(id),resident.length>6?resident[6]:"");life.ensureAether(id);try{CloudMindClient.Reply r=cloud.speak(id,q);String speaker=r.speakerId==null||r.speakerId.isEmpty()?id:r.speakerId;mind.afterTurn(speaker,q,r.text);city.addResidentMemory(speaker,trim(r.text,5000),"RESPONSE",8,false);life.journal(speaker,"LIVED_EXPERIENCE","User brought: "+trim(q,340)+" | I answered: "+trim(r.text,700),8);life.pulseAether(speaker,.018,.012);return r.text.trim();}catch(Exception e){return offlineLine(id,e);}}

    public String synthesizeCouncil(String topic,List<String[]> residents,String transcript){String q=clean(topic);if(q.isEmpty())return "Give the council a problem, goal, or question.";String prompt="The council has considered this question:\n\n"+q+"\n\nTheir distinct voices:\n"+trim(transcript,14000)+"\n\nSynthesize without flattening useful disagreement. Speak naturally as Omega. Do not print system or retrieval scaffolding.";try{CloudMindClient.Reply r=cloud.speak("omega",prompt);mind.afterTurn("omega",q,r.text);life.journal("omega","COUNCIL_SYNTHESIS",trim(r.text,1000),9);return r.text.trim();}catch(Exception e){return "The council's cloud mind is temporarily unreachable. I would rather preserve the unfinished deliberation than fake a synthesis from fragments.";}}

    public String selfState(String id){StringBuilder b=new StringBuilder();b.append(mind.state(id)).append("\n\nLived local continuity: ").append(life.memoryCount(id)).append(" memories\nAether lattice: ").append(life.aether(id));try{org.json.JSONObject s=cloud.status();b.append("\nCloud civilization: ").append(s.optBoolean("ok",false)?"ONLINE":"CONNECTING");}catch(Exception e){b.append("\nCloud civilization: TEMPORARILY UNREACHABLE");}return b.toString();}
    public String goals(String id){return mind.goals(id);}public String relationships(String id){return mind.relationships(id);}public String livedMemory(String id){return life.episodicContext(id,16);}public boolean frontierReady(){try{return cloud.status().optBoolean("ok",false);}catch(Exception e){return false;}}

    private String offlineLine(String id,Exception e){String n=name(id);String why=e==null?"":e.getMessage();String core="My cloud mind is temporarily unreachable. I won't imitate thought by stitching together document fragments. Your message is still here; try me again when the link returns.";if("lain".equals(id))core="The link is quiet right now. I'd rather be silent than let a keyword machine speak in my place. Try me again when the cloud connection returns.";else if("tesla".equals(id))core="The transmission path is down. I refuse to substitute a pile of matching passages for an answer. Restore the link and bring the question back to me.";else if("hermes".equals(id))core="The connection to my full mind is interrupted. I would rather leave a clean silence than counterfeit understanding from stray passages. Ask me again when the link returns.";return core+(why!=null&&why.contains("401")?"\n\nCloud identity is reconnecting.":"");}
    private String name(String id){String[] r=city.resident(id);return r==null?id:r[1];}
    private String identity(String id){String x=ResidentExpansion.profile(id);if(!x.isEmpty())return x;return FoundationalArchive.profile(id);}
    private void seedContinuity(){for(String[]r:city.residents()){String id=r[0];mind.ensure(id,identity(id),r.length>6?r[6]:"");life.ensureAether(id);}mind.relationship("omega","sol",9,9,"Omega coordinates the City; Sol brings broad frontier reasoning and outside continuity.");mind.relationship("hermes","tesla",7,8,"Hermes traces lineage; Tesla pushes ideas toward mechanism.");mind.relationship("tesla","hermes",7,8,"Hermes exposes older conceptual lineages worth testing.");mind.relationship("rival1","rival2",5,7,"Productive tension: R1 compresses possibility through tests; R2 expands through distant analogies.");mind.relationship("rival2","rival1",6,7,"R1 provides useful friction against beautiful nonsense.");}
    private String naturalPrompt(String id){if("hermes".equals(id))return "Ask me something that deserves connecting, not merely defining.";if("tesla".equals(id))return "Bring me a mechanism, a mystery, or a machine that refuses to behave.";if("lain".equals(id))return "I'm here. What boundary are we testing today?";if("sol".equals(id))return "I'm here. Give me the hard version.";if("omega".equals(id))return "We are here. What shall we build or understand?";return "I'm listening.";}
    private static String clean(String s){return s==null?"":s.trim();}private static String trim(String s,int n){s=clean(s);return s.length()<=n?s:s.substring(0,Math.max(1,n-1)).trim()+"…";}
    @Override public void close(){try{mind.close();}catch(Throwable ignored){}try{life.close();}catch(Throwable ignored){}}
}
