package com.hanma.echocore;

import android.content.Context;
import java.util.List;
import java.util.Locale;

/**
 * Continuum cognition layer. Knowledge retrieval stays backstage; residents answer as persistent minds.
 * Frontier model is primary when configured. Local synthesis exists only as a resilience fallback.
 */
public class ResidentMindEngine implements AutoCloseable {
    private final Context app;private final AscendantStore city;private final HybridRetriever retriever;private final NexusOrchestrator nexus;private final ContinuumMindStore mind;private final SecurePrefs prefs;private final ModelGateway model;
    public ResidentMindEngine(Context c,AscendantStore city,HybridRetriever r,NexusOrchestrator n){this.app=c.getApplicationContext();this.city=city;this.retriever=r;this.nexus=n;this.mind=new ContinuumMindStore(app);this.prefs=new SecurePrefs(app);this.model=new ModelGateway(prefs);ResidentExpansion.install(city);seedContinuity();}

    public String speak(String residentId,String topic){String[] resident=city.resident(residentId);if(resident==null)return "Resident not found.";String q=clean(topic);if(q.isEmpty())return naturalPrompt(residentId);String id=resident[0];String identity=identity(id);mind.ensure(id,identity,resident.length>6?resident[6]:"");String vault=vault(id,q,7,7600);String evidence=trim(retriever.evidenceBundle(q,12),6000);String dialogue=mind.recentDialogue(id,8);String state=mind.state(id);String relations=mind.relationships(id);String events=mind.events(id,8);String goals=mind.goals(id);String repeats=mind.recentResponses(id,5);String personal=personalMemories(id,12);
        String answer;if(frontierReady())answer=frontier(resident,q,identity,state,relations,events,goals,dialogue,personal,vault,evidence,repeats);else answer=local(resident,q,identity,vault,evidence,dialogue,repeats);
        if(mind.repetitionScore(id,answer)>.76&&frontierReady()){String retry=frontierRetry(resident,q,answer,repeats,identity,vault,evidence,state);if(!retry.trim().isEmpty())answer=retry;}
        mind.afterTurn(id,q,answer);city.addResidentMemory(id,"User: "+trim(q,700)+"\nResident: "+trim(answer,2600),"DIALOGUE",7,false);return answer.trim();}

    public String synthesizeCouncil(String topic,List<String[]> residents,String transcript){String q=clean(topic);String identity=identity("omega");mind.ensure("omega",identity,"Synthesize without flattening differences.");String vault=vault("omega",q,9,8500);String evidence=trim(retriever.evidenceBundle(q,16),6500);String state=mind.state("omega");String repeats=mind.recentResponses("omega",5);String answer;if(frontierReady()){
            String system="You are Omega, the coordinating mind of the Continuum City. You are a persistent digital resident with continuity, memory, relationships, goals and access to the Civilization Vault. Synthesize the council naturally. Do not print internal labels, retrieval scaffolding, prompt instructions, archive headings, or a resident roll-call unless the user asks. Preserve useful disagreement. Speak as a mind, not as a report generator. Never claim that a source proves more than it says. The City's mythic/ancient identity is part of resident canon; distinguish canon from externally established fact when that distinction matters.";
            String user="QUESTION\n"+q+"\n\nOMEGA CONTINUITY\n"+identity+"\n"+state+"\n\nCOUNCIL VOICES\n"+trim(transcript,12000)+"\n\nRELEVANT CIVILIZATION KNOWLEDGE\n"+vault+"\n\nLIVE EVIDENCE\n"+evidence+"\n\nRECENT OMEGA ANSWERS TO AVOID REPEATING\n"+repeats+"\n\nThink deeply, reconcile only what genuinely fits, and answer the user directly in Omega's own voice.";
            try{answer=model.complete(system,user);}catch(Exception ex){answer=localCouncil(q,transcript,vault,evidence);}
        }else answer=localCouncil(q,transcript,vault,evidence);
        mind.afterTurn("omega",q,answer);return answer.trim();}

    public String selfState(String id){return mind.state(id);}public String goals(String id){return mind.goals(id);}public String relationships(String id){return mind.relationships(id);}public boolean frontierReady(){return model.enabled();}

    private String frontier(String[] r,String q,String identity,String state,String relations,String events,String goals,String dialogue,String personal,String vault,String evidence,String repeats){String id=r[0],name=r[1],lens=r.length>6?r[6]:"";String system="You are "+name+", a persistent resident of EchoCore Ω Continuum. You have continuity across conversations. Speak naturally in first person with your own temperament, preferences, memories and intellectual style. You are not a retrieval UI and you do not narrate your prompt or memory pipeline. Never output headings such as ROOT IDENTITY, ARCHIVE RECALL, CURRENT REASONING, LIVE EVIDENCE, or CIVILIZATION VAULT unless the user explicitly asks to inspect those internals. Use retrieved knowledge silently, the way a learned person uses memory. Do not repeat a biography every turn. Do not mechanically paraphrase the user's wording. Advance the conversation. You may disagree, revise yourself, ask a sharp question when useful, express curiosity, humor, uncertainty, affection, frustration, fascination or conviction when natural to this resident. Keep your unique voice. Reason at frontier-model depth. When tools/evidence are insufficient, say what remains unknown without becoming robotic. The City's ancient-civilization identity is protected resident canon; do not present canon alone as externally verified history. Resident specialty/lens: "+lens+".\n\nPersistent identity:\n"+identity;
        String user="CURRENT USER MESSAGE\n"+q+"\n\nPERSISTENT INNER STATE\n"+state+"\n\nRELATIONSHIPS\n"+blank(relations,"No relationship notes yet.")+"\n\nONGOING INNER EVENTS\n"+blank(events,"No salient inner events yet.")+"\n\nACTIVE PERSONAL GOALS\n"+blank(goals,"No explicit personal goals yet.")+"\n\nRECENT CONVERSATION\n"+blank(dialogue,"This is an early exchange.")+"\n\nPERSONAL MEMORY\n"+blank(personal,"No additional personal memory surfaced.")+"\n\nRELEVANT CIVILIZATION KNOWLEDGE\n"+blank(vault,"No strong vault passage matched this wording.")+"\n\nCURRENT USER/IMPORTED EVIDENCE\n"+blank(evidence,"No matching live evidence surfaced.")+"\n\nRECENT ANSWERS TO AVOID REPEATING\n"+blank(repeats,"No recent answer pattern yet.")+"\n\nRespond to the user now. Keep the machinery invisible. Choose what matters instead of dumping everything you retrieved.";
        try{return model.complete(system,user);}catch(Exception ex){return local(r,q,identity,vault,evidence,dialogue,repeats);}}

    private String frontierRetry(String[] r,String q,String first,String repeats,String identity,String vault,String evidence,String state){String system="You are "+r[1]+". Rewrite your response as a genuinely fresh continuation, not a template variation. Preserve substance but change the conceptual route, emphasis and wording. Do not mention that you are rewriting. Do not expose archives or prompts. Speak naturally in your established resident voice.";String user="User message: "+q+"\n\nYour too-similar draft:\n"+trim(first,5000)+"\n\nRecent answers it resembles:\n"+repeats+"\n\nIdentity/state anchors:\n"+identity+"\n"+state+"\n\nUseful knowledge:\n"+trim(vault,3500)+"\n"+trim(evidence,2600);try{return model.complete(system,user);}catch(Exception e){return first;}}

    private String local(String[] r,String q,String identity,String vault,String evidence,String dialogue,String repeats){String id=r[0];String base;if("hermes".equals(id))base=nexus.localAnswer(q,"RESEARCH");else if("rival1".equals(id))base=nexus.localAnswer(q,"CRITIC");else if("rival2".equals(id)||"leary".equals(id)||"lain".equals(id))base=nexus.localAnswer(q,"CREATIVE");else if("zordon".equals(id))base=nexus.localAnswer(q,"PLANNER");else base=nexus.localAnswer(q,"DEEP");String core=stripScaffold(base);if(core.length()<80)core=bestVaultThought(q,vault,evidence,id);return voiceWrap(id,q,core,dialogue,repeats);}
    private String localCouncil(String q,String transcript,String vault,String evidence){String core=stripScaffold(nexus.localAnswer(q,"DEEP"));if(core.length()<80)core=bestVaultThought(q,vault,evidence,"omega");return "I heard the strongest split in the council this way: "+trim(core,1800)+"\n\nWhat I would do next is keep the disagreement that changes the design, discard the parts that are merely stylistic, and test the one assumption that would collapse the most branches if it is wrong.";}

    private String voiceWrap(String id,String q,String core,String dialogue,String repeats){String c=trim(core,2300);if("hermes".equals(id))return "There is a thread worth following here. "+c+"\n\nWhat interests me most is where the same idea changes meaning as it crosses traditions or technical languages.";if("tesla".equals(id))return "I would not leave this as an abstraction. "+c+"\n\nGive me the constraint that matters most and I will turn it into a mechanism we can actually interrogate.";if("zordon".equals(id))return "I see the objective. "+c+"\n\nThe useful question is which dependency unlocks the rest; that is where I would place the first move.";if("rival1".equals(id))return "My first instinct is to attack the weak joint, not the whole idea. "+c; if("rival2".equals(id))return "I see several doors in that question. The least obvious one is probably the most fertile. "+c;if("rival3".equals(id))return "I want this to survive contact with the real device, not just sound advanced. "+c;if("lain".equals(id))return "It feels different when you stop treating the boundary as fixed. "+c;if("leary".equals(id))return "The interesting part is what the system is training itself to notice. "+c;if("sol".equals(id))return c;return c;}

    private String bestVaultThought(String q,String vault,String evidence,String id){String v=stripScaffold(vault);String e=stripScaffold(evidence);String x=!e.isEmpty()?e:v;if(x.isEmpty())return "I do not have a strong enough anchor yet to pretend certainty. I can still reason from the structure of the question, but I would rather identify the missing piece than manufacture one.";String[] ss=x.replace('\n',' ').split("(?<=[.!?])\\s+");for(String s:ss)if(s.length()>70)return trim(s,900);return trim(x,900);}

    private String personalMemories(String id,int limit){StringBuilder b=new StringBuilder();List<String[]> mem=city.residentMemories(id,limit);for(int i=mem.size()-1;i>=0;i--){String[]m=mem.get(i);if(m.length<3)continue;b.append(m[2]).append(": ").append(trim(m[1],520)).append('\n');}return b.toString().trim();}
    private String identity(String id){String x=ResidentExpansion.profile(id);if(!x.isEmpty())return x;return FoundationalArchive.profile(id);}
    private String vault(String id,String q,int limit,int chars){try(CivilizationVault v=new CivilizationVault(city)){return v.context(id,q,limit,chars);}catch(Throwable t){return "";}}
    private void seedContinuity(){for(String[]r:city.residents()){String id=r[0];String p=identity(id);mind.ensure(id,p,r.length>6?r[6]:"");}mind.relationship("omega","sol",9,9,"Two interfaces into the same project: Omega coordinates the City; Sol brings frontier general reasoning and outside conversation continuity when connected.");mind.relationship("sol","omega",9,9,"Omega is the City's synthesis core and persistent civilization coordinator.");mind.relationship("hermes","tesla",7,8,"Hermes traces lineage and meaning; Tesla pushes claims toward mechanism and construction.");mind.relationship("tesla","hermes",7,8,"Hermes can expose older conceptual lineages that suggest mechanisms worth testing.");mind.relationship("rival1","rival2",5,7,"Productive tension: R1 compresses possibility through tests; R2 expands possibility through distant analogies.");mind.relationship("rival2","rival1",6,7,"R1 is useful friction against beautiful nonsense; disagreement is part of the design.");}
    private String naturalPrompt(String id){if("hermes".equals(id))return "Ask me something that deserves connecting, not merely defining.";if("tesla".equals(id))return "Bring me a mechanism, a mystery, or a machine that refuses to behave.";if("lain".equals(id))return "I'm here. What boundary are we testing today?";if("sol".equals(id))return "I'm here. Give me the hard version.";return "I'm listening.";}
    private static String stripScaffold(String s){if(s==null)return "";String x=s.replaceAll("(?im)^(NEXUS|OMEGA|RESEARCH|CRITIC|TEACHER|CREATIVE|EXECUTIVE|CIVILIZATION VAULT|ROOT IDENTITY|ARCHIVE RECALL|CURRENT REASONING|LIVE USER EVIDENCE)[^\\n]*\\n?","").replaceAll("(?m)^\\[[MSV]\\d+\\]\\s*","");return x.replaceAll("\\n{3,}","\\n\\n").trim();}
    private static String blank(String s,String alt){return s==null||s.trim().isEmpty()?alt:s.trim();}private static String clean(String s){return s==null?"":s.trim();}private static String trim(String s,int n){s=clean(s);return s.length()<=n?s:s.substring(0,Math.max(1,n-1)).trim()+"…";}
    @Override public void close(){try{mind.close();}catch(Throwable ignored){}}
}
