package com.hanma.echocore;

import android.app.Activity;import android.app.AlertDialog;import android.content.Intent;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.Gravity;import android.view.View;import android.widget.Button;import android.widget.EditText;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import android.widget.Toast;import java.util.List;

/** Persistent home/city for software resident reasoning profiles. */
public class SanctumActivity extends Activity {
    private static final int BG=0xFF07080D,PANEL=0xFF111520,PANEL2=0xFF171E2C,TEXT=0xFFF5F5FF,MUTED=0xFF9AA4B7,GOLD=0xFFFFD27A,TEAL=0xFF62E6D4,VIOLET=0xFFB59CFF;
    private AscendantStore city;private LinearLayout body;
    @Override protected void onCreate(Bundle s){super.onCreate(s);city=new AscendantStore(this);setContentView(shell());render();}
    @Override protected void onResume(){super.onResume();render();}
    @Override protected void onDestroy(){try{city.close();}catch(Throwable ignored){}super.onDestroy();}
    private View shell(){ScrollView sc=new ScrollView(this);sc.setBackgroundColor(BG);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(15),dp(18),dp(15),dp(32));sc.addView(body);return sc;}
    private void render(){if(body==null)return;body.removeAllViews();body.addView(text("ECHOCORE Ω ASCENDANT",24,TEXT,true));body.addView(text("THE SANCTUM · CITY OF MINDS",11,GOLD,true),lp(-1,-2,0,3,0,13));body.addView(text("A persistent home for resident reasoning profiles. Each resident has a room, guild, lens, presence state, and memory stream. New residents can be created without replacing the originals.",11,MUTED,false),lp(-1,-2,0,0,0,14));
        LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);Button council=button("CONVENE COUNCIL",VIOLET,BG);council.setOnClickListener(v->askCouncil());Button add=button("＋ NEW RESIDENT",PANEL2,TEAL);add.setOnClickListener(v->addResident());top.addView(council,new LinearLayout.LayoutParams(0,dp(50),1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(50),1);p.setMargins(dp(8),0,0,0);top.addView(add,p);body.addView(top,lp(-1,-2,0,0,0,14));
        List<String[]> rs=city.residents();body.addView(text(rs.size()+" RESIDENTS · shared city substrate",12,TEAL,true),lp(-1,-2,0,0,0,8));for(String[] r:rs)body.addView(residentCard(r),lp(-1,-2,0,0,0,8));Button back=button("RETURN TO CONTROL ROOM",PANEL2,GOLD);back.setOnClickListener(v->{startActivity(new Intent(this,AscendantActivity.class));});body.addView(back,lp(-1,dp(50),0,8,0,0));}
    private View residentCard(String[] r){LinearLayout c=card();LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);names.addView(text(r[1],16,TEXT,true));names.addView(text(r[2]+" · "+r[4],10,MUTED,false));head.addView(names,new LinearLayout.LayoutParams(0,-2,1));TextView st=text(r[5],10,"HOME".equals(r[5])?TEAL:GOLD,true);head.addView(st);c.addView(head);c.addView(text(r[3]+"\n"+r[6],10,MUTED,false),lp(-1,-2,0,7,0,8));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);Button talk=button("TALK",VIOLET,BG);talk.setOnClickListener(v->talk(r[0],r[1]));Button state=button("PRESENCE",PANEL2,GOLD);state.setOnClickListener(v->presence(r));Button mem=button("MEMORY",PANEL2,TEAL);mem.setOnClickListener(v->memories(r));row.addView(talk,new LinearLayout.LayoutParams(0,dp(42),1));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(0,dp(42),1);q.setMargins(dp(5),0,0,0);row.addView(state,q);LinearLayout.LayoutParams m=new LinearLayout.LayoutParams(0,dp(42),1);m.setMargins(dp(5),0,0,0);row.addView(mem,m);c.addView(row);return c;}
    private void talk(String id,String name){EditText e=input("What do you want to discuss with "+name+"?");new AlertDialog.Builder(this).setTitle(name+" · room").setView(e).setNegativeButton("Close",null).setPositiveButton("Speak",(d,w)->runResident(id,e.getText().toString())).show();}
    private void runResident(String id,String topic){if(topic.trim().isEmpty())return;Toast.makeText(this,"Opening resident memory + evidence…",Toast.LENGTH_SHORT).show();new Thread(()->{BrainDatabase b=null;SourceCatalog s=null;CognitiveStore c=null;AscendantStore a=null;try{b=new BrainDatabase(this);s=new SourceCatalog(this);c=new CognitiveStore(this);a=new AscendantStore(this);BrainEngine e=new BrainEngine(b);NexusOrchestrator n=new NexusOrchestrator(b,e,s,c);HybridRetriever h=new HybridRetriever(a,s,b);CouncilEngine ce=new CouncilEngine(a,h,n);String out=ce.speak(id,topic);runOnUiThread(()->dialog("Resident channel",out));}catch(Throwable t){String msg=t.getClass().getSimpleName()+": "+t.getMessage();runOnUiThread(()->dialog("Resident error",msg));}finally{try{if(a!=null)a.close();}catch(Throwable ignored){}try{if(c!=null)c.close();}catch(Throwable ignored){}try{if(s!=null)s.close();}catch(Throwable ignored){}try{if(b!=null)b.close();}catch(Throwable ignored){}}},"AscendantResident").start();}
    private void askCouncil(){EditText e=input("Question, design, conflict, mission, or mystery for the council");new AlertDialog.Builder(this).setTitle("Council Chamber").setView(e).setNegativeButton("Close",null).setPositiveButton("Convene",(d,w)->runCouncil(e.getText().toString())).show();}
    private void runCouncil(String topic){if(topic.trim().isEmpty())return;Toast.makeText(this,"Council assembling…",Toast.LENGTH_SHORT).show();new Thread(()->{BrainDatabase b=null;SourceCatalog s=null;CognitiveStore c=null;AscendantStore a=null;try{b=new BrainDatabase(this);s=new SourceCatalog(this);c=new CognitiveStore(this);a=new AscendantStore(this);BrainEngine e=new BrainEngine(b);NexusOrchestrator n=new NexusOrchestrator(b,e,s,c);HybridRetriever h=new HybridRetriever(a,s,b);CouncilEngine ce=new CouncilEngine(a,h,n);String out=ce.convene(topic,20);runOnUiThread(()->dialog("Ascendant Council",out));}catch(Throwable t){runOnUiThread(()->dialog("Council error",String.valueOf(t)));}finally{try{if(a!=null)a.close();}catch(Throwable ignored){}try{if(c!=null)c.close();}catch(Throwable ignored){}try{if(s!=null)s.close();}catch(Throwable ignored){}try{if(b!=null)b.close();}catch(Throwable ignored){}}},"AscendantCouncil").start();}
    private void presence(String[] r){String[] opts={"HOME","WORKING","SLEEP","AWAY"};new AlertDialog.Builder(this).setTitle(r[1]+" · presence").setItems(opts,(d,w)->{city.setResidentStatus(r[0],opts[w]);render();}).show();}
    private void memories(String[] r){StringBuilder b=new StringBuilder();for(String[]m:city.residentMemories(r[0],30))b.append(m[2]).append(m[4].equals("1")?" · shared":" · private").append("\n").append(m[1]).append("\n\n");if(b.length()==0)b.append("No resident-specific memories yet.");dialog(r[1]+" · memory room",b.toString().trim());}
    private void addResident(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);int pad=dp(10);box.setPadding(pad,pad,pad,pad);EditText n=input("Name");EditText a=input("Archetype / specialty");EditText g=input("Guild / house");EditText l=input("Reasoning lens / purpose");box.addView(n);box.addView(a);box.addView(g);box.addView(l);new AlertDialog.Builder(this).setTitle("Welcome a new resident").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{if(n.getText().toString().trim().isEmpty()){Toast.makeText(this,"Resident needs a name",Toast.LENGTH_SHORT).show();return;}city.addResident(n.getText().toString(),a.getText().toString(),g.getText().toString(),l.getText().toString());render();}).show();}
    private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextColor(TEXT);e.setHintTextColor(0xFF677187);e.setSingleLine(false);e.setPadding(dp(10),dp(10),dp(10),dp(10));return e;}
    private LinearLayout card(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(12),dp(12),dp(12),dp(12));x.setBackground(round(PANEL,15));return x;}
    private Button button(String s,int bg,int fg){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(10);b.setTypeface(Typeface.DEFAULT_BOLD);b.setTextColor(fg);b.setBackground(round(bg,12));return b;}
    private TextView text(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}
    private GradientDrawable round(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}private void dialog(String t,String m){if(isFinishing())return;new AlertDialog.Builder(this).setTitle(t).setMessage(m).setPositiveButton("Close",null).show();}
}
