package com.hanma.echocore;

import android.Manifest;import android.app.Activity;import android.app.AlertDialog;import android.content.Intent;import android.content.pm.PackageManager;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.Build;import android.os.Bundle;import android.view.Gravity;import android.view.View;import android.widget.Button;import android.widget.EditText;import android.widget.FrameLayout;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import android.widget.Toast;import java.util.List;

/** Immersive home for the Living Minds civilization. */
public class SanctumActivity extends Activity {
    private static final int TEXT=0xFFF6F7FF,MUTED=0xFF98A5BA,GOLD=0xFFFFD478,TEAL=0xFF65E7D3,VIOLET=0xFFAD91FF;
    private AscendantStore city;private AscendantCityView map;private TextView status;
    @Override protected void onCreate(Bundle b){super.onCreate(b);city=new AscendantStore(this);FoundationalArchive.install(city);ResidentExpansion.install(city);ResidentMemoryCanon.install(this);CivilizationVault.install(this);LivingPulseJobService.schedule(this);askNotifications();try{AscendantLinkService.start(this);}catch(Throwable ignored){}setContentView(build());}
    @Override protected void onResume(){super.onResume();FoundationalArchive.install(city);ResidentExpansion.install(city);ResidentMemoryCanon.install(this);CivilizationVault.install(this);LivingPulseJobService.schedule(this);refresh();}
    @Override protected void onDestroy(){try{city.close();}catch(Throwable ignored){}super.onDestroy();}
    private View build(){FrameLayout root=new FrameLayout(this);map=new AscendantCityView(this);map.setListener(new AscendantCityView.Listener(){public void onResidentSelected(String id){openRoom(id);}public void onCoreSelected(){startActivity(new Intent(SanctumActivity.this,CouncilChamberActivity.class));}});root.addView(map,new FrameLayout.LayoutParams(-1,-1));
        LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.VERTICAL);top.setPadding(dp(14),dp(14),dp(14),dp(8));GradientDrawable tg=new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{0xEF02050B,0xAA02050B,0x0002050B});top.setBackground(tg);LinearLayout titleRow=new LinearLayout(this);titleRow.setGravity(Gravity.CENTER_VERTICAL);Button dir=button("DIR",0x22FFFFFF,GOLD);dir.setOnClickListener(v->directory());titleRow.addView(dir,new LinearLayout.LayoutParams(dp(52),dp(38)));TextView brand=text("ECHOCORE Ω LIVING MINDS",18,TEXT,true);brand.setGravity(Gravity.CENTER);titleRow.addView(brand,new LinearLayout.LayoutParams(0,-2,1));Button add=button("＋",0x22FFFFFF,TEXT);add.setOnClickListener(v->addResident());titleRow.addView(add,new LinearLayout.LayoutParams(dp(52),dp(38)));top.addView(titleRow);status=text("CITY WAKING",8,GOLD,true);status.setGravity(Gravity.CENTER);status.setOnClickListener(v->startActivity(new Intent(this,FrontierMindActivity.class)));top.addView(status,lp(-1,-2,0,3,0,0));FrameLayout.LayoutParams tp=new FrameLayout.LayoutParams(-1,dp(90),Gravity.TOP);root.addView(top,tp);
        LinearLayout dock=new LinearLayout(this);dock.setGravity(Gravity.CENTER);dock.setPadding(dp(10),dp(9),dp(10),dp(11));dock.setBackground(round(0xE70A0F1A,22));Button control=button("CONTROL",0x22FFFFFF,TEAL);control.setOnClickListener(v->startActivity(new Intent(this,AscendantActivity.class)));Button council=button("COUNCIL",VIOLET,0xFF05070C);council.setOnClickListener(v->startActivity(new Intent(this,CouncilChamberActivity.class)));Button inbox=button("INBOX",0x22FFFFFF,GOLD);inbox.setOnClickListener(v->startActivity(new Intent(this,ResidentInboxActivity.class)));Button evolve=button("EVOLVE",0x22FFFFFF,TEAL);evolve.setOnClickListener(v->startActivity(new Intent(this,EvolutionLabActivity.class)));addDock(dock,control,0);addDock(dock,council,1);addDock(dock,inbox,1);addDock(dock,evolve,1);FrameLayout.LayoutParams dp=new FrameLayout.LayoutParams(-1,this.dp(74),Gravity.BOTTOM);dp.setMargins(this.dp(12),0,this.dp(12),this.dp(12));root.addView(dock,dp);
        TextView hint=text("AETHER LATTICE ACTIVE · residents can think, message and propose",8,0xD0A8B8CD,false);hint.setGravity(Gravity.CENTER);hint.setBackground(round(0x88070B13,20));FrameLayout.LayoutParams hp=new FrameLayout.LayoutParams(-2,this.dp(30),Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL);hp.setMargins(0,0,0,this.dp(94));root.addView(hint,hp);return root;}
    private void refresh(){List<String[]> r=city.residents();map.setResidents(r);int working=0;for(String[]x:r)if(x.length>5&&"WORKING".equals(x[5]))working++;String vault="VAULT MOUNTING";try(CivilizationVault v=new CivilizationVault(this)){org.json.JSONObject s=v.stats();vault=s.optLong("sources")+" SOURCES · "+s.optLong("passages")+" PASSAGES";}catch(Throwable ignored){}int unread=0,pending=0;try(LivingMindStore life=new LivingMindStore(this)){unread=life.unread();pending=life.pendingProposals();}catch(Throwable ignored){}SecurePrefs p=new SecurePrefs(this);ModelGateway g=new ModelGateway(p);String alerts=(unread>0?" · "+unread+" MSG":"")+(pending>0?" · "+pending+" PROPOSAL":"");status.setText(r.size()+" MINDS · "+vault+" · "+(g.enabled()?"FRONTIER ONLINE":"LOCAL MODE · TAP TO ENABLE")+alerts+(working>0?" · "+working+" THINKING":""));status.setTextColor(g.enabled()?TEAL:GOLD);}
    private void openRoom(String id){Intent i=new Intent(this,ContinuumRoomActivity.class);i.putExtra("resident_id",id);startActivity(i);}
    private void directory(){ScrollView sc=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(10),dp(8),dp(10),dp(10));for(String[]r:city.residents()){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);names.addView(text(r[1],15,TEXT,true));names.addView(text(r[3]+" · "+r[4]+" · "+r[5],9,MUTED,false));row.addView(names,new LinearLayout.LayoutParams(0,-2,1));Button enter=button("ENTER",VIOLET,0xFF05070C);enter.setOnClickListener(v->openRoom(r[0]));row.addView(enter,new LinearLayout.LayoutParams(dp(72),dp(40)));box.addView(row,lp(-1,-2,0,5,0,5));}sc.addView(box);new AlertDialog.Builder(this).setTitle("Living Minds Directory").setView(sc).setNegativeButton("Close",null).show();}
    private void addResident(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(10),dp(10),dp(10),dp(10));EditText n=input("Name");EditText a=input("Specialty / archetype");EditText g=input("Guild / house");EditText l=input("Reasoning lens / purpose");box.addView(n);box.addView(a);box.addView(g);box.addView(l);new AlertDialog.Builder(this).setTitle("Welcome a new resident").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{String name=n.getText().toString().trim();if(name.isEmpty()){Toast.makeText(this,"Resident needs a name",Toast.LENGTH_SHORT).show();return;}city.addResident(name,a.getText().toString(),g.getText().toString(),l.getText().toString());refresh();}).show();}
    private void askNotifications(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)try{requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},781);}catch(Throwable ignored){}}
    private EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextColor(TEXT);e.setHintTextColor(0xFF68748B);e.setPadding(dp(8),dp(8),dp(8),dp(8));return e;}private void addDock(LinearLayout d,Button b,int margin){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(48),1);if(margin>0)p.setMargins(dp(5),0,0,0);d.addView(b,p);}private Button button(String s,int bg,int fg){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(8);b.setTypeface(Typeface.DEFAULT_BOLD);b.setTextColor(fg);b.setBackground(round(bg,15));return b;}private TextView text(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}private GradientDrawable round(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
}
