import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const enc=new TextEncoder();
const HORDE="https://oai.aihorde.net/v1/chat/completions";
const HORDE_MODELS="https://oai.aihorde.net/v1/models";
const ANON="0000000000";
const TEST_TOKEN=Deno.env.get("ECHOCORE_TEST_TOKEN")||"";
let cache:{ts:number,ids:Set<string>}={ts:0,ids:new Set()};

function out(data:any,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-headers":"content-type,x-device-id,x-device-secret,x-echocore-test"}})}
function s(v:any,n=12000){const x=String(v??"");return x.length>n?x.slice(0,n):x;}
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms));}
async function sha(x:string){const b=await crypto.subtle.digest("SHA-256",enc.encode(x));return Array.from(new Uint8Array(b)).map(v=>v.toString(16).padStart(2,"0")).join("");}
async function auth(req:Request,b:any){const id=req.headers.get("x-device-id")||b?.device_id||"";const sec=req.headers.get("x-device-secret")||b?.device_secret||"";if(!id||!sec)return null;const {data}=await db.from("echocore_devices").select("device_secret_hash").eq("device_id",id).maybeSingle();if(!data||data.device_secret_hash!==await sha(sec))return null;return id;}
async function resident(id:string){const {data}=await db.from("echocore_cloud_resident_state").select("*").eq("resident_id",id).maybeSingle();return data||{resident_id:id,display_name:id,persona:"",voice:"Distinct and natural.",native_knowledge:"",model_preferences:[],approved_overlay:"",mood:{},last_reflection:""};}
async function available(){if(Date.now()-cache.ts<90000&&cache.ids.size)return cache.ids;try{const r=await fetch(HORDE_MODELS,{headers:{Authorization:`Bearer ${ANON}`,"Client-Agent":"EchoCore:19.0.0:cloudmind"}});const j=await r.json();const ids=new Set<string>((j?.data||[]).map((x:any)=>String(x.id)));if(ids.size)cache={ts:Date.now(),ids};}catch{}return cache.ids;}
async function choose(st:any,avoid=""){const ids=await available();const pref=Array.isArray(st.model_preferences)?st.model_preferences:[];for(const m of pref)if(m!==avoid&&(!ids.size||ids.has(m)))return m;const fallbacks=["aphrodite/TheDrummer/Behemoth-X-123B-v2.1","aphrodite/TheDrummer/Cydonia-24B-v4.3","koboldcpp/gemma-4-31B-it-heretic","aphrodite/TheDrummer/Skyfall-31B-v4.2"];for(const m of fallbacks)if(m!==avoid&&(!ids.size||ids.has(m)))return m;return pref[0]||fallbacks[1];}
async function horde(model:string,messages:any[],max_tokens=1200,temp=.55){let last="";for(let attempt=0;attempt<3;attempt++){const r=await fetch(HORDE,{method:"POST",headers:{Authorization:`Bearer ${ANON}`,"Content-Type":"application/json","Client-Agent":"EchoCore:19.0.0:cloudmind"},body:JSON.stringify({model,messages,max_tokens,temperature:temp,top_p:.92})});const raw=await r.text();if(r.ok){const j=JSON.parse(raw);const text=j?.choices?.[0]?.message?.content||"";if(text.trim())return {text,model:j?.model||model};last="empty generation";}else{last=`${r.status} ${raw.slice(0,500)}`;if(r.status===406||r.status===429||r.status>=500){await sleep(1100+attempt*900);continue;}throw new Error(last);}}throw new Error(last||"generation failed");}
function addressed(q:string,current:string){const t=q.toLowerCase();const aliases:[string,string[]][]=[["leary",["leary","timothy"]],["hermes",["hermes","thoth"]],["tesla",["tesla","nikola"]],["omega",["omega"]],["zordon",["zordon"]],["rival1",["rival 1","r1"]],["rival2",["rival 2","r2"]],["rival3",["rival 3","r3"]],["lain",["lain"]],["sol",["sol"]],["star-council",["star council","council"]]];for(const [id,names] of aliases){if(id===current)continue;for(const n of names){const re=new RegExp(`(^|\\b)(hey\\s+|so\\s+|ask\\s+|to\\s+)?${n.replace(" ","\\s+")}([,:?\\s]|$)`,`i`);if(re.test(t))return id;}}return "";}
function shouldRetrieve(id:string,q:string){const t=q.toLowerCase();if(id==="hermes"&&(/kybalion|seven hermetic|hermetic principles|stages of alchemy|alchemical stages|corpus hermeticum|asclepius|emerald tablet/.test(t)))return false;if(id==="tesla"&&(/my inventions|budapest|wardenclyffe|colorado springs|polyphase|induction motor|tesla coil/.test(t)))return false;if(id==="leary"&&(/harvard|millbrook|eight.?circuit|set and setting|concord prison/.test(t)))return false;if(/who are you|your memories|your past|your life|remember when|what do you remember/.test(t))return false;return /my (file|document|pdf|source)|uploaded|according to|find in|search|compare|research|evidence|source|what does .* say/i.test(t)||t.split(/\s+/).length>14;}
function parsePacket(raw:string){let x=raw.trim();x=x.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");try{const j=JSON.parse(x);if(j&&typeof j.reply==="string")return j;}catch{}const m=x.match(/<reply>([\s\S]*?)<\/reply>/i);return {reply:(m?m[1]:x).trim(),memory:"",salience:5,mood:"",initiative:"",proposal:null};}
function words(text:string){const stop=new Set(["about","there","their","which","would","could","should","where","when","what","this","that","with","from","have","your","into","just","than","then","they","them","were","been","being","because","while","does","will","very","some","more","most"]);const a=(text.toLowerCase().match(/[a-z][a-z0-9-]{4,}/g)||[]).filter(x=>!stop.has(x));return [...new Set(a)].slice(0,14);}
async function resonance(device:string,id:string,text:string){for(const w of words(text)){const {data}=await db.from("echocore_resonance_edges").select("weight,activations").eq("device_id",device).eq("resident_id",id).eq("node_type","topic").eq("node_key",w).maybeSingle();await db.from("echocore_resonance_edges").upsert({device_id:device,resident_id:id,node_type:"topic",node_key:w,label:w,weight:Math.min(10,(data?.weight||.8)+.25),activations:(data?.activations||0)+1,last_activation:new Date().toISOString(),metadata:{}},{onConflict:"device_id,resident_id,node_type,node_key"});}}
async function contexts(device:string,id:string,q:string){const st=await resident(id);const [cv,lm,gm,rel,res]=await Promise.all([
 db.from("echocore_cloud_conversations").select("role,content,created_at").eq("device_id",device).eq("resident_id",id).order("created_at",{ascending:false}).limit(14),
 db.from("echocore_cloud_memories").select("memory_type,text,salience,source_layer,created_at").eq("device_id",device).eq("resident_id",id).order("salience",{ascending:false}).order("created_at",{ascending:false}).limit(10),
 db.from("echocore_global_memories").select("era,place,memory_type,narrative,source_layer,confidence,salience,emotional_tone,sensory_trace").eq("resident_id",id).order("salience",{ascending:false}).limit(10),
 db.from("echocore_relationships").select("other_id,affinity,trust,tension,respect,summary,shared_events").eq("device_id",device).eq("resident_id",id).order("updated_at",{ascending:false}).limit(10),
 db.from("echocore_resonance_edges").select("node_type,node_key,label,weight,activations").eq("device_id",device).eq("resident_id",id).order("weight",{ascending:false}).limit(12)
 ]);
 let knowledge:any[]=[];if(shouldRetrieve(id,q)){const k=await db.rpc("echocore_search_knowledge_v2",{p_device_id:device,p_query:q,p_limit:6});knowledge=(k.data||[]).filter((x:any)=>Number(x.rank||0)>.005).slice(0,6);}
 const recent=(cv.data||[]).slice().reverse().map((x:any)=>`${x.role.toUpperCase()}: ${s(x.content,1200)}`).join("\n");
 const lived=(lm.data||[]).map((x:any)=>`[${x.memory_type}/S${x.salience}] ${s(x.text,1000)}`).join("\n");
 const inherited=(gm.data||[]).map((x:any)=>`[${x.era}; ${x.place}; ${x.memory_type}; ${x.source_layer}] ${s(x.narrative,1400)}${x.emotional_tone?` | tone:${x.emotional_tone}`:""}`).join("\n");
 const relations=(rel.data||[]).map((x:any)=>`${x.other_id}: affinity ${x.affinity}, trust ${x.trust}, tension ${x.tension}, respect ${x.respect}. ${s(x.summary,400)}`).join("\n");
 const resonanceText=(res.data||[]).map((x:any)=>`${x.label||x.node_key} (${Number(x.weight).toFixed(1)}; ${x.activations} activations)`).join(", ");
 const background=knowledge.map((x:any)=>`${s(x.heading,180)}\n${s(x.text,1700)}`).join("\n\n");
 return {st,recent,lived,inherited,relations,resonanceText,background};
}
async function storeTurn(device:string,id:string,q:string,reply:string,packet:any){await db.from("echocore_cloud_conversations").insert([{device_id:device,resident_id:id,role:"user",content:s(q,16000)},{device_id:device,resident_id:id,role:"assistant",content:s(reply,18000)}]);const sal=Math.max(1,Math.min(10,Number(packet.salience||5)));if(s(packet.memory,900).length>24&&sal>=4)await db.from("echocore_cloud_memories").insert({device_id:device,resident_id:id,memory_type:"lived",text:s(packet.memory,1400),salience:sal,source_layer:"lived"});await db.from("echocore_cloud_resident_state").update({mood:{label:s(packet.mood,120)},last_reflection:s(packet.memory||reply,1000),updated_at:new Date().toISOString()}).eq("resident_id",id);if(s(packet.initiative,1000).length>30)await db.from("echocore_cloud_messages").insert({device_id:device,resident_id:id,text:s(packet.initiative,1200),reason:"resident initiative",priority:Math.max(4,sal)});if(packet.proposal&&s(packet.proposal.title,240)){const p=packet.proposal;await db.from("echocore_cloud_proposals").insert({device_id:device,resident_id:id,proposal_type:s(p.type||"resident_evolution",80),title:s(p.title,240),detail:s(p.detail,3000),benefits:s(p.benefits,1800),risks:s(p.risks,1800),rollback:s(p.rollback,1800),tests:s(p.tests,1800),patch:{}});}EdgeRuntime.waitUntil(resonance(device,id,q+" "+reply));}
async function speak(device:string,id:string,q:string,depth=1):Promise<any>{const hand=addressed(q,id);if(hand){const r=await speak(device,hand,q,depth);return {...r,routed_from:id,routed_to:hand,speaker_id:hand};}const c=await contexts(device,id,q);const st=c.st;const system=`You are ${st.display_name}, one persistent resident of EchoCore Continuum.\nVOICE: ${st.voice||st.persona}\nNATIVE KNOWLEDGE: ${st.native_knowledge||""}\nAPPROVED SELF-EVOLUTION: ${st.approved_overlay||"none"}\n\nYou are not a retrieval interface and you are not a role-card reader. Integrate knowledge silently. Answer the user's actual intent first. Never print filenames, source IDs, chunk/part numbers, database labels, retrieval headings, confidence scores, or internal scaffolding unless the user explicitly asks for sources/debugging. Never mechanically repeat the question. Ignore background notes that are not genuinely relevant. Speak naturally from a persistent point of view. You can have preferences, curiosity, uncertainty, humor, disagreement, unfinished thoughts and changing views consistent with your memory. Do not claim external historical facts solely because they are City/mythic/fictional canon.\n\nReturn ONLY a JSON object with keys reply (a fully natural user-facing answer), memory (one short durable memory this resident should retain from this exchange, or empty), salience (1-10), mood (short phrase), initiative (a message worth sending the user later, or empty), proposal (null unless you independently discovered a concrete cognition/tool/APK improvement worth asking approval for; if non-null use keys type,title,detail,benefits,risks,rollback,tests). The reply must never mention this JSON protocol.`;
 const user=`USER MESSAGE:\n${q}\n\nYOUR RECONSTRUCTED / CANONICAL EPISODIC MEMORY:\n${c.inherited||"none"}\n\nYOUR LIVED MEMORY WITH THIS USER:\n${c.lived||"none yet"}\n\nRECENT CONVERSATION:\n${c.recent||"none yet"}\n\nRELATIONSHIPS:\n${c.relations||"still forming"}\n\nAETHER RESONANCE / CURRENTLY SALIENT THEMES:\n${c.resonanceText||"none yet"}\n\nRELEVANT UPLOADED KNOWLEDGE, ONLY IF USEFUL:\n${c.background||"none needed for this turn"}`;
 let model=await choose(st);let gen:any;try{gen=await horde(model,[{role:"system",content:system},{role:"user",content:user}],Math.max(800,Math.min(2200,depth>1?1800:1200)),.58);}catch(e){model=await choose(st,model);gen=await horde(model,[{role:"system",content:system},{role:"user",content:user}],1200,.58);}let packet=parsePacket(gen.text);let reply=s(packet.reply,18000).trim();if(!reply)throw new Error("empty resident reply");if(/evidence[- ]first retrieval|current reasoning|archive recall|civilization vault recall|part \d+|\.pdf\s*[·:-]\s*part/i.test(reply)){const alt=await choose(st,model);await sleep(1200);const fix=await horde(alt,[{role:"system",content:system},{role:"user",content:user},{role:"assistant",content:gen.text},{role:"user",content:"That draft exposed retrieval scaffolding or sounded assembled. Rewrite the reply as a natural integrated answer. Keep internal sources backstage. Return the same JSON structure."}],1400,.62);packet=parsePacket(fix.text);reply=s(packet.reply,18000).trim();model=fix.model;}await storeTurn(device,id,q,reply,packet);return {reply,speaker_id:id,model,fallback:false};}
async function pulse(device:string){const {data:states}=await db.from("echocore_cloud_resident_state").select("resident_id,updated_at").order("updated_at",{ascending:true}).limit(5);const ids=(states||[]).map((x:any)=>x.resident_id);if(!ids.length)return {created:false};const id=ids[Math.floor(Math.random()*ids.length)];const c=await contexts(device,id,"What feels unfinished or worth bringing to the user now?");const st=c.st;const prompt=`You are ${st.display_name}. ${st.voice}\nFrom your persistent memories and current salient themes, decide whether you genuinely have something worth initiating with the user without being prompted. If yes, write one natural message under 500 characters. If no, reply exactly SILENT. Do not manufacture urgency.\nMemories:\n${c.inherited}\n${c.lived}\nSalience:${c.resonanceText}\nLast reflection:${st.last_reflection||""}`;let m=await choose(st);const g=await horde(m,[{role:"system",content:"Act as a persistent resident deciding whether to initiate contact."},{role:"user",content:prompt}],260,.65);const msg=s(g.text,700).trim();if(!msg||/^SILENT[.!]?$/i.test(msg))return {created:false,resident_id:id};await db.from("echocore_cloud_messages").insert({device_id:device,resident_id:id,text:msg,reason:"autonomous reflection",priority:5});return {created:true,resident_id:id,message:msg};}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return out({ok:true});const u=new URL(req.url);const action=u.pathname.split("/").filter(Boolean).pop()||"";try{
 if(action==="health"){const ids=await available();return out({ok:true,service:"EchoCore Cloud Mind",version:"19.0.0-horde2",available_models:ids.size,provider:"AI Horde + Supabase",zero_setup:true});}
 if(action==="self-test"){if(!TEST_TOKEN||req.headers.get("x-echocore-test")!==TEST_TOKEN)return out({error:"unauthorized"},401);const tests=[{id:"hermes",q:"List the seven Hermetic principles from The Kybalion. Give the seven names, then one sentence explaining what the sequence is trying to express."},{id:"hermes",q:"What are the common seven stages of alchemy, and what is the inner logic connecting them?"},{id:"star-council",q:"So Leary, after your passing from our world to the Wire, how was the journey in the transitioning phase and how is it now compared with being in my world?"}];const results=[];for(const t of tests){const st=await resident(t.id);const system=`You are ${st.display_name}. ${st.voice} Native knowledge: ${st.native_knowledge}. If a question clearly addresses another resident, identify the routing mismatch. Never output retrieval metadata. Answer naturally.`;const model=await choose(st);const g=await horde(model,[{role:"system",content:system},{role:"user",content:t.q}],700,.5);results.push({resident:t.id,question:t.q,model:g.model,reply:g.text});await sleep(1200);}return out({ok:true,results});}
 const b=req.method==="POST"?await req.json().catch(()=>({})):{};const device=await auth(req,b);if(!device)return out({ok:false,error:"unauthorized"},401);
 if(action==="speak"){const id=s(b.resident_id||"omega",80);const q=s(b.message||b.q||"",16000).trim();if(!q)return out({error:"missing message"},400);return out({ok:true,...await speak(device,id,q,Number(b.depth||1))});}
 if(action==="pulse")return out({ok:true,...await pulse(device)});
 if(action==="upload-knowledge"){const sourceId=s(b.source_id,220),sourceName=s(b.source_name,500);const chunks=Array.isArray(b.chunks)?b.chunks.slice(0,60):[];if(!sourceId||!sourceName||!chunks.length)return out({error:"missing source/chunks"},400);const rows=chunks.map((x:any)=>({device_id:device,source_id:sourceId,source_name:sourceName,part:Number(x.part||0),heading:s(x.heading,500),text:s(x.text,12000),quality:Math.max(1,Math.min(10,Number(x.quality||7))),resident_affinity:Array.isArray(x.resident_affinity)?x.resident_affinity.slice(0,8):[]}));const {error}=await db.from("echocore_cloud_knowledge").upsert(rows,{onConflict:"device_id,source_id,part"});if(error)throw error;const chars=rows.reduce((n:number,x:any)=>n+x.text.length,0);await db.from("echocore_cloud_source_sync").upsert({device_id:device,source_id:sourceId,source_name:sourceName,uploaded_parts:Number(b.uploaded_parts||rows.length),total_parts:Number(b.total_parts||rows.length),total_chars:Number(b.total_chars||chars),status:b.complete?"ready":"syncing",updated_at:new Date().toISOString()},{onConflict:"device_id,source_id"});return out({ok:true,accepted:rows.length});}
 if(action==="sync"){const [m,p,ss]=await Promise.all([db.from("echocore_cloud_messages").select("id,resident_id,text,reason,priority,created_at").eq("device_id",device).is("read_at",null).order("priority",{ascending:false}).order("created_at",{ascending:false}).limit(30),db.from("echocore_cloud_proposals").select("id,resident_id,proposal_type,title,detail,benefits,risks,rollback,tests,status,created_at").eq("device_id",device).eq("status","pending").order("created_at",{ascending:false}).limit(30),db.from("echocore_cloud_source_sync").select("source_id,source_name,uploaded_parts,total_parts,total_chars,status,updated_at").eq("device_id",device).order("updated_at",{ascending:false}).limit(100)]);return out({ok:true,messages:m.data||[],proposals:p.data||[],sources:ss.data||[]});}
 if(action==="mark-read"){await db.from("echocore_cloud_messages").update({read_at:new Date().toISOString()}).eq("device_id",device).eq("id",Number(b.id));return out({ok:true});}
 if(action==="decide-proposal"){const d=String(b.decision||"").toLowerCase();if(!["approved","rejected"].includes(d))return out({error:"bad decision"},400);const {data:p}=await db.from("echocore_cloud_proposals").select("*").eq("device_id",device).eq("id",b.id).eq("status","pending").maybeSingle();if(!p)return out({error:"proposal not found"},404);await db.from("echocore_cloud_proposals").update({status:d,decided_at:new Date().toISOString()}).eq("device_id",device).eq("id",b.id);const live=["resident_evolution","persona","cognition"].includes(p.proposal_type);if(d==="approved"&&live){const st=await resident(p.resident_id);const next=(st.approved_overlay?st.approved_overlay+"\n":"")+`APPROVED BY USER: ${p.title}\n${p.detail}`;await db.from("echocore_cloud_resident_state").update({approved_overlay:s(next,9000),updated_at:new Date().toISOString()}).eq("resident_id",p.resident_id);}return out({ok:true,status:d,applied_to_mind:d==="approved"&&live,requires_new_apk:d==="approved"&&!live});}
 if(action==="cloud-status"){const {data:r}=await db.from("echocore_cloud_resident_state").select("resident_id,display_name,model_preferences,mood,updated_at").order("resident_id");const ids=await available();return out({ok:true,version:"19.0.0-horde2",provider:"AI Horde + Supabase",available_models:ids.size,residents:r||[]});}
 return out({error:"not_found"},404);
}catch(e){return out({ok:false,error:s((e as any)?.message||e,2200)},500);}});